### ISSUE TITLE
https://nodejs.org/dist/v18.20.5/ files are missing

### ISSUE THREAD

**Issue by wonsange** [nodejs/help#4501] opened 2024-11-13 01:03 UTC
### Node.js Version

v18.20.5

### NPM Version

v10.7.0

### Operating System

ubuntu 22.04

### Subsystem

Other

### Description

https://nodejs.org/dist/v18.20.5/ files are missing.

I use nextjs app via netlify.
When initializing, netlify try to install the nodejs.
But, failed.

9:27:47 AM: Binary download from https://nodejs.org/dist/v18.20.5/node-v18.20.5-linux-x64.tar.xz failed, trying source.
9:27:47 AM: grep: /opt/buildhome/.nvm/.cache/bin/node-v18.20.5-linux-x64/node-v18.20.5-linux-x64.tar.xz: No such file or directory

"https://nodejs.org/dist/v18.20.5" files are missing.
"https://nodejs.org/dist/v18.20.4" files are exist.

Cannot use v18.20.5?
Do I need to select v18.20.4 forced?
Please help me.

### Before You Submit

- [X] I have looked for issues that already exist before submitting this
- [X] My issue follows the guidelines in the README file, and follows the 'How to ask a good question' guide at https://stackoverflow.com/help/how-to-ask

**Comment by RedYetiDev** [comment] 2024-11-13 01:35
This incident has been resolved

**Comment by ljharb** [comment] 2024-11-13 01:35
Duplicate of #4500.

**Closed** 2024-11-13 01:35 UTC
