### ISSUE TITLE
Cant download node js on my mac.

### ISSUE THREAD

**Issue by medhachereddy21** [nodejs/help#2244] opened 2019-10-21 15:16 UTC
* **Node.js Version**:
* **OS**:
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:

**Comment by medhachereddy21** [comment] 2019-10-21 15:19
Node.js Version: “node-v12.12.0.pkg”
OS: macOS Catalina
Scope (install, code, runtime, meta, other?): downloaded. Cannot install
Module (and version) (if relevant):

**Comment by NickNaso** [comment] 2019-10-23 09:30
@medhachereddy21 I think that your problem is the same reported here: https://github.com/nodejs/help/issues/2243 I followed this suggestion and the installation started without problems https://github.com/nodejs/help/issues/2243#issuecomment-544822742. Hope that this help you.

**Comment by ymacora** [comment] 2019-11-06 21:00
work around curl "https://nodejs.org/dist/v12.13.0/node-v12.13.0.pkg" > "$HOME/Downloads/node-latest.pkg" && sudo installer -store -pkg "$HOME/Downloads/node-latest.pkg" -target "/"

**Comment by tniessen** [comment] 2019-11-15 03:06
Due to a lack of further information from @medhachereddy21, I am closing this as a duplicate of https://github.com/nodejs/help/issues/2243.

**Closed by tniessen** 2019-11-15 03:06 UTC
