### ISSUE TITLE
Assertion failed: new_time >= loop->time, file c:\ws\deps\uv\src\win\core.c, line 309

### ISSUE THREAD

**Issue by beyondwatts** [nodejs/help#2470] opened 2020-02-15 11:49 UTC
node.js version: 12.16.0
OS: Windows 10
Hardware: Microsoft Surface Pro 7
Module: npm-cli, tape
Error: Assertion failed: new_time >= loop->time, file c:\ws\deps\uv\src\win\core.c, line 309

When running tape tests with npm run, I am receiving the error:
`
Assertion failed: new_time >= loop->time, file c:\ws\deps\uv\src\win\core.c, line 309
`

The following is reported
````
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rest-api@1.0.0 testAssertionError: `tape test/*-test.js | tap-spec`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the rest-api@1.0.0 testAssertionError script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     xxx-debug.log
````

The debug log contains the following:
````
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'testAssertionError'
1 verbose cli ]
2 info using npm@6.13.4
3 info using node@v12.16.0
4 verbose run-script [
4 verbose run-script   'pretestAssertionError',
4 verbose run-script   'testAssertionError',
4 verbose run-script   'posttestAssertionError'
4 verbose run-script ]
5 info lifecycle rest-api@1.0.0~pretestAssertionError: rest-api@1.0.0
6 info lifecycle rest-api@1.0.0~testAssertionError: rest-api@1.0.0
7 verbose lifecycle rest-api@1.0.0~testAssertionError: unsafe-perm in lifecycle true
8 verbose lifecycle rest-api@1.0.0~testAssertionError: PATH: xxx
9 verbose lifecycle rest-api@1.0.0~testAssertionError: CWD: C:\temp\rest-api
10 silly lifecycle rest-api@1.0.0~testAssertionError: Args: [ '/d /s /c', 'tape test/*-test.js | tap-spec' ]
11 silly lifecycle rest-api@1.0.0~testAssertionError: Returned: code: 1  signal: null
12 info lifecycle rest-api@1.0.0~testAssertionError: Failed to exec testAssertionError script
13 verbose stack Error: rest-api@1.0.0 testAssertionError: `tape test/*-test.js | tap-spec`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:321:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:321:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid rest-api@1.0.0
15 verbose cwd C:\temp\beyondwatts\rest-api
16 verbose Windows_NT 10.0.18363
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "testAssertionError"
18 verbose node v12.16.0
19 verbose npm  v6.13.4
20 error code ELIFECYCLE
21 error errno 1
22 error rest-api@1.0.0 testAssertionError: `tape test/*-test.js | tap-spec`
22 error Exit status 1
23 error Failed at the rest-api@1.0.0 testAssertionError script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
````

A quick google found https://github.com/libuv/libuv/issues/1633 which indicates that there could be an issue with the System Clock on the Ice Lake processor - Intel(R) Core(TM) i5-1035G4 CPU @ 1.10GHz, 1498 Mhz, 4 Core(s), 8 Logical Processor(s)

Edit: This error does not occur using the Windows Subsystem for Linux (WSL)

Appreciating that the error says this is unlikely to be a problem with npm, any ideas?

**Comment by Tim-Shaffer** [comment] 2020-02-22 22:13
Same issue  running axios .

Intel(R) Core(TM) i7-1065G7
Windows 10 Pro
Version 1903
OS build 18362.356

Unfortunately for me, this also occurs in WSL.

**Comment by gireeshpunathil** [comment] 2020-02-23 02:46
@zilched0 - can you open the windows event viewer, and check the time stamps around system events? ideally they should be ordered on time; are you able to see any entries that do not follow strict time ordering?

**Comment by swve** [comment] 2020-03-31 12:25
Hello, did you find a workaround for this yet ? Thanks

**Comment by zilched0** [comment] 2020-03-31 12:29
I moved over to WSL v1 and haven't seen the issue since (fingers crossed)... Might be an option?

**Comment by danielcomes** [comment] 2020-04-18 17:27
> Me mudé a WSL v1 y no he visto el problema desde entonces (dedos cruzados) ... ¿Podría ser una opción?

Hey!, could you tell me how to install WSL v1 in windows 10 ?

**Comment by soraryu** [comment] 2020-04-20 13:41
Same issue here.
Poking around GitHub seems to conclude that this is an Intel processor 10th gen issue in libuv, but that is not very helpful. Many node apps seem to be broken right now due to this (when accessing specific functionality), on a lot of machines.

See the lengthy discussion in https://github.com/libuv/libuv/issues/1633

**Comment by danielcomes** [comment] 2020-04-21 21:31
> Same issue here.
> Poking around GitHub seems to conclude that this is an Intel processor 10th gen issue in libuv, but that is not very helpful. Many node apps seem to be broken right now due to this (when accessing specific functionality), on a lot of machines.
> 
> See the lengthy discussion in [libuv/libuv#1633](https://github.com/libuv/libuv/issues/1633)

Hey!, I solved it installing WSL!

**Comment by jalilaviles** [comment] 2020-05-28 22:42
para resolver lo del npm not foud pueden instalar WSL (cualquier tutorial en youtube que no sea tan viejo;  luego vayan a la página https://codingpotions.com/npm-tutorial, sigan los comandos, sobre todo el que tiene init; luego vayan a la página https://www.techunits.com/topics/setup-guides/step-by-step-guide-to-install-node-red-on-ubuntu-18-04-lts/ y sigan esos pasos teambien, eso me ayudo y el node-red me volvió a funcionar, por favor me comentan para si les sirvió, no por dar las gracias, sino por saber que se aprendió algo que sirve, gracias.

**Comment by grao-github** [comment] 2020-06-14 03:20
Solved:
I had the same issue with firebase on Windows 10. I simply synchronized the clock. There is a button called "Synchronize Your Clock" under Date & Time settings. And the issue got resolved.

Regards,
Gkari[https://remitusd.com]

**Comment by NickAsher** [comment] 2020-06-14 04:12
I had the same issue, I am on windows 10 and 10th gent Intel i5
I solved it by using the above method of synchronizing the clock. Don't know how it works, but it worked.

**Comment by grao-github** [comment] 2020-06-15 06:43
I am glad it helped you :D

**Comment by thanhquan0311** [comment] 2020-06-24 09:53
Same issue, and i also click a button called "Synchronize Your Clock" but it doesn't work
I have the issue when i'm running "firebase deploy".
Please help.

**Comment by thanhquan0311** [comment] 2020-06-25 01:09
@grao-github I am on windows 10 and 10th gent Intel i5 too, but it doesn't work

**Comment by EvgeniyPeshkov** [comment] 2020-06-25 13:29
Clock synchronization, obviously, shouldn't help. I've build 14.4.0 version with [this patch](https://github.com/libuv/libuv/commit/796744869669842bd5405a71de8ba60b1556fc24).
Maybe it'll help someone. Simply, download [node.zip](https://github.com/nodejs/help/files/4831517/node.zip) and replace *node.exe* in folder, where NodeJS 14.4.0 is installed.

**Comment by 2775468731** [comment] 2020-06-30 03:22
> 显然，时钟同步在大多数情况下无济于事。我已经使用[此补丁](https://github.com/libuv/libuv/commit/796744869669842bd5405a71de8ba60b1556fc24)构建了14.4.0版本，它可以工作。
> 也许会帮助某人。只需下载[node.zip](https://github.com/nodejs/help/files/4831517/node.zip)并替换安装了_NodeJS 14.4.0_的文件夹中的node.exe。

Thank you very much.

**Comment by Krishnavithal** [comment] 2020-07-17 12:33
I have also come across the same issue when i installed firebase, i have fixed by uninstalling node and re installed it again and re installed firebase as well. Hope this might help some people, thank you...

**Comment by Lucas-L** [comment] 2020-09-09 20:32
> Clock synchronization, obviously, shouldn't help in most cases. I've build 14.4.0 version with [this patch](https://github.com/libuv/libuv/commit/796744869669842bd5405a71de8ba60b1556fc24), it works.
> Maybe it'll help someone. Simply, download [node.zip](https://github.com/nodejs/help/files/4831517/node.zip) and replace _node.exe_ in folder, where NodeJS 14.4.0 is installed.

Worked for me! Thanks.

**Comment by PoojaDurgad** [comment] 2020-09-30 10:57
@zilched0 - looks like this issue can be closed now. please let me know if that is not the case.

**Comment by PoojaDurgad** [comment] 2020-11-09 05:34
answered. closing!! feel free to re-open if it is outstanding

**Closed by PoojaDurgad** 2020-11-09 05:34 UTC

**Comment by ManelGonzalez-ops** [comment] 2021-01-03 16:33
I got to fix it thanks to EvgeniyPeshkov answer.

**Comment by Bharati-ba** [comment] 2021-05-07 05:34
> Clock synchronization, obviously, shouldn't help in most cases. I've build 14.4.0 version with [this patch](https://github.com/libuv/libuv/commit/796744869669842bd5405a71de8ba60b1556fc24), it works.
> Maybe it'll help someone. Simply, download [node.zip](https://github.com/nodejs/help/files/4831517/node.zip) and replace _node.exe_ in folder, where NodeJS 14.4.0 is install

I want 10.16.3 version for this version  it is not working

**Comment by Maxim-Mazurok** [comment] 2021-09-28 09:38
I'm getting this issue in Windows 10 VM in VirtualBox on Windows 10 host.
The clock is being unsynced for some reason, like seconds go faster/slower than on host.
Syncing time doesn't solve the clock issue.
Using node 16.4.1

**Comment by CactusWren2020** [comment] 2021-12-04 16:32
I am using Windows 10 VB, Windows 10 host as well, and the clock sync doesn't help me either. Node v16.13.1 Here is my error:
``npm ERR! code 3221226505
npm ERR! path C:\xampp\htdocs\auto_tests\duplicator-pro-tests\node_modules\puppeteer  
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node install.js
npm ERR! Assertion failed: new_time >= loop->time, file c:\ws\deps\uv\src\win\core.c, 
line 324```

**Comment by AlokJoshi** [comment] 2022-02-17 15:02
I am still getting the error after clock synchronization. I am using axios. Is there a solution for this issue or does anyone here think that using another library will help?

**Comment by lorand-horvath** [comment] 2022-07-22 11:08
Getting the error `Assertion failed: new_time >= loop->time, file c:\ws\deps\uv\src\win\core.c, line 324` with Node.js 12.22.12 on Windows 7 x64 after doing a Windows Update to latest available components as of 2022 June. Node 12 was running fine before some Windows 7 patch broke something. Very interesting to note is I'm getting the error in line 324 and not 309. Anyway, very annoying....

**Comment by juanburns** [comment] 2022-08-01 03:44
Tenía Node 14.0.0, lo desinstalé e instale la nueva versión LTS Node 16.16.0 64bits, y funciona sin problemas ahora, saludos!.

**Comment by basmith** [comment] 2023-04-05 08:48
i was getting this error in a virtualbox vm running windows.  enabling the vm option for "Enable Hardware Clock in UTC Time" seemed to resolve the issue.

**Comment by lorand-horvath** [comment] 2023-04-05 09:15
@basmith Thanks for this info. I'm just wondering what would be the equivalent fix for Windows 7 x64 (native install, not virtualbox)?
I'm still having the issue with Node 16.19.1 and latest 16.20.0 as described above in https://github.com/nodejs/help/issues/2470#issuecomment-1192459871

**Comment by SakisTsalk** [comment] 2023-04-17 07:44
Also having the same issue on Windows server 2009 vm and Node 16.14.0.

**Comment by SakisTsalk** [comment] 2023-04-17 14:16
> > Also having the same issue on Windows server 2009 vm and Node 16.14.0.
> 
> @SakisTsalk Can you give more details, please? When did it start, is it in line 309 or 324 (as I mentioned above)? Have you tried upgrading Node to 16.20+ etc.? Have you recently upgraded Windows?

I tried with node.js 18.14.0 but still same issue. The line is actually 327. 
<img width="850" alt="image" src="https://user-images.githubusercontent.com/54308664/232510588-70545a83-07e8-481f-b14b-2009fc80057b.png">
Windows server 2019 Standard 2019 not 2009 sorry. Running on VirtualBox 7.0

**Comment by akshayka** [comment] 2023-04-19 03:06
Same issue on VirtualBox 7.0. Host: Windows 11 Pro, Guest: Windows Server 2022

Assertion failed: new_time >= loop->time, file c:\ws\deps\uv\src\win\core.c, line 327

Running node; v18.13.0

Trying synchronizing the clock and also enabling hardware clock in the VirtualBox settings. Still getting the error

**Comment by McQuitty-Broadcom** [comment] 2023-05-23 17:59
Same here, with VirtualBox.

**Comment by lorand-horvath** [comment] 2023-05-24 10:51
After a clean Windows install, problem is gone.

**Comment by lucasnatanmelo** [comment] 2023-06-07 14:28
I'm with the same problem when running npm install. Using Node v18.16.0. 
Assertion failed: new_time >= loop->time, file c:\ws\deps\uv\src\win\core.c, line 327

**Comment by lucasnatanmelo** [comment] 2023-06-07 14:30
I'm with the same problem when running npm install. Using Node v18.16.0 and Win 10 on Virtual Machine Oracle.
Assertion failed: new_time >= loop->time, file c:\ws\deps\uv\src\win\core.c, line 327

This Issue can't be closed yet!!

**Comment by tsteele1432** [comment] 2023-06-07 20:14
Try restarting the computer, deleting the npm_modules folder that is created from previously running npm install wherever you running it.

**Comment by gireeshpunathil** [comment] 2023-06-08 03:04
this is due to system time drift in the host h/w, and is outside the scope of Node.js. Searching in the internet, I found an old issue https://www.virtualbox.org/ticket/15179 which may be related. Could you compare the versions and see relevance, and if possible upgrade and check?

**Comment by gouramis** [comment] 2023-07-05 21:41
getting Assertion failed: new_time >= loop->time, file c:\ws\deps\uv\src\win\core.c, line 327in 22472ms
on windows 2019 standard vm in virtual box when running npm i.
Is there any solution for this? I tried synching the clock and that didn't work either. 
I've deleted node modules and tried again and keep getting the same thing.

**Comment by AndreyArayaC** [comment] 2023-07-31 19:50
Same issue here, host windows 11 pro, VM: Windows 10 pro.
Tried uninstalling node, installing again newer versions, enabling System clock in UTC. Still not working

**Comment by gouramis** [comment] 2023-07-31 23:52
> 

Do you have a little turtle icon on your vm? Is hyperware on?

**Comment by rdk** [comment] 2023-08-09 13:37
Same problem here on Windows 10 Pro VM in VirtualBox (host system is also Windows 10 Pro).
```
$ npm i
Assertion failed: new_time >= loop->time, file c:\ws\deps\uv\src\win\core.c, line 327pleted in 9115ms
```
Tested on all latest versions of node between 14-20.
Changing VirtualBox settings or time sync settings in the VM doesn't help.

Is there any working fix/workaround? Or is it simple the case that node simply doesn't work under VirtualBox+Windows?

**Comment by rdk** [comment] 2023-08-10 08:13
> Hyper V on? You have a turtle icon? For me thats what caused this because your system clock is going slower than actual time so thats why that time assertion fails. Node does work on virtual box with windows with pretty much every windows version.
Hyper V is off on both host and VM. No turtle icon.

**Comment by gouramis** [comment] 2023-08-10 18:06
> > Hyper V on? You have a turtle icon? For me thats what caused this because your system clock is going slower than actual time so thats why that time assertion fails. Node does work on virtual box with windows with pretty much every windows version.
> 
> Hyper V is off on both host and VM. No turtle icon.

I assume you tried the other suggestions like synching your clock. I just wanted to throw my solution which was to fix that turtle icon because the turtle is what caused this failure for me.

**Comment by Yarflam** [comment] 2023-08-21 09:38
I built with Node.JS v18, it's going on! Adjust the datetime it was not enough.

**Comment by isaackearl** [comment] 2023-10-12 18:11
I'm using virtualbox, I've tried the syncing method and the enabling utc time etc... nothing seems to work for me.

**Comment by Zamiell** [comment] 2023-11-19 14:39
I ran into this today. Getting rid of the green turtle icon fixed it for me: https://forums.virtualbox.org/viewtopic.php?t=98642

**Comment by aaqibmehrban** [comment] 2024-03-31 17:58
if anyone still getting this error in virtualBox windows envirnoment.
Sycn clock did'nt work than do this.
1- Goto virtual Machine setting > acceleration>paravirtualization (**change default to KVM**)
2- Start the virtual machine and sync clock by going to change date and time setting in windows setting.

that's it.
![image](https://github.com/nodejs/help/assets/46885712/33bc1cd8-20ea-49e9-bb58-d7f6eed9789f)

this solution worked for me in latest node versions.

**Comment by gocursor** [comment] 2024-05-07 08:15
> this solution worked for me in latest node versions.
I can confirm this works for me too, BUT... it is VERY SLOW...

**Comment by hafizasad072** [comment] 2024-07-31 08:27
I am using virtual box  VM Windows 11 and facing same issue.  I did all this on my host machine

**Solution:**
- Windows Key + R - Open Run command -> type services.msc -> set **Auto Time Zone Updater** service to automatic and start. 
- Go to date and time settings and sync your clock.
- VirtualBox select VM  **Setting** and then select **System** and Enable Hardware Clock in UTC Time
- Close existing CMD and open a new one and try with your command...
- It fixed my assertion error problem. Finally.

**Comment by dntrply** [comment] 2024-08-19 11:17
Am using VirtualBox 7.0.20 and a VM Windows 11 and am facing the same issue when running the command:

`npx create-react-app my-app`

The solution suggested by @hafizasad072 did not work as well :-(

The error is:
`Assertion failed: new_time >= loop->time, file c:\ws\deps\uv\src\win\core.c, line 327pleted in 9115ms
`
Have run out of any other ideas to try!!

**Comment by hafizasad072** [comment] 2024-08-19 14:01
Have you tried

> Am using VirtualBox 7.0.20 and a VM Windows 11 and am facing the same issue when running the command:
> 
> `npx create-react-app my-app`
> 
> The solution suggested by @hafizasad072 did not work as well :-(
> 
> The error is: `Assertion failed: new_time >= loop->time, file c:\ws\deps\uv\src\win\core.c, line 327pleted in 9115ms ` Have run out of any other ideas to try!!

once you did all try to sync guest/host machine time

**Comment by gocursor** [comment] 2024-08-26 06:00
I can confirm, that the solution proposed by @hafizasad072 and extended by @dntrply is also working for me! Thank you both!
