### ISSUE TITLE
react js application cant load on chrome browser port 3000 

### ISSUE THREAD

**Issue by empirewebmd** [nodejs/help#3641] opened 2021-12-06 08:12 UTC
### Details

opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

am having the above error when trying to run my react app using npm

Am using macos monterey

### Node.js version

Not applicable.Node.js v17.2.0

### Operating system

macos monetery

### Scope

code

### Module and version

Not applicable.

**Comment by shellberg** [comment] 2021-12-06 11:14
https://roytuts.com/how-to-fix-err_ossl_evp_unsupported-in-react-js-application/

Google's your friend on this one.  Lots of other potential hits searching by that error code, e.g.
https://www.bswen.com/2021/11/reactjs-ERR_OSSL_EVP_UNSUPPORTED_error_solution.html

All pretty well agree on the cause and the workaround.

**Comment by empirewebmd** [comment] 2021-12-06 12:04
Thank you shellberg, i actually solved this using your recommendations,but i keep going through the same process everytime i create a new react project. i was looking for a one time solution, 
Regards

**Comment by RedYetiDev** [comment] 2024-04-25 13:08
*(closing, as this is a react issue, and a workaround was provided)*

**Closed by RedYetiDev** 2024-04-25 13:08 UTC
Labels: workaround provided, wrong repo
