### ISSUE TITLE
Error: socket hang up if CRLF line is missed

### ISSUE THREAD

**Issue by LavrovArtem** [nodejs/help#993] opened 2017-11-27 07:31 UTC
https://www.w3.org/Protocols/rfc2616/rfc2616-sec6.html
```
Response      = Status-Line
                *(( general-header
                 | response-header
                 | entity-header ) CRLF)
                CRLF                      // <— this required line is missed
                [ message-body ]
```
Server for reproduсing:
```js
require('net').createServer(c => {
    c.write('HTTP/1.1 301 Moved Permanently\r\n' +
            'Location: http://something.com/\r\n');
    c.end();
}).listen(1234);
```

The calling `http.request()` to `localhost:1234` throws an error with text `socket hang up`. But if I add `+ '\r\n'` to the responce, everything will work correctly.
Chrome, Firefox end IE correctly parse this invalid responce.

Any workarounds??

* **Version**: 9.1.0
* **Platform**: Win 8.1 x64

https://github.com/nodejs/node/issues/17288

**Comment by gireeshpunathil** [comment] 2018-03-10 05:30
Reproducible in other platforms as well, with latest versions.

While an invalid response is causing this issue, these facts exists:
 - there is no way for a consumer to absorb this.
 - consumer can be a server too, acting as client to other services
 - which means a bad service can cause trouble for a consumer
 - client sending a similar invalid request to the server is handled nicely - well absorbed at the HTTP parser level, that means there is a better way out for this.

recreate:
```js
var h = require('http')
var t = require('net')
var s = t.createServer((c) => {
  c.end('HTTP/1.1 200 OK \r\n')
})
s.listen(() => {
  try {
    h.request({port: s.address().port, method: 'GET'})
  } catch(e) {
    console.log(e)
  }
})
```

I think this needs to be fixed by invoking one of the client's error callbacks - `close` / `abort` / `error` etc.  /cc @nodejs/http

**Comment by bnoordhuis** [comment] 2018-03-10 08:31
I didn't check your test case but OP's test errors because Node.js can't distinguish between end-of-message and premature connection termination.

Browsers probably assume it's the former, Node.js the latter.

**Comment by gireeshpunathil** [comment] 2018-03-10 10:43
@bnoordhuis - agreed, but the main concern IMO is an endpoint crashes due to the malformed header of another, without having any way out. the error escapes both the try-catch sequence and the listeners:

```js
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: socket hang up
    at createHangUpError (_http_client.js:331:15)
    at Socket.socketOnEnd (_http_client.js:423:23)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1055:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by bnoordhuis** [comment] 2018-03-10 11:07
That's because there's no `'error'` listener.

**Comment by bnoordhuis** [comment] 2018-03-10 17:46
One on the request object should work with OP's test case (on the client, that is.)

**Comment by gireeshpunathil** [comment] 2018-03-11 05:05
#cat 993.js 

```js
var h = require('http')
require('net').createServer(c => {
    c.end('HTTP/1.1 200 OK \r\n')
}).listen(1234, () => {
  var q = h.request({port: 1234, method: 'GET'}, (s) => {
    s.on('data', (d) => {
      console.log('response data')
    })
    e.on('end', () => {
      console.log('response ended')
    })
  })
  q.on('error', (e) => {
    console.log('error caught: ' + e)
  })
})
```
#../collab/node/node 993.js 
`error caught: Error: socket hang up`

@bnoordhuis - thanks. I don't know what messup I did last time, I guess I wasn't able to distinguish between the error being thrown and the program termination.

everything looks consistent now, Ben's [earlier comment](https://github.com/nodejs/help/issues/993#issuecomment-372013216) is the bottom line for this issue - for a malformed response with server ending the response, the client action is to close the socket with an error.

Closing this with no pending action, please let me know if have concerns.

**Closed by gireeshpunathil** 2018-03-11 05:05 UTC
