### ISSUE TITLE
I'm trying to execute SOAP API from node childprocess. How do i capture the response object of API

### ISSUE THREAD

**Issue by gitautomateudemy** [nodejs/help#1320] opened 2018-06-06 18:22 UTC
* **Node.js Version**: 6
* **OS**: windows
* **Scope (install, code, runtime, meta, other?)**: runtime
* **Implementing Automation with CucumberJS  (Protractor for UI + SOAP for API)

I'm executing SOAP APIs via a bat file in childprocess. I now need to capture the response object. How can i acheive this?

Then('SOAP must be executed', function(callback){

var spawn = require('child_process').spawn
ls = spawn('cmd.exe', ['/c', 'mybatfilepath']);

	ls.stdout.on('data', function(data){
	result += data.toString();
        console.log(result);
	expect(result).contain(200);

	});
	
	ls.stderr.on('data', function(err){
	console.log(err);
	});
	
	ls.on('exit', function(exit){
	console.log(exit)
	return callback();
	});
});

Output: Always gives me the contents in .bat file but not the response of SOAP API execution.

**Comment by user-9826342** [comment] 2018-06-07 10:20
What exactly are you trying to achieve? How does you batch file look like? What is it supposed to print? Are you passing the absolute or relative path to your batch file? What is the expected output?

I tried with examle batch file and a little modified version of your script and it works fine:

**server.js**

```js
'use strict';

var cp = require('child_process');

func(result => {
  console.log(result);
});

function func(callback){
  var ls = cp.spawn('cmd.exe', ['/c', 'C:/absolute/path/to/batch/file.bat']);
  var result = Buffer.alloc(0);

  ls.stdout.on('data', data => {
    result = Buffer.concat([result, data]);
  });

  ls.stderr.on('data', err => {
    console.log(err.toString());
  });

  ls.on('exit', exit => {
    callback(result.toString());
  });
}
```

**The batch file**

```batch
@echo off
echo Hello, World!
```

Output:

```
Hello, World!
```

**Comment by gitautomateudemy** [comment] 2018-06-07 17:13
My bat file contains call to an API which is written in SOAPUI tool.  I have imported the project into an .xml & executing in bat file.

 bat file: ==============================
cd c:/project/SOAPUI/5.0.0/bin
testrunner.bat -r -a -I "D:/projectpath/SOAPUIproject.xml"
=========================================

**Comment by gitautomateudemy** [comment] 2018-06-07 17:16
I want to get the Response object or the least response code .

**Comment by user-9826342** [comment] 2018-06-07 18:12
I cannot reproduce your issue. But you may find https://github.com/nodejs/help/issues/1112 helpful, since there is explained how to properly deal with batch files (when you call one batch file from another).

What is the purpose of `"D:/projectpath/SOAPUIproject.xml"` at the end of your batch file? It should open the xml file, is this what you're trying to do? And is it opening the file properly? If not, you probably want to put command `call` before `testrunner.bat`, like so: `call testrunner.bat -r -a -I `

What you want to obtain in your node.js application? Do you want the output of `testrunner.bat`, or what? Is the `SOAPUIproject.xml` file an input or output file? You said it prints the content of your batch file. Which batch file? The one you posted here, or `testrunner.bat`?

Have you tested your application using the code I posted?

**Comment by gitautomateudemy** [comment] 2018-06-07 18:21
"D:/projectpath/SOAPUIProject.xml" contains the list of APIs (with request body)..  In order to execute SOAPUI, testrunner,bat file is required. 
Yes i want the output of testrunner.bat file(which contains the result of APIs i put in XML)  
testrunner.bat file comes in-built with SOAPUI tool. 
I have put testrunner.bat file into a .bat file & expecting the output of testrunner.bat file.

**Comment by user-9826342** [comment] 2018-06-07 18:33
I misinterpreted your batch code, I thought the `"D:/projectpath/SOAPUIproject.xml"` is on a new line. Can you please use markdown formatting next time to avoid similar confusions

<pre>
```
Encapsulate your code using tripple accents
in order to force it to display properly
```
</pre>

But anyway, you haven't answered to many of my questions. Have you tested your code using the script I provided in comment 1? Does it work properly for you when you use my script instead of yours? If not, what exactly do you get as the output? Please post the whole output of your Node.js application.

**Comment by gitautomateudemy** [comment] 2018-06-07 18:50
Yes. It gives me the output. My problem here is my child process always exits successfully with '0' on finishing even though my API fails.  I want them as : say if my API fails, my childnode should exit & provide me the FAIL status.

**Comment by user-9826342** [comment] 2018-06-07 19:08
> Yes. It gives me the output.

Which output? Correct or incorrect? I asked you *"Does it work properly for you when you use my script instead of yours?"*, so what is your answer to this? I am confused of your response.

> My problem here is my child process always exits successfully with '0' on finishing even though my API fails. I want them as : say if my API fails, my childnode should exit & provide me the FAIL status.

If you want your batch file to propagate the exit code of `testrunner.bat`, then you should use something like this:

```batch
@echo off
set errorlevel=
call testrunner.bat
echo /b %errorlevel%
```

Of course, replace `testrunner.bat` with the full path (or navigate to the `bin` directory). This batch file exits with the same exit code `testrunner.bat` exits with. In your node.js application you can use something like:

```js
ls.on('exit', exitCode => {
  console.log(`Exit code: ${exitCode}`);
  callback(result.toString());
});
```

Suppose the content of `testrunner.bat` is:

```js
@echo off
echo example
exit 5
```

then the output of `node server.js` will be:

```
Exit code: 5
example
```

As you can see, it propagates the exit code, if that was your question.

**Comment by gitautomateudemy** [comment] 2018-06-08 17:03
Thank you.. exactly what I was looking for.  Implemented and it's working fine

**Comment by gireeshpunathil** [comment] 2018-06-15 15:11
closing as answered.

**Closed by gireeshpunathil** 2018-06-15 15:11 UTC
