### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Mehak-Mehta** [nodejs/help#3362] opened 2021-05-08 16:05 UTC
Hi I was trying to run my  server but i kept getting this error. Can someone pls help. I tried everything that i could find on stackover flow but nothing worked.

![2021-05-08 (2)](https://user-images.githubusercontent.com/76558546/117545879-48782f00-b045-11eb-9e83-cac5d9334e47.png)

**Comment by Ayase-252** [comment] 2021-05-08 16:08
what command did you use to start server?

**Comment by Mehak-Mehta** [comment] 2021-05-08 16:24
> what command did you use to start server? It looks like starting command is problematic, since `node index.js index.js` is definitely wrong.

i used git bash (npm run server)

**Comment by Ayase-252** [comment] 2021-05-09 03:00
> i used git bash (npm run server)

If possible, could you show your `package.json`?

**Comment by Mehak-Mehta** [comment] 2021-05-09 05:51
sorry for the late reply. Here is my <a href="https://github.com/Mehak-Mehta/Apollo-Graphql-Server/blob/master/package.json"> package.json</a>

Btw thank you so much for your time!

**Comment by Ayase-252** [comment] 2021-05-09 08:14
Do you have an `index.js` in the root your project?

**Comment by Mehak-Mehta** [comment] 2021-05-09 09:50
> Do you have an `index.js` in the root your project?

Yes i do have an <a href="https://github.com/Mehak-Mehta/Apollo-Graphql-Server/blob/master/src/index.js">index.js</a> . I was basically working on this <a href="https://github.com/Mehak-Mehta/Apollo-Graphql-Server">project</a> (Its not complete because of this error). Can you go through it as it might help in finding a solution? I am sorry i am new to node and stuff :/ Thanks

**Comment by Ayase-252** [comment] 2021-05-09 10:08
You need to execute `src/index`.

```
diff --git a/package.json b/package.json
index 080e471..809bb1f 100644
--- a/package.json
+++ b/package.json
@@ -16,7 +16,7 @@
   "devDependencies": {},
   "scripts": {
     "test": "echo \"Error: no test specified\" && exit 1",
-    "server": "nodemon index.js"
+    "server": "nodemon src/index.js"
   },
   "author": "",
   "license": "ISC"
```

Also, you may need to change `src/index.js` to `src/index.mjs` in order to use ESM import.

**Comment by Mehak-Mehta** [comment] 2021-05-09 10:42
![2021-05-09 (2)](https://user-images.githubusercontent.com/76558546/117569047-3ea40980-b0e1-11eb-8c6f-41dfda3543f7.png)

yes that worked!! I can't thank you enough! Thank you so much @Ayase-252

**Comment by Mehak-Mehta** [comment] 2021-05-09 10:45
Should i close this issue now?

**Comment by Ayase-252** [comment] 2021-05-09 10:46
If the issue is resolved, please feel free to close it.

**Closed** 2021-05-09 10:47 UTC
