### ISSUE TITLE
How to intercept stderr from source process in destination process

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#836] opened 2017-09-20 21:32 UTC
Say I have this:

```bash
node a.js  | node b.js
```

in` a.js`, I have 
```js
process.stderr.write('foo');
```

in `b.js`, I have
```js
process.stdin.resume().on('data', function(d){
   console.log('data from stdin',d);
});
```

`foo` will get written to the terminal, but it doesn't go through b.js

I guess the only way to send stderr to b.js, is to use

`node a.js 2>&1  | node b.js`

**my question is** - is there any other way for b.js to intercept stderr from a.js?

**Comment by ORESoftware** [comment] 2017-11-12 01:24
@bnoordhuis  any ideas here? thx

**Comment by gireeshpunathil** [comment] 2018-03-26 07:16
@ORESoftware - I spent a good amount of time on this and determined that there is no `JS` way of doing this, and there is no `easy and portable` way as well, if we go to the native addon land. The problem is that the `stderr` is a pre-existing `fd` and `piping` to | from it does not look possible to me.

In either way, I would treat it as a general programming problem, not a lack of capability with Node.js.

Is it a nagging issue for you?

**Comment by gireeshpunathil** [comment] 2018-04-02 08:02
closing as answered, @ORESoftware -  please re-open if you think there is imporvments possible in Node.js

**Closed by gireeshpunathil** 2018-04-02 08:02 UTC

**Comment by the1mills** [comment] 2018-04-02 09:48
I havent look at this in awhile

But I assume we could monkeypatch

`process.stderr.write`

And have it write to `process.stdout` instead

We could toggle that behavior in a.js
