### ISSUE TITLE
map structure with string number keys converted to array

### ISSUE THREAD

**Issue by miltgrin** [nodejs/help#1277] opened 2018-05-16 02:04 UTC
Nodejs 8.11.1
latest npm components
windows 10 platform
browser is chrome
server is running on same machine as the browser.

I am making a call through ajax with a structure that has in it:
{x: {"test": {"test":{"1":{"name":"a"},"2":{"name":"B"}}}},
{"test1": {"test":{"a1":{"name":"a"},"a2":{"name":"B"}}}}
}

In the routes.js file the request has the structure converted to:
{x: {"test": {"test":[{"name":"a"},{"name":"B"}]}},
{"test1": {"test":{"a1":{"name":"a"},"a2":{"name":"B"}}}}
}

So the map that had string numbers (or numbers) as the key gets converted to an array. The numbers don't even need to be consecutive.
1 and 3 keys creates the same array.

Don't understand why or what is processing the call.

**Comment by advanceddeveloper** [comment] 2018-05-16 02:45
> I am making a call through ajax with a structure that has in it

From where do you perform an ajax call (I suppose from browser)? How do you perform an ajax call? Notice that ajax itself is not a browser feature, it is an abstraction that can be realized manually (using XMLHttpRequest) or using some framework (like jQuery). Are you doing it manually or using a framework?

> In the routes.js file the request has the structure converted to

Is your `routes.js` a server-side or client-side script? How do stringify the object you're talking about? Are you using `JSON.stringify` or some other module to do it? Also, more important, how do you parse it? Using `JSON.parse`, or in some other way?

> So the map that had string numbers (or numbers) as the key gets converted to an array.

What do you mean by a *"map"*? Are you reffering to the `Map` constructor (property of the global object) or just an ordinary object which has properties?

> The numbers don't even need to be consecutive.

What do you mean by *"consecutive"*? The order of object properties doesn't matter. Or do you mean *"numbers from continuous interval"* instead?

> Don't understand why or what is processing the call

As I said, it depends on how you stringify/parse object. Can you please share some code or explain how do you parse the objects (which function calls do you perform in order to do that)?

---

What you have there is not a valid JSON (because of `x` at the beginning), nor it is a valid JavaScript syntax (because the object containing `test1` is not assigned to a valid property name).

```js
{x: {"test": {"test":{"1":{"name":"a"},"2":{"name":"B"}}}},
{"test1": {"test":{"a1":{"name":"a"},"a2":{"name":"B"}}}}
}
```

**Comment by miltgrin** [comment] 2018-05-16 03:16
Sorry if in trying to simplify the actual structure I messed up type the
structure.  However, the actual code is correct json .
Here is the actual argument to $.ajax
{
   "url":"http://localhost/updateprescription",
   "dataType":"json",
   "type":"get",
   "data":{
      "gramedical":{
         "test":{"test":{ "1":{"name":"a"},
                          "2":{"name":"B"}
            }
         },
         "test1":{"test":{ "a1":{"name":"a"},
                     "a2":{"name":"B"}
            }
         }
      }
   }
}

In routes.js this gets converted to in the req argument (
{
   "url":"http://localhost/updateprescription",
   "dataType":"json",
   "type":"get",
   "data":{
      "gramedical":{
         "test":{"test":[{"name":"a"},
                         {"name":"B"}]
             },
         "test1":{"test":{ "a1":{"name":"a"},
                     "a2":{"name":"B"}
            }
         }
      }
   }
}

On Tue, May 15, 2018 at 7:45 PM, advanceddeveloper <notifications@github.com

**Comment by advanceddeveloper** [comment] 2018-05-16 03:44
I asked you a lot of questions and you haven't answered to any of these. One of my questions was: which framework do you use to perform ajax call, or do you perform it manually? As I can see (according to `$.ajax`) it seems that you're using jQuery, am I correct?

Another of my questions was: what is `route.js`? Is it client-side or server-side script? According to the ajax call in it, I suppose it is a client-side script. What do you mean by *"In routes.js this gets converted to in the req argument"*? How does it get converted? Do you mean the sorce code itself gets converted or just the json?

If you're using jQuery, please post the version you're using. I did the following steps in order to reproduce your problem:

1. Created a local json file with the given content
2. Performed jQuery ajax call
3. Received the expected JSON (without array)

And please post all scripts neccessary for reproducing the issue (including your server-side script and relevant client-side scripts) and also the relevant frameworks and their versions you're using.

**Comment by miltgrin** [comment] 2018-05-16 20:52
I'm sorry I missed all the questions that you had asked.

Windows 10
Chrome client
jquery 3.3.1
react 16.3.2
nodejs 8.11.1
all npm components updated to latest

It is a very complex program so I can't send it to you.  If the answers
don't help, I will have to spend some time paring it down to a much simpler
version to send to debug. I am providing a lot of summary stuff.   But the
interaction between the client and the server is straight forward and
provided below.  I'm unsure as to what process is taking the ajax call and
locating the appropriate routine on the server to process.

I have made some modifications to the original json I identified in earlier
messages to eliminate confusion of names.
Thanks in advance for the help.

Milt

I am making a call through ajax with a structure that has in it

From where do you perform an ajax call (I suppose from browser)? How do you
perform an ajax call? Notice that ajax itself is not a browser feature, it
is an abstraction that can be realized manually (using XMLHttpRequest) or
using some framework (like jQuery). Are you doing it manually or using a
framework?

I am using jquery and react.  I am making the ajax call from the client
side. I build a json object (jsonstruct) that was described in previous
email (also shown below) and make the call $.ajax(jsonstruct)

In the routes.js file the request has the structure converted to

Is your routes.js a server-side or client-side script? How do stringify the
object you're talking about? Are you using JSON.stringify or some other
module to do it? Also, more important, how do you parse it? Using JSON.parse,
or in some other way?

routes.js is a server side script.  There is a handler
*app.get("/updateprescription", function (req, res){ ..}*
that get called from the url in the jsonstruct.  I do not stringify or
parse the json into or out of the calls.  I do do a JSON.stringify in a
console.log call to see the receiving structure.  That is how I see that
the structure that was normal json has been turned into an json array.  I
also try and to just get direct access to the elements using
test.theset['3'] which returns the correct value on the client but is
undefined on the server.

So the map that had string numbers (or numbers) as the key gets converted
to an array.

What do you mean by a *"map"*? Are you reffering to the Map constructor
(property of the global object) or just an ordinary object which has
properties?

By map I was just referring to a normal JSON structure. shown below in
jsonstruct

The numbers don't even need to be consecutive.

What do you mean by *"consecutive"*? The order of object properties doesn't
matter. Or do you mean *"numbers from continuous interval"* instead?

If the keys were 0 and 1 or 3 and 6.  The arrays that somehow get produced
are the same. as seen in the data from routes.js

Don't understand why or what is processing the call

As I said, it depends on how you stringify/parse object. Can you please
share some code or explain how do you parse the objects (which function
calls do you perform in order to do that)?

the code on the client that is triggering this is:

var json = {
      url: url,
      dataType: 'json',
      type: 'get',
      data: newdata,

      success: function(data) {
         //util_app.menuLogin({"loginType" : "Logout"})
         //headnew.displayPrescriptionRender("no");
         console.log(LOGTAG1+"success");
       }.bind(this),
          error: function(xhr, status, err) {
         //console.error(url, status, err.toString());
         console.log(LOGTAG1+"failure: "+err.toString());
         }.bind(this)
   }
   console.log("saveCall "+JSON.stringify(json))
   var query = newdata;
    var test = query.gramedical.test;
    var test1 = query.gramedical.test1;
    console.log(LOGTAG1+" test  "+JSON.stringify(query.gramedical.test));
    console.log(LOGTAG1+" test.theset  "+JSON.stringify(test.theset));
    console.log(LOGTAG1+" test.theset['3']  "+JSON.stringify(test.theset['
3']));

    console.log(LOGTAG1+" test1 "+JSON.stringify(query.gramedical.test1));
    console.log(LOGTAG1+" test1.theset.a3 "+JSON.stringify(test1.theset.
a3));
    $.ajax(json);

The output on the client is;
      saveCall  test  {"theset":{"3":{"name":"a"},"6":{"name":"B"}}}
      saveCall  test.theset  {"3":{"name":"a"},"6":{"name":"B"}}
      saveCall  test.theset['3']  {"name":"a"}
      saveCall  test1 {"theset":{"a3":{"name":"a"},"a6":{"name":"B"}}}
      saveCall  test1.theset.a3 {"name":"a"}

the receiver in routes.js on the server side is

app.get("/updateprescription", function (req, res){
    var LOGTAG1 = "GET /updateprescription "
    console.log(LOGTAG1);
    var query = req.query;
    var test = query.gramedical.test;
    var test1 = query.gramedical.test1;
    console.log(LOGTAG1+" test  "+JSON.stringify(test));
    console.log(LOGTAG1+" test.theset "+JSON.stringify(test.theset));
    console.log(LOGTAG1+" test.theset['3'] "+JSON.stringify(
test.theset['3'] ));
    RecordModel.upsertPrescription(req, res);
})

the console output on the server is:
GET /updateprescription
GET /updateprescription  test  {"theset":[{"name":"a"},{"name":"B"}]}
GET /updateprescription  test.theset [{"name":"a"},{"name":"B"}]
GET /updateprescription  test.theset['3'] undefined


jsonstruct =
{
   "url":"http://localhost/updateprescription",
   "dataType":"json",
   "type":"get",
   "data":{
      "gramedical":{
         "test":{"theset":{ "3":{"name":"a"},
                          "6":{"name":"B"}
            }
         },
         "test1":{"theset":{ "a3":{"name":"a"},
                     "a6":{"name":"B"}
            }
         }
      }
   }
}

when it is processed in routes.js
{
   "url":"http://localhost/updateprescription",
   "dataType":"json",
   "type":"get",
   "data":{
      "gramedical":{
         "test":{"theset":[{"name":"a"},

...



On Tue, May 15, 2018 at 8:45 PM, advanceddeveloper <notifications@github.com

**Comment by usmanshb** [comment] 2018-05-29 10:20
And here is an interesting thing if key number is greater than 20 then this issue doesn't occur.
e.g.
splitted_field_mapping: { '9': 'v1', '21': 'v2' } } 
is recieved as : 
splitted_field_mapping: { '9': 'v1', '21': 'v2' } }

while 
splitted_field_mapping: { '9': 'v1', '20': 'v2' } }
is recieved as : 
splitted_field_mapping: { 'v1', 'v2' } }

**Comment by miltgrin** [comment] 2018-05-30 16:00
No.  I haven't found a resolution to this problem.  Hopefully someone at
nodejs can address this issue.

**Comment by gireeshpunathil** [comment] 2018-06-15 13:12
$ cat 1277.js
```js
const h = require('http')
const s = h.createServer((q, r) => {
  q.on('data', (d) => {
    console.log(JSON.parse(d))
  })
  q.on('end', () => {
    r.end('hello world!')
  })
})

s.listen(12000, () => {
  const jn = { '9': 'v1', '20': 'v2' }
  const c = h.request({port: 12000, method: 'POST'}, (m) => {
    m.on('data', (d) => {
      console.log(d.toString())
    })
  })
  c.end(JSON.stringify(jn))
})
```
$ node 1277.js
```
{ '9': 'v1', '20': 'v2' }
hello world!
```

I don't see this as happening with only Node.js in the stack - neither with the original JSON object nor with the one that @usmanshb posted. It could be an artifact with one of those upper stack modules. If you think otherwise, please work with the above code and see if you can bring in the issue.

**Comment by gireeshpunathil** [comment] 2018-06-28 07:36
closing as answered, let me know if you still have issues

**Closed by gireeshpunathil** 2018-06-28 07:36 UTC
