### ISSUE TITLE
error received when installing/loading packages

### ISSUE THREAD

**Issue by acourtney2015** [nodejs/help#1569] opened 2018-10-24 20:39 UTC
* **Node.js Version**: 8.12.0
* **OS**: windows
* **Scope (install, code, runtime, meta, other?)**: install
* **Module (and version) (if relevant)**: same error when attempting to load hyperledger-composer generator as well. have python 3.7 installed in same drive

Issue: unable to load packages and modules. Error received below. Have tried uninstalling  and reinstalling NPM/Node same error. Seems to be throwing a syntax error. Help would be greatly appreciated. Thanks!

Microsoft Windows [Version 10.0.16299.726]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\Users\001te>npm install -g composer-cli@0.19
C:\Users\001te\AppData\Roaming\npm\composer -> C:\Users\001te\AppData\Roaming\npm\node_modules\composer-cli\cli.js

> dtrace-provider@0.8.7 install C:\Users\001te\AppData\Roaming\npm\node_modules\composer-cli\node_modules\dtrace-provider
> node-gyp rebuild || node suppress-error.js

C:\Users\001te\AppData\Roaming\npm\node_modules\composer-cli\node_modules\dtrace-provider>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Users\001te\AppData\Local\Programs\Python\Python37-32\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:276:12)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:915:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\001te\AppData\Roaming\npm\node_modules\composer-cli\node_modules\dtrace-provider
gyp ERR! node -v v8.12.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

> node-report@2.2.1 install C:\Users\001te\AppData\Roaming\npm\node_modules\composer-cli\node_modules\node-report
> node-gyp rebuild

C:\Users\001te\AppData\Roaming\npm\node_modules\composer-cli\node_modules\node-report>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Users\001te\AppData\Local\Programs\Python\Python37-32\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:276:12)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:915:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\001te\AppData\Roaming\npm\node_modules\composer-cli\node_modules\node-report
gyp ERR! node -v v8.12.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\composer-cli\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-report@2.2.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-report@2.2.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\001te\AppData\Roaming\npm-cache\_logs\2018-10-24T19_20_58_018Z-debug.log

C:\Users\001te>

**Comment by NickNaso** [comment] 2018-10-24 21:09
Hi @acourtney2015,
I think that you have some problems in your configuration and when node-gyp try to compile a module that is a native module you will get the reported error. To solve the problem you need to set the environment and you can use **windows-build-tools**:
`npm install --global windows-build-tools`
For more info see at this repo:
[https://github.com/felixrieseberg/windows-build-tools](https://github.com/felixrieseberg/windows-build-tools)
Hope to be helpful.

**Comment by richardlau** [comment] 2018-10-24 22:15
@acourtney2015 The issue is that the `gyp` tool that `node-gyp` depends on was written for Python 2 and is not compatible with Python 3.

**Comment by acourtney2015** [comment] 2018-10-25 00:45
Thank you so much. That worked perfectly!

**Comment by gireeshpunathil** [comment] 2019-06-12 07:37
answered, closing

**Closed by gireeshpunathil** 2019-06-12 07:37 UTC
