### ISSUE TITLE
Two-dimensional array created with Array(dimension).fill(Array(dimension)) change value by index

### ISSUE THREAD

**Issue by sidletsky** [nodejs/help#1899] opened 2019-05-07 14:27 UTC
* **Version**: v12.1.0
* **Platform**: Windows 10 64-bit
* **Subsystem**:

Changing a value by an index i and j (random number bounded with array's dimension) in array, that was created using `Array(dimension).fill(Array(dimension))` doesn't work properly. 

Example: 
```
const matrix = Array(3).fill(Array(3));
matrix[0][0] = -4;
console.log(matrix);
```
expected output: 
```
[
  [ -4, <2 empty items> ],
  [ <3 empty items> ],
  [ <3 empty items> ]
]
```
actual output: 
```
[
  [ -4, <2 empty items> ],
  [ -4, <2 empty items> ],
  [ -4, <2 empty items> ]
]
```

However, if we create two-dimensional array using for loops, it would work. 
Example:
```
const matrix = [];
for (let i = 0; i < 3; ++i) {
  const row = [];
  for (let j = 0; j < 3; ++j) {
    row.push(undefined)
  }
  matrix.push(row)
}
matrix[0][0] = -4;
console.log(matrix);
```
expected output and actual output: 
```
[
  [ -4, undefined, undefined ],
  [ undefined, undefined, undefined ],
  [ undefined, undefined, undefined ]
]
```

**Comment by targos** [comment] 2019-05-07 14:30
Transferred to `nodejs/help` (it's not a bug).

**Comment by BridgeAR** [comment] 2019-05-07 14:39
@sidletsky when using `fill` with an object (and an array is an object) the object is created once. Thus, all entries of `matrix` contain the identical array. Changing the inner array from either reference has an impact on all references.

**Closed by BridgeAR** 2019-05-07 14:39 UTC

**Comment by Hakerh400** [comment] 2019-05-07 22:20
@sidletsky

You can create a matrix without loop:

```js
const matrix = Array(3).fill().map(() => Array(3).fill());
```

If you want a function that creates arbitrary matrix, you can use

```js
const createMatrix = dim => {
  return dim.length ? new Array(dim[0]).fill().map(
    createMatrix.bind(null, dim.slice(1))
  ) : void 0;
};
```

Then call it like

```js
const matrix = createMatrix([3, 3]);
```
