### ISSUE TITLE
Network errors

### ISSUE THREAD

**Issue by stefanosala** [nodejs/help#1759] opened 2019-02-10 20:53 UTC
* **Node.js Version**: 10.15.1
* **OS**: Linux
* **Scope (install, code, runtime, meta, other?)**: Heroku
* **Module (and version) (if relevant)**:

Hello there.
Since a month or so we're noticing a weird thing happening to our app running on Heroku. After a while, quite randomly, we're getting these types of errors:
```
2019-02-10T20:47:50.285527+00:00 app[worker.1]: Error: socket hang up
2019-02-10T20:47:50.285528+00:00 app[worker.1]: at createHangUpError (_http_client.js:323:15)
2019-02-10T20:47:50.285529+00:00 app[worker.1]: at TLSSocket.socketOnEnd (_http_client.js:426:23)
2019-02-10T20:47:50.285531+00:00 app[worker.1]: at TLSSocket.emit (events.js:194:15)
2019-02-10T20:47:50.285532+00:00 app[worker.1]: at TLSSocket.EventEmitter.emit (domain.js:441:20)
2019-02-10T20:47:50.285533+00:00 app[worker.1]: at endReadableNT (_stream_readable.js:1103:12)
2019-02-10T20:47:50.285535+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:63:19)
```

```
2019-02-10T20:51:32.150387+00:00 app[worker.16]: Error: Client network socket disconnected before secure TLS connection was established
2019-02-10T20:51:32.150389+00:00 app[worker.16]: at TLSSocket.onConnectEnd (_tls_wrap.js:1088:19)
2019-02-10T20:51:32.150391+00:00 app[worker.16]: at Object.onceWrapper (events.js:277:13)
2019-02-10T20:51:32.150392+00:00 app[worker.16]: at TLSSocket.emit (events.js:194:15)
2019-02-10T20:51:32.150394+00:00 app[worker.16]: at TLSSocket.EventEmitter.emit (domain.js:441:20)
2019-02-10T20:51:32.150395+00:00 app[worker.16]: at endReadableNT (_stream_readable.js:1103:12)
2019-02-10T20:51:32.150397+00:00 app[worker.16]: at process._tickCallback (internal/process/next_tick.js:63:19)
```

Both of the above are connection towards https endpoint that are running fine otherwise and we need to restart the dynos to get over these errors. We're not sure how to debug it and get to the source of the error.

Help?

## Edit

From this graph it seems the event loop goes crazy:
![](http://drops.stefanosala.name.s3-eu-west-1.amazonaws.com/Screen-Shot-2019-02-10-22-30-20/Screen-Shot-2019-02-10-22-30-20.png)

**Comment by rdunk** [comment] 2019-04-09 09:49
@stefanosala Did you ever find the cause of this? I'm seeing similar behaviour with a Dokku app. Also connecting to an https endpoint that is running fine and have to restart the restart/redeploy the app to resolve.

**Comment by stefanosala** [comment] 2019-04-09 09:50
@rdunk not yet unfortunately :( it's quite random and it's not affecting our app as much anymore, luckily. My gut feel tells me that it's something internal in node networking, but I have no ideas how to debug this more.

**Comment by rdunk** [comment] 2019-04-09 10:02
@stefanosala OK! Thanks for the super quick response. I'll update here if I find anything.

**Comment by gireeshpunathil** [comment] 2019-06-19 07:17
pinging  @stefanosala @rdunk to see if these were still outstanding issues for them.

**Comment by stefanosala** [comment] 2019-06-19 07:34
@gireeshpunathil I haven't seen this happening again recently, we updated few minor versions and that might have fixed the issue.

**Comment by rdunk** [comment] 2019-06-19 08:39
I'm seeing the errors appear roughly once a week at present. I've _just_ updated from v10.15.1 (lts-alpine), to v12.4.0 (current-alpine). I'll try to remember to update here after a week or so, but safe to assume it's resolved for me if I don't update this comment.

**Comment by rdunk** [comment] 2019-06-27 10:53
Unfortunately error cropped up again yesterday. Again after roughly a week of the process running.

Behaviour has changed in that previously every request would result in this error until the process was restarted, but now it seems that some requests will work. For example it happened yesterday, and again this morning at roughly 5am and 10am for a few minutes, but requests in between seem to have worked.

Bizarre.

**Comment by gireeshpunathil** [comment] 2019-06-28 06:30
the error is composed in  `onConnectEnd` https://github.com/nodejs/node/blob/d9da0a9912aeb5a720c863bcd234e3934d895b9c/lib/_tls_wrap.js#L1352-#L1366

that is installed as a one time `end` listener in the connect method, and shutdown when the connection is established in `onConnectSecure` . Not sure if there are return paths in this method other than through shutting down the listener, that can potentially explain this behavior. @nodejs/crypto - thoughts?

**Comment by sam-github** [comment] 2019-06-28 15:45
No ideas, but running with `--trace-tls` will generate lots of debugging info, and likely show what is happening.

**Comment by rdunk** [comment] 2019-07-10 08:20
@gireeshpunathil @sam-github Very much appreciate you trying to help me with this and re-opening the ticket. 

Updating to v12.4.0 seemed to give me some improved error logging, including a stack trace which was very helpful. It seems the issue wasn't because of node, but was caused by a memory leak in my application due to the incorrect implementation of an HTTP client. It seemed the error was triggered when the application ran out of memory. I really should have noticed the pattern earlier from our performance logs, apologies.

So all resolved, please feel free to close this.

**Closed** 2019-07-10 08:21 UTC
