### ISSUE TITLE
async _flush won't fire 'end'

### ISSUE THREAD

**Issue by sezanzeb** [nodejs/help#2811] opened 2020-06-29 23:06 UTC
* **Node.js Version**: v14.2.0 and 10.19.0
* **OS**: Manjaro and Ubuntu
* **Scope (install, code, runtime, meta, other?)**: code
* **Module (and version) (if relevant)**: stream

I already tried on stackoverflow, but no answers so far: https://stackoverflow.com/questions/62580007/async-flush-wont-fire-an-end-event

The 'end' event is never fired, unleass a 'data' handler is added or `pipe.resume()` is called, as shown here:
https://nodejs.org/api/stream.html#stream_compatibility_with_older_node_js_versions

But we are not only calling `pipe.end()` as opposed to the example there (if it makes any difference), we are also calling
`pipe.read()` repeatedly as explained here: https://nodejs.org/api/stream.html#stream_event_end

```javascript
const { Transform } = require('stream')

class Pipe extends Transform {
    _transform(data, encoding, callback) {
        console.log('_transform', data.toString())
        this.push(data)
        callback()
    }

    _flush(callback) {
        process.nextTick(callback)
    }
}

const pipe = new Pipe()

pipe.on('finish', () => {
    console.log('on finish')
})

pipe.on('end', () => {
    console.log('on end')
})

pipe.write('foo')

console.log('pipe.end()')
pipe.end()

console.log('read 1', pipe.read().toString())
console.log('read 2', pipe.read())
```

output:

    _transform foo
    pipe.end()
    read 1 foo
    read 2 null
    on finish

We would expect to see an 'on end' log, even without data handler and `pipe.resume()` since we are calling `pipe.read()`.

Furthermore, using

```javascript
_flush(callback) {
    callback()
}
```

instead works fine:
    
    _transform foo
    pipe.end()
    read 1 foo
    read 2 null
    on finish
    on end

So it seems this issue is only present with asynchronous _flush code

What is going on there?

Thanks

**Comment by PoojaDurgad** [comment] 2020-10-22 07:47
closing!! as this issue is same as https://github.com/nodejs/node/issues/34520  and resolved as this is intended behavior

**Closed by PoojaDurgad** 2020-10-22 07:47 UTC
