### ISSUE TITLE
Error: write EPIPE  at WriteWrap.afterWrite

### ISSUE THREAD

**Issue by mort3za** [nodejs/help#1652] opened 2018-12-02 15:45 UTC
* **Node.js Version**: 10.14.1 (also tested with 11.3.0)
* **OS**: Linux runner-75df7aee-project-60-concurrent-0 4.4.0-124-generic #148-Ubuntu SMP Wed May 2 13:00:18 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
* **Scope (install, code, runtime, meta, other?)**: on build vuejs project
* **Module (and version) (if relevant)**:

When I build my vue.js project (created by vue cli 2) on my laptop, there is no issue but when I run a job to build the project on gitlab-ci, this error happens:  
```
$ yarn run build
yarn run v1.12.3
$ node build/build.js
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at WriteWrap.afterWrite [as oncomplete] (net.js:799:14)
Emitted 'error' event at:
    at errorOrDestroy (internal/streams/destroy.js:98:12)
    at onwriteError (_stream_writable.js:436:5)
    at onwrite (_stream_writable.js:461:5)
    at _destroy (internal/streams/destroy.js:40:7)
    at Socket._destroy (net.js:623:3)
    at Socket.destroy (internal/streams/destroy.js:32:8)
    at WriteWrap.afterWrite [as oncomplete] (net.js:801:10)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: Job failed: exit code 1
```

I tried some ways to fix it:  
- update my packages (by `yarn upgrade`)  
- update nodejs  
- use centos:7 image in gitlab-ci instead of ubuntu:latest  
- use npm instead of yarn  
- run `DEBUG=babel yarn run build`  (someone said this solved his problem but didn't worked for me)
- search all the web for it  

gitlab version is 11.0.3-ee f25aa33

my gitlab-ci job:  
```
image: ubuntu:latest

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - uname -a
    - apt-get update
    - apt-get install -y curl
    - apt-get install -y gnupg2
    - apt-get install -y git
    - curl -sL https://deb.nodesource.com/setup_10.x | bash -
    - apt-get install -y nodejs
    - curl -L https://www.npmjs.com/install.sh | sh
    - node -v
    - npm install -g yarn
    - yarn install
    - yarn run build
  artifacts:
    expire_in: 2d
    paths:
      - dist
  only:
    - pushes

#other jobs ...
```

Any help will be appreciated.

**Comment by mtaylor** [comment] 2019-03-05 21:51
@mort3za Any luck resolving this issue.  We've ran into the same issue with our Jenkins CI job.

**Comment by mtaylor** [comment] 2019-03-08 18:12
@mort3za we didn't get to the bottom of the cause but found increasing the memory in the docker container made the problem go away.

**Comment by gireeshpunathil** [comment] 2019-06-18 06:18
ping @mort3za - is this still occurring?

**Comment by gireeshpunathil** [comment] 2019-07-01 04:51
inactive, closing

**Closed by gireeshpunathil** 2019-07-01 04:51 UTC
