### ISSUE TITLE
Error: unexpected end of file at Zlib._handle.onerror (zlib.js:370:17)

### ISSUE THREAD

**Issue by vishal-biradar** [nodejs/help#658] opened 2017-06-06 11:52 UTC
I am trying to unzip the file using zlib module but getting the error as follows:
**Error: unexpected end of file at Zlib._handle.onerror (zlib.js:370:17)**

Below is my code:

```
const zlib = require('zlib');    
const unzip = zlib.createUnzip();  
const fs = require('fs');  
const inp = fs.createReadStream('input.txt.gz');  
const out = fs.createWriteStream('input1.txt');  
inp.pipe(unzip).pipe(out);
```

**Comment by addaleax** [comment] 2017-06-06 12:52
This most likely means that `input.txt.gz` is not a valid gzip file. Does `gunzip < input.txt.gz > input1.txt` work? What Node.js version are you using?

**Comment by vishal-biradar** [comment] 2017-06-06 12:56
I am using node 6.10.3.

**Comment by tranghaviet** [comment] 2018-01-16 12:36
same here. I tried both version 6 and 8.

**Comment by gireeshpunathil** [comment] 2018-03-11 14:26
just wondering whether it should be `createGunzip` rather than `createUnzip`

```patch
2c2
< const unzip = zlib.createGunzip();  
---
> const unzip = zlib.createUnzip(); 
```

can you try?

**Comment by gireeshpunathil** [comment] 2018-03-15 15:03
closing as answered, please re-open if it is still outstanding.

**Closed by gireeshpunathil** 2018-03-15 15:03 UTC

**Comment by incomingstick** [comment] 2019-12-29 04:27
Hi, I am actually looking for help on this. In case it is seen, I am downloading a .tar.gz from a Github release. I use nodejs's HTTPS to download the file. Upon inspecting the download I am able to inspect the .tar.gz with 7z, as well as run `gunzip < OpenRPG-0.5.0-win64.tar.gz > openrpg.tar` via WSL. However, when running:

```
const unzip = require('zlib').createUnzip();

const comp = fs.createReadStream(download);
const tarball = fs.createWriteStream(path.join(tmpdir, 'openrpg.tar'));

comp.pipe(unzip).pipe(tarball);
```

For greater context, I am working on packaging [this](https://github.com/incomingstick/OpenRPG) project to be downloaded via the command `node build.js download` where it would download the relevant binaries from the current release [here](https://github.com/incomingstick/OpenRPG) so that the node package is a significantly smaller size, by downloading prebuilt binaries from GitHub.

I am able to download the file _using_ the HTTPS request, and tested extracting it via both the gunzip and tar commands without error, so I can confirm that it is properly downloading the file.

If anyone ends up seeing thing, I would love some suggestions.

**Comment by addaleax** [comment] 2019-12-29 16:03
@incomingstick Can you open a new issue and a) include a link to the .gz file in question and b) include at least the Node.js version you’re using? Thanks.

@gireeshpunathil I know it’s a bit late, but why would using `.createGunzip()` instead of `.createUnzip()` help here? If it does, that’s a bug in Node.js.

**Comment by incomingstick** [comment] 2019-12-29 19:50
Hey @addaleax thanks for seeing this! I have created the issue #2377 instead of hijacking this issue. I figured since it was so old, I would try to use this thread first before adding yet another issue.

Thanks again!

**Comment by gireeshpunathil** [comment] 2019-12-30 06:22
@addaleax - 

> but why would using .createGunzip() instead of .createUnzip() help here? If it does, that’s a bug in Node.js.

I am unable to prove that theory anymore - whatever I tried, both the APIs are working fine, so consider it as invalid. I will update in case if I find evidence of the original issue.
