### ISSUE TITLE
It seems that he took the space as the interval between commands

### ISSUE THREAD

**Issue by LonelyMarch** [nodejs/help#4057] opened 2022-12-23 06:20 UTC
### Version

18.12.1

### Platform

Microsoft Windows NT 10.0.22000.0 x64

### What steps will reproduce the bug?

![image](https://user-images.githubusercontent.com/63410167/209282139-6bea53a0-8830-4426-b86e-290fe111a393.png)
It seems that no space is allowed in the path?

### How often does it reproduce? Is there a required condition?

Always

### What is the expected behavior?

Create a Vite project

### What do you see instead?

![image](https://user-images.githubusercontent.com/63410167/209282622-4b6cd812-34c0-4ac7-9a0f-ea538af7c660.png)
![image](https://user-images.githubusercontent.com/63410167/209282665-eb927e26-1965-4199-b79b-eba76476bca1.png)
Only the two things

### Additional information

Forgive my Chinglish

**Comment by bmuenzenmeyer** [comment] 2023-01-13 19:21
this looks like a duplicate of https://github.com/vitejs/vite/issues/6121 which indicates it is a `yarn` limitation: https://github.com/yarnpkg/yarn/issues/6851

as a workaround, try `npm create vite`

**Closed by bmuenzenmeyer** 2023-01-13 19:21 UTC
