### ISSUE TITLE
Npm not installed 

### ISSUE THREAD

**Issue by harnystiles** [nodejs/help#2757] opened 2020-06-05 09:32 UTC
I installed node.js from nodejs.org, installed it properly....afterwards I ran codes on gitbash like node -v ,got a version output...,but when I ran npm -v, I got bunch of errors....., pls how do I solve this.
A picture of the error I got https://photos.app.goo.gl/CHiWHVA2vWiWt19o9

**Comment by Hakerh400** [comment] 2020-06-05 09:53
Does it work if you run `npm -v` from Command Prompt instead of Git Bash?

**Comment by harnystiles** [comment] 2020-06-06 07:16
No....same thing as  command prompt
Still the same error message

**Comment by naseemkhan7021** [comment] 2020-06-06 11:40
same problem in my pc window powershell.
A picture of the error I got ---> [https://photos.app.goo.gl/v49bJspqUsBQ26Nk7](url)

please help..........please

**Comment by PoojaDurgad** [comment] 2020-10-20 08:37
@harnystiles and @naseemkhan7021  - can you provide the content of package.json ?
@harnystiles - for me by looking at the error I guess npm is not configured properly may be you can delete the npm and npm cache folder manually and try using `npm install -g npm@latest` on command prompt which will install the latest stable version of npm. and give `npm -v` in prompt to check whether npm is installed or not

**Comment by naseemkhan7021** [comment] 2020-10-20 10:38
Thanks pooja for your raspectfulle reply .... But the problem is automatically solved when I upgraded my PC windows 7 to windows 10.

Thanks pooja 🙏

**Comment by PoojaDurgad** [comment] 2020-10-21 06:48
no longer an issue. closing!!

**Closed by PoojaDurgad** 2020-10-21 06:48 UTC
