### ISSUE TITLE
NPM5 generate package-lock from existing node_modules? (migrating from Yarn, using @types)

### ISSUE THREAD

**Issue by dwasyluk** [nodejs/help#672] opened 2017-06-15 19:27 UTC
We're migrating a project from using Yarn for deterministic dependency locking back to pure NPM now that lockfiles are supported in a more deterministic manner. Is there a way to generate package-lock.json from an existing node_modules? `npm install` which auto-gens the lockfile is pulling down new versions which the existing Yarn.lock file prevents, but I can't find any good material on how to migrate back to pure npm while maintaining the locked versions.

I was thinking using `npm shrinkwrap` would do it but I ran into https://github.com/npm/npm/issues/16812; installed canary and now `npmc shrinkwrap` generates a file without errors but none of the `@types` entries are present (listed under devDependencies in package.json). How can I generate a complete package-lock.json with all @types etc?

**Comment by gibfahn** [comment] 2017-06-15 19:46
I don't think that's possible currently. Seems like it'd have to be a feature request for [npm/npm](https://github.com/npm/npm)

**Comment by vkozubal** [comment] 2017-10-01 12:53
Have you tried to npm shrinkwrap and then just rename npm-shrinkwrap.json to package-lock.json?

**Comment by boazrymland** [comment] 2017-11-08 09:09
What @vkozubal worked for me. In fact, you don't really need to rename since npm-shrinkwrap.json share the same syntax as package-lock.json and will take precedence over it. 
Just do:

- Have  a working tree, with working node_nodules.
- Delete all lock files: package-lock.json and npm-shrinkwrap.json
- Run "npm shrinkwrap". This will create the shrinkwrap file.

Now you're done. To check it, simply move aside the node_modules tree. Then run npm install and it will use the newly created shrinkwrap file (produced in the last step above) to recreate the same node_modules tree.

**Comment by gireeshpunathil** [comment] 2018-03-12 13:23
closing as answered, please re-open if the proposed solution does not work for you, thanks!

**Closed by gireeshpunathil** 2018-03-12 13:23 UTC

**Comment by IgorDePaula** [comment] 2018-10-09 15:42
Its not working for me =/

**Comment by adyz** [comment] 2018-11-22 14:12
Renaming  `npm-shrinkwrap.json` to `package-lock.json` does not work in all cases!

**Comment by michau-krakow** [comment] 2018-12-05 10:51
Can you give examples, please?

**Comment by veksi** [comment] 2019-02-04 13:05
After doing some R&D I found out next:
1. There are no reliable tools for migrating from yarn to npm, or to be exact, create `package-lock.json` from `yarn.lock` file and keep consistency in module dependencies between those package managers. (There is some tool [synp](https://github.com/imsnif/synp), but never got it to work...)
2. All CRA projects should first be updated to CRA2 before even trying to switch to npm
  General steps:
  	1. Delete `lock` file and `node_modules` folder
    2. Bump `react-scripts` version to newest `2.1.3``
    3. Remove `eslint` from dependencies (`react-scripts` has its own `eslint` dependency `v. 5.6.0`)
    4. `npm i``

**POSSIBLE MIGRATION HELPER TOOL**

Possible tool for easier migration from yarn to npm may be [syncyarnlock](https://github.com/vasilevich/sync-yarnlock-into-packagejson#readme) which:
> Syncs yarn.lock versions into an exsisting package.json file, removing dynamic numbers such as with ^, keeping static versions intact.

General steps for migration using this tool would be:
1. Install tool using `npm install -g syncyarnlock`
2. Position inside project root and: `syncyarnlock`
3. Since most of the issues are caused by root level dependencies (since they trigger changes/installing new child dependencies) use this command to keep the list of all local root (level 0) dependencies (dependencies inside `node_modules`): `npm list --depth=0 > filename.txt`
4. Remove all lock files (`yarn.lock` in this case) and `node_modules` folder
5. Install new dependencies using: `npm i``

At this moment list of all local level 0 dependencies comes in hand if application start doesn't work since there might be mismatch between dependencies previously listed in `yarn.lock` and ones that are currently installed. 
Each issue/error generated by dependency changes need to be solved separately using google (yes I said it) and saved dependency list or/and old `yarn.lock` file.

Migration for smaller projects can be done without `syncyarnlock` with just keeping and eye on version which are being installed. -> brute force approach


Known issues with versions:

`NEXT.JS` projects which use version `7+` (`7.0.2` in my case) doesn't work with `webpack 4.25+`. To fix this either delete `webpack` from dependencies if you don't use it aside from `next.js` tasks (beacause `next.js`itself has webpack as dependency) or use verion `4.24.0` as it is the latest one working.

Using this steps I migrated few "smaller" projects to npm in reasonamble time but I would like to put this migration decision to vote since it's not straightforward task and might cause issues (take much more time) for bigger and complicated projects to be transfered.

**Comment by alvaropaco** [comment] 2019-04-04 22:07
@adyz is right! The `npm-shrinkwrap.json` miss integrity, for example.

**Comment by Bassem95** [comment] 2020-12-30 11:32
them same problem in 2020

**Comment by vkurlyan** [comment] 2021-05-05 14:39
The same problem in 2021. Could somebody reopen this ticket?

**Comment by Piturnah** [comment] 2022-01-11 23:21
Same problem in 2022
