### ISSUE TITLE
HTTP response is not being sent (hangs forever)

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#2609] opened 2020-04-16 22:21 UTC
I am trying to find an answer to this problem:

https://stackoverflow.com/questions/61261016/stream-is-not-ending-response-is-not-being-sent

anyone know why the HTTP response is not ending / finishing?

**Comment by gireeshpunathil** [comment] 2022-02-09 03:13
looks like the issue is resolved in SOF, by using the right piping entities in the right order. closing the issue.

**Closed by gireeshpunathil** 2022-02-09 03:13 UTC
