### ISSUE TITLE
How to Stream Client Audio to Node.js Backend using Node Streams

### ISSUE THREAD

**Issue by andrewdingcanada8** [nodejs/help#3367] opened 2021-05-12 08:55 UTC
* **Node.js Version**: v14.15.0
* **OS**: MacOS
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**: stream, socket.io-stream

I am currently trying to stream some microphone audio to our server backend with Node Streams using the socket.io-stream package. Here is what our code looks like currently:

```js
onData: function (blob) {
    // pipe the audio blob to the read stream
    ss.createBlobReadStream(blob).pipe(audioStream, { end: false });
}
```
However we've been running into the maxListenersExceeded error:

MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 listeners added...
My theory is that I am creating too many read streams and piping them into the same write stream without destroying them when they are finished.

But I've tried the following fix to no avail:
```js
onData: function (blob) {
    const blobStream = ss.createBlobReadStream(blob);
    blobStream.on('end', () => {
        blobStream.destroy();
        audioStream.removeAllListeners();
    });
    blobStream.pipe(audioStream, { end: false });
}
```

**Comment by gireeshpunathil** [comment] 2021-10-04 07:07
@andrewdingcanada8 - is this outstanding? a smaller recreate would be ideal to debug this. Otherwise,  I can only speculate. The root cause seem to be that every request is triggering an event registration, and the key is to:
 - locate where that is happening
 - figure out how to change it to one time registration
 - adjust the code to meet the correct data flow

**Comment by gireeshpunathil** [comment] 2021-11-29 11:00
closing as answered, pls reopen if there is anything outstanding.

**Closed by gireeshpunathil** 2021-11-29 11:00 UTC
