### ISSUE TITLE
clarification on replace functionality broken in 4 and 4.1

### ISSUE THREAD

**Issue by sivam93** [nodejs/help#2072] opened 2019-07-24 05:34 UTC
hi ,
Can you help me out with the same problem.
Console.log prints single slach(\) in REPL for the below code

var user="DOMAIN\\USERNAME"

console output:DOMAIN\\USERNAME.

I am Trying to the user to connect to mssqlserver data base using mssql package.

After assigning the user, and when tried to print the config getting the below output
Code:
var config = {
server: 'DEV',
user: 'DOMAIN\\\\USERNAME',
password: 'XXXX',
database: 'TEMP'
}

NODE REPL OUTPUT:
{ server: 'DEV',
user: 'DOMAIN\\\\USERNAME',
password: 'XXX',
database: 'TEMP' }

Seems to be the same issue but because of this not able to connect to the db, getting error: ConnectionError: Login failed for user

**Comment by sivam93** [comment] 2019-07-24 06:39
Tried with 'DOMAIN\\USERNAME' .
The REPL Output goes like

{ server: 'DEV',
user: 'DOMAIN\\USERNAME',
password: 'XXX',
database: 'TEMP' }

But assigning the user to a variable ad printing the variable alone gives the output like below
var value = 'DOMAIN\\USERNAME';

Output : 'DOMAIN\USERNAME',

**Comment by Hakerh400** [comment] 2019-07-24 09:23
Duplicate of https://github.com/nodejs/node/issues/25812

When called with a string, `console.log` prints the literal string, character by character, so variable `user` actually contains exactly one slash (in the source code it must be of course escaped with another extra slash) and thus only one slash is printed. That is expected.

When called with an object, `console.log` calls `util.inspect` internally and `util.inspect` formats all strings so that they represent valid JavaScript strings that can be copy-pasted into the source code. In other words, it surrounds strings with `'` characters and escapes all characters that need to be escaped in order to represent valid JavaScript source string.

These two different outputs actually represent the same string. Simpler example:

```js
console.log('a\\b');
console.log(['a\\b']);
```

Output:

```
a\b
[ 'a\\b' ]
```

Explanation: the first line of the source code calls `console.log` by passing string `a\b` (backslash is escaped using another backslash so there are two backslashes, but the length of the string is only 3 characters). The first line of the output is `a\b`, which is literal representation of the beforementioned string. The second line of the source code calls `console.log` by passing an array (arrays are objects), so `console.log` calls `util.inspect`, which then formats the array and all its contant, so the representation of the string `a\b` now becomes `'a\\b'`, but it is the same string.

> Seems to be the same issue but because of this not able to connect to the db, getting error: 
 onnectionError: Login failed for user

There is an error somewhere else in your script.

**Comment by sivam93** [comment] 2019-07-25 10:43
thanks for the explanation on console.log.
But the problem lies around the config object we are setting and it taking the double slash(\\\\).
the module mssql replies back with the  below error:

{ ConnectionError: Login failed for user 'DOMAIN\\\\USERNAME'.
  code: 'ELOGIN',
  originalError:
   { ConnectionError: Login failed for user 'DOMAIN\\\\USERNAME'.
            message: 'Login failed for user \\'DOMAIN\\\\USERNAME\\'.',
     code: 'ELOGIN' },
  name: 'ConnectionError' }
{ ConnectionError: Connection is closed.
 
If u see the same log prints two different user name, with two different slashes.
so there is a confusion because the same username password works well in python

**Comment by PoojaDurgad** [comment] 2020-09-21 05:24
@sivam93 , is this issue resolved?

**Comment by gireeshpunathil** [comment] 2020-10-07 10:21
inactive, closing

**Closed by gireeshpunathil** 2020-10-07 10:21 UTC
