### ISSUE TITLE
writable.write(chunk) return false?

### ISSUE THREAD

**Issue by wisecolt** [nodejs/help#12] opened 2015-10-09 13:44 UTC
I want to upload (stream) control the writing process. But the writing process always returns false. Large files upload process stops. The output of the code is as follows;

> Node app.js
> False
> False
> False
> False

What am I doing wrong?

My code;

app.js

var http = require('http');
var fs = require('fs');

http.createServer(function(req, res){
  var readable = fs.createReadStream('read.mkv');
  var writable  = fs.createWriteStream('write.mkv');

  readable.on('data', function(chunk){

      var buffer = writable.write(chunk);

      if(!buffer){ // ----> Always false! Why????

        readable.pause();
      }
      console.log(buffer);
  });

  writable.on('drain', function(){

    readable.resume();
  });
}).listen(8090);

**Comment by yosuke-furukawa** [comment] 2015-10-11 19:14
@wisecolt I cannot reproduce your problem. how big is your 'read.mkv' ?

**Comment by lordKnighton** [comment] 2016-03-22 20:01
closing for now, feel free to reopen.

**Closed by lordKnighton** 2016-03-22 20:01 UTC
