### ISSUE TITLE
Doesn't get any responce from https.get on specific https website

### ISSUE THREAD

**Issue by AlexBGD** [nodejs/help#78] opened 2016-01-17 12:12 UTC
```javascript
var https=require('https');
https.get({ host:'www.juvalis.de', path: '/' }, function(res) {
    res.on('data', function(d) {
        console.log('chunk');
    });

    res.on('end', function() {
        console.log('end');
    });
}).on('error', function(e) {
    console.error(e);
}).on('close',function(){
    console.log('close')
});
```
 no errors,no response only close

**Comment by kelthenoble** [comment] 2016-01-21 20:26
Hey, are you having any luck with this yet?

**Comment by AlexBGD** [comment] 2016-01-21 20:34
still have a problem, with curl works fine

**Comment by kelthenoble** [comment] 2016-01-21 21:05
Are you running V-  0.12, 0.10 or newer?

**Comment by AlexBGD** [comment] 2016-01-21 21:14
v5.4.0

**Comment by kelthenoble** [comment] 2016-01-21 21:18
var https = require('https');

https.get('https://www.juvalis.de/', function(res) {
    console.log("statusCode: ", res.statusCode);
    console.log("headers: ", res.headers);

    res.on('data', function(d) {
        process.stdout.write(d);
    });

}).on('error', function(e) {
    console.error(e);
});

I'm doing it with version .12 of node & it's giving me the same.

**Comment by AlexBGD** [comment] 2016-01-21 21:19
I try also with v0.10.25 and don't work. Very strange

**Comment by kelthenoble** [comment] 2016-01-21 21:22
Are you trying to create a server with this, is this code suppose to be attached to some other code? What exactly are you trying to do? Besides get a response?

**Comment by AlexBGD** [comment] 2016-01-21 21:25
It's scraping app.There are more than 20 shops and all works fine except that one.

**Comment by kelthenoble** [comment] 2016-01-21 21:36
Bummer, well let's change that & get you back up & running.

**Comment by AlexBGD** [comment] 2016-01-21 21:45
oh yeah

**Comment by kelthenoble** [comment] 2016-01-21 21:48
Okay so I'm getting a response with this, it may not be what you wanted, but we can inch closer to the end goal with it. 

const https = require('https');

https.get('https://juvalis.de/', (res) => {
  console.log('statusCode: ', res.statusCode);
console.log('headers: ', res.headers);

res.on('data', (d) => {
  process.stdout.write(d);
});

}).on('error', (e) => {
  console.error(e);
});

**Comment by kelthenoble** [comment] 2016-01-21 23:33
Are you having any luck on your side?

**Comment by AlexBGD** [comment] 2016-01-22 08:29
Still not luck

**Comment by SomeoneWeird** [comment] 2016-01-22 08:33
Are you sitting behind a proxy?

**Comment by AlexBGD** [comment] 2016-01-22 09:51
No

**Comment by AlexBGD** [comment] 2016-01-22 09:52
I am not blocked for shure

**Comment by kelthenoble** [comment] 2016-01-22 22:10
So @AlexBGD from the response i got earlier in that photo, what kind of response are you respecting, how should this code respond?

**Comment by AlexBGD** [comment] 2016-01-23 09:48
So when I remove www from url I get error event(like on your photo) but still don't get any responce, only error event.

**Comment by AlexBGD** [comment] 2016-01-23 12:06
with curl all works fine

**Comment by kelthenoble** [comment] 2016-01-25 03:24
Because your not assigning it a server & specifying a port for it to run on, your not gonna be able to see this in a browser. But we can give it a createServer & port & run it in a browser.

**Comment by AlexBGD** [comment] 2016-01-25 08:57
I don't need a server, it's cli app. I just want to know why I don't get any respoce and how to handle that in the future.

**Comment by kelthenoble** [comment] 2016-01-25 20:04
check out these two photos. 
![screen shot 2016-01-25 at 12 03 46 pm](https://cloud.githubusercontent.com/assets/1773260/12562770/ba8c7010-c35b-11e5-9bc4-5c0c88345bcb.png)

and 

![screen shot 2016-01-25 at 12 04 15 pm](https://cloud.githubusercontent.com/assets/1773260/12562775/c1385b7c-c35b-11e5-96f6-52024310e196.png)

**Comment by kelthenoble** [comment] 2016-01-25 20:15
I would close this now, but i want one of my colleagues to look this over, to make sure i didn't miss anything.

**Comment by bnoordhuis** [comment] 2016-01-25 20:46
`node -e 'require("https").get("https://www.juvalis.de/", res => res.pipe(process.stdout));'` works fine for me with node master:
```
$ node -v
v6.0.0-pre
```
Can you confirm?

**Comment by TheAlphaNerd** [comment] 2016-01-25 20:50
I can confirm that work on master but not v4 or v5

**Comment by kelthenoble** [comment] 2016-01-25 21:02
:+1: Thanks guys for helping out. @TheAlphaNerd & @bnoordhuis 
> Yeah i have -v 4.2.4
so it's not working for me. I'll try -V 6 and see if it works out.

**Comment by bnoordhuis** [comment] 2016-01-25 21:07
It would be good to figure out what commit fixes it (probably not ALPN support, that exists in v5) and back-port it.  I don't have time right now but a simple `git bisect` should do it.

**Comment by TheAlphaNerd** [comment] 2016-01-25 21:09
I'll give a bisect a run this afternoon. I really hope it isn't a semver major fix

**Comment by kelthenoble** [comment] 2016-01-25 21:46
Hey what's the result of this running successful, since it works on `-v 6` and master, I'm on `v4` so i can't tell. 
can you someone give me a screen shot or typed result of it. Then I'll start bisecting.

**Comment by TheAlphaNerd** [comment] 2016-01-25 22:00
@kelthenoble the result would be the entire html document. If you see lots of lines in your terminal it is working, if not :(

**Comment by kelthenoble** [comment] 2016-01-25 22:04
I think i got ya. Ok this is my first time `git bisecting`, So i'll start, & will let you guys know how it goes.

**Comment by TheAlphaNerd** [comment] 2016-01-25 22:39
@kelthenoble let me know if you want to pair on this. Feel free to ping me in #node-dev

**Comment by kelthenoble** [comment] 2016-01-25 22:41
yeah, that sounds great, I'm reinstalling git short cuts & ohmyzsh, i factory restarted my mac

**Comment by kelthenoble** [comment] 2016-01-27 18:37
@AlexBGD Thanks for your patience as we got to the root of the problem. So in conclusion, there has been issues like this, and the fix was pushed master. But to my understanding, some of the support for other versions will drop in the following weeks. But there is a temp solution: https://nodejs.org/download/nightly/. If you follow some of the references & links, you can look further into it. But for now, my advice is just to wait for a few weeks. 

![screen shot 2016-01-27 at 10 38 04 am](https://cloud.githubusercontent.com/assets/1773260/12624066/e3ea63f4-c4e1-11e5-8737-b583c9d87650.png)

**Closed by kelthenoble** 2016-01-27 18:37 UTC
Labels: help wanted

**Comment by AlexBGD** [comment] 2016-01-27 18:50
Thanks man

**Comment by kelthenoble** [comment] 2016-01-27 18:55
You're very welcome.
