### ISSUE TITLE
npm pachages install fail

### ISSUE THREAD

**Issue by nvasilev1** [nodejs/help#738] opened 2017-07-17 15:09 UTC
* **Node.js Version**:6.11.1
* **OS**:windows 7 64bit
* **Scope (install, code, runtime, meta, other?)**: install

Hello,
I am trying to create a new angular project. It was already installed, but when creating it starts to install some packages and fails. After that the command prompt cannot "recognize" a simple ng command and states 

```
"'ng' is not recognized as an internal or external command,
operable program or batch file."
```

Here is the error:

```
Installing packages for tooling via npm.
'npm' is not recognized as an internal or external command,
operable program or batch file.

Package install failed, see above.
D:\temp\NV\node-v6.11.1-win-x64\node_modules\@angular\cli\tasks\npm-install.js:2
5
                    throw new Error(message);
                    ^

Error: Package install failed, see above.
    at child_process_1.exec (D:\temp\NV\node-v6.11.1-win-x64\node_modules\@angul
ar\cli\tasks\npm-install.js:25:27)
    at ChildProcess.exithandler (child_process.js:211:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:891:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

Any help is highly appreciated.

**Comment by vsemozhetbyt** [comment] 2017-07-17 17:04
It seems this should be posted in https://github.com/npm/npm first.

**Comment by gibfahn** [comment] 2017-07-18 05:09
Do you have node installed?

If you run `where node` and `where npm` in CMD, what does it output?

**Comment by gibfahn** [comment] 2017-07-18 05:11
I'd guess you'd get it in `D:\temp\NV\node-v6.11.1-win-x64\bin\node.exe`.

Angular is trying to run `npm`, but it's not in the path so is failing.

**Comment by gibfahn** [comment] 2017-07-18 05:12
Is this a duplicate of https://github.com/nodejs/help/issues/737 ?

**Comment by nvasilev1** [comment] 2017-07-18 07:44
@vsemozhetbyt Sorry will post it there as well - I am kind of new here :(

@gibfahn 
Regarding the 1st one - Yes I have them installed, but I should navigate to the folder in CMD and then they are showing, here is the code:
D:\temp\NV\node-v6.11.1-win-x64>where node
D:\temp\NV\node-v6.11.1-win-x64\node.exe

D:\temp\NV\node-v6.11.1-win-x64>where npm
D:\temp\NV\node-v6.11.1-win-x64\npm
D:\temp\NV\node-v6.11.1-win-x64\npm.cmd

Regarding  the second one - it is not in the /bin folder, but in the main one. I think npm is in the same one as well. However there is a npm folder in node_modules\npm - can this be connected to the issue?

Regarding the 3rd one - It is kind of different than #737, as there I had a problem with the binary installment and once I navigated to the folder it worked.

**Comment by gibfahn** [comment] 2017-07-18 08:22
>Regarding the second one - it is not in the /bin folder, but in the main one. I think npm is in the same one as well. However there is a npm folder in node_modules\npm - can this be connected to the issue?

Sorry, I was thinking of non-windows! Having them in the main folder is normal on windows.

---

So `where npm` is working, does `npm --version` work? If so then that my first guess would be an issue with Angular.

When you `npm install -g ng` it should put a binary in your global path, so `where ng` should find an `ng` binary. I suggest uninstalling and reinstalling angular (`npm uninstall -g ng`, `npm i -g ng`) and seeing if that helps.

**Comment by nvasilev1** [comment] 2017-07-18 08:53
npm --version worked (showing 3.10.10) and uninstalling and installing it again, and unfortunately the issue appeared again. If you are out of ideas - thanks a lot for your help.

**Comment by lordKnighton** [comment] 2017-07-18 16:28
your trying to use the `@angular cli` right?  Okay from the signature of your error message, It telling me that it doesn't recognize the way you installed the `Angular CLI` 

----------------
Type:  ng -v 

![screen shot 2017-07-18 at 9 24 37 am](https://user-images.githubusercontent.com/1773260/28328324-0f2aa9b4-6b9b-11e7-914f-c9f196395bcb.png)

For reference-- Check out this video, the first 3 mins should have you ready to build @angular/cli apps

**Comment by nvasilev1** [comment] 2017-07-19 08:13
this is what i see when entering ng -v : 

D:\temp\NV\node-v6.11.1-win-x64>ng -v
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / ? \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.2.1
node: 6.11.1
os: win32 x64

**Closed** 2017-07-19 12:57 UTC
