### ISSUE TITLE
node:test with typescript, code coverage and typing for mock

### ISSUE THREAD

**Issue by MorningLightMountain713** [nodejs/help#4325] opened 2024-01-12 14:54 UTC
### Details

Just FYI, testing works fine when using the following:

```
node --import tsx  --test test/myfile.ts
```

***Problem 1***

When trying to use code coverage with `node --import tsx --experimental-test-coverage --test test/myfile.ts`

I get the following warning (and no code coverage):

```
ℹ Warning: Could not report code coverage. TypeError: Cannot read properties of undefined (reading 'line')
```

What can I do to get code coverage?

***Problem 2***

Whenever I spy in the ts file, intellisense gives warnings about type missing for mock. Eg:

```typescript
    t.mock.method(serverFromOtherTsFile, "myMockedMethod");

    assert.strictEqual(serverFromOtherTsFile.myMockedMethod.mock.calls.length, 0);
    await serverFromOtherTsFile.myMockedMethod();
    assert.strictEqual(serverFromOtherTsFile.myMockedMethod.mock.calls.length, 1);
```

The `mock` property doesn't exist on type myMockedMethod. How can I type this? For clarity, the tests still run, it's just in VSCode I get the warnings as mock doesn't exist on myMockedMethod.

Thanks for your help 

### Node.js version

v20.10.0

### Operating system

macOS

### Scope

code / runtime

### Module and version

Not applicable.

**Comment by MorningLightMountain713** [comment] 2024-01-17 12:03
I have ended up doing the following:

```typescript
assert.strictEqual((serverFromOtherTsFile.myMockedMethod as any).mock.calls.length, 0);
```

I don't like it, but it lets me run `tsc` without throwing errors

**Comment by NikitaIT** [comment] 2024-04-05 01:10
```
ℹ Warning: Could not report code coverage. TypeError: Cannot read properties of undefined (reading 'line')
```


test.ts
```ts
import { a } from "./a.ts";
```
a.ts
```ts
// no imports <-- TypeError: Cannot read properties of undefined (reading 'line')
export function a(): string {
  return "a";
}
```

**Comment by liza-unito** [comment] 2024-05-14 20:22
+1 also having this issue. (... as any) does work but... it's not the prettiest solution

**Comment by RedYetiDev** [comment] 2024-05-15 11:19
Fixed by https://github.com/nodejs/node/pull/53000

**Comment by RedYetiDev** [comment] 2024-05-15 11:21
Keep in mind the coverage won't exactly be useful in the transpiled code, see https://github.com/nodejs/node/issues/52775#issuecomment-2111926554

**Comment by khaosdoctor** [comment] 2024-05-21 15:45
Btw, if someone is having the same thing, please first check if the transpiler (if you're using any) provides an inline source map generation for the code, the underlying problem in that case is that the generated transpiled code does not map to anything in the original code, hence there's no way to tell which function is which and the code coverage won't work properly.

Weird thing though, if the code is simple enough, the coverage works, even with transpilers

**Closed** 2024-05-21 19:27 UTC
Labels: workaround provided

**Comment by onlywei** [comment] 2024-06-25 02:04
Did anyone figure out a solution to Problem 2 in the original issue? How come this issue was closed without that problem being addressed?

**Comment by RedYetiDev** [comment] 2024-06-25 02:07
This issue was closed because the described issue involved an issue with Typescript code, which is not maintained by Node.js. If you can reproduce in purely JS, please open a new issue.

**Comment by onlywei** [comment] 2024-06-25 02:33
@RedYetiDev I see. I found a good solution, though. I'll post it below:

@liza-unito @MorningLightMountain713 this is the solution I used:

```typescript
import { beforeEach, describe, it, mock, Mock } from 'node:test';
import { object } from './object';

describe('solution', () => {
  let mockedMethod: Mock<typeof object.myMethod>;

  beforeEach(() => {
    mockedMethod = mock.method(object, 'myMethod');
  });

  it('should not make TypeScript complain', () => {
    assert.strictEqual(mockedMethod.mock.calls.length, 0);
  });
});
```

**Comment by khaosdoctor** [comment] 2024-06-25 08:35
This was resolved in https://github.com/nodejs/node/issues/52775 and implemented on https://github.com/nodejs/node/pull/53315

Turns out it was a code issue in the test runner that wasn't correctly checking for the lines

**Comment by MartenOlofsson** [comment] 2024-12-17 11:34
If anyone else were to end up here:

`const mockedMethod = t.mock.method(serverFromOtherTsFile, "myMockedMethod");
    assert.strictEqual(mockedMethod.mock.calls.length, 0);`
