### ISSUE TITLE
npm from 8.9.1 binary distribution doesnt work

### ISSUE THREAD

**Issue by sandrotosi** [nodejs/help#962] opened 2017-11-10 15:52 UTC
* **Node.js Version**: 8.9.1
* **OS**: debian jessie
* **Scope (install, code, runtime, meta, other?)**: install
* **Module (and version) (if relevant)**: n/a

Hello,
i downloaded the linux x86_64 binary release for 8.9.1 and installed in `/usr/local/nodejs_8.9.1/`.

when i run node from there it works fine:

```
/usr/local/nodejs_8.9.1/bin/node --version
v8.9.1
```

but if i try to run npm it fails with:

```
# /usr/local/nodejs_8.9.1/bin/npm --version

module.js:340
    throw err;
          ^
Error: Cannot find module '../lib/utils/unsupported.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at /usr/local/nodejs_8.9.1/bin/npm:19:21
    at Object.<anonymous> (/usr/local/nodejs_8.9.1/bin/npm:92:3)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```

i suspected this is because the shebang is set to `/usr/bin/env node` (which points to the system-installed node, instead of this one) but even change npm shebang to 8.9.1 node i got the same error:

```
# head -1 /usr/local/nodejs_8.9.1/bin/npm
#!/usr/local/nodejs_8.9.1/bin/node

# /usr/local/nodejs_8.9.1/bin/npm --version
module.js:538
    throw err;
    ^

Error: Cannot find module '../lib/utils/unsupported.js'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at /usr/local/nodejs_8.9.1/bin/npm:19:21
    at Object.<anonymous> (/usr/local/nodejs_8.9.1/bin/npm:92:3)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
```

what am i doing wrong? how can i fix it?

thanks!

**Comment by sandrotosi** [comment] 2017-11-13 17:53
fixed with https://stackoverflow.com/a/20549534 but this is an extremely unpleasant way to distribute binary releases - they should just work out of whatever directory the user installs them

**Comment by radoslavpetranov** [comment] 2017-11-17 18:43
Having the same issue after upgrading from node 6.11 to node 8.9.1 on a windows machine.

**Comment by clcoup** [comment] 2017-11-23 03:06
I am having this issue and don't know what i am doing wrong. Please see below Error: Cannot find module '../config/config.json'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/chaunceyleslie/Desktop/Desktop/BootCampCoding/Homework/sequelizedBurger/models/index.js:8:17)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/chaunceyleslie/Desktop/Desktop/BootCampCoding/Homework/sequelizedBurger/controllers/burgers_controller.js:3:10)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/chaunceyleslie/Desktop/Desktop/BootCampCoding/Homework/sequelizedBurger/server.js:29:1)

**Comment by josuevalrob** [comment] 2018-01-09 09:32
any solution for windows?

**Comment by gibfahn** [comment] 2018-01-09 11:18
This shouldn't be happening with v8.9.4.

@josuevalrob what does `where npm` print on your machine? How did you install node?

Usually a complete uninstall and reinstall fixes the issue.

Alternatively you could try something like `nvs`, and see if that fixes your problem.

**Comment by SamuraiJack** [comment] 2018-01-15 10:59
Confirmed for 8.9.4:

```
nickolay@outpost:~$ which node
/home/nickolay/Programs/node-v8.9.4-linux-x64/bin/node
nickolay@outpost:~$ which npm
/home/nickolay/Programs/node-v8.9.4-linux-x64/bin/npm
nickolay@outpost:~$ node --version
v8.9.4
nickolay@outpost:~$ npm --version
module.js:540
    throw err;
    ^

Error: Cannot find module '../lib/utils/unsupported.js'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at /home/nickolay/Programs/node-v8.9.4-linux-x64/bin/npm:19:21
    at Object.<anonymous> (/home/nickolay/Programs/node-v8.9.4-linux-x64/bin/npm:92:3)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
nickolay@outpost:~$ 
```

**Comment by gibfahn** [comment] 2018-01-16 08:44
@SamuraiJack can you give more info? I can't reproduce on an Ubuntu 14.04 box:

```console
$ curl -sL https://nodejs.org/download/release/v8.9.4/node-v8.9.4-linux-x64.tar.gz | tar -xzf -
$ export PATH=$PWD/node-v8.9.4-linux-x64/bin:$PATH
$ node -v
v8.9.4
$ npm -v
5.6.0
```

**Comment by SamuraiJack** [comment] 2018-01-16 18:21
@gibfahn Resolved by installation from sources and removing the npm from /usr/.../node_modules/npm. Was an artefact of installation over the old version.

**Comment by HiPaMon** [comment] 2018-01-24 09:42
@gibfahn 怎么解决的

**Comment by gibfahn** [comment] 2018-01-24 10:22
>@gibfahn 怎么解决的

你的错误是什么？这个问题一般是上一个安装没卸好的原因，留下了些npm的文件。把`/usr/local/lib/node_modules`删掉然后重新安装可能会解决问题。

**Comment by Noor0** [comment] 2018-01-28 20:25
i'm on a windows 8.1 machine and updated my node installation to 8.9.4 and now i'm getting this error
`module.js:540
    throw err;
    ^

Error: Cannot find module './C:/Users/noor/AppData/Local/Microsoft/TypeScript/2.
6/node_modules/@types/bluebird'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
....`

**Comment by gireeshpunathil** [comment] 2018-03-10 10:50
what is the status of this? Is it resolved, or outstanding?

**Comment by gibfahn** [comment] 2018-03-10 18:25
>what is the status of this? Is it resolved, or outstanding?

I think it can be closed as we haven't had any follow-up on the reports. If anyone has this issue with new versions of 8 then they would be better served opening a new issue.

**Closed by gibfahn** 2018-03-10 18:25 UTC

**Comment by SeyouElegance** [comment] 2018-03-28 13:50
On MAC V.10.12.6
npm -v
5.6.0
node -v
v8.9.4

Open your terminal : 

open /usr/local/lib/node_modules/

Delete "npm" folder 

back to Terminal : 

brew install node
To see if Node is installed, type node -v in Terminal.
To see if NPM is installed, type npm -v in Terminal.

should be working now !!!

**Comment by erperejildo** [comment] 2018-09-16 18:37
I tried deleting all of these folder but nothing works:
![node](https://user-images.githubusercontent.com/5629919/45599683-ee378500-b9e7-11e8-8bb4-05992ccdf5ac.JPG)
