### ISSUE TITLE
npm ERR! Unexpected end of JSON input while parsing near '...1","webpack-stream":"'

### ISSUE THREAD

**Issue by acharotariya** [nodejs/help#1926] opened 2019-05-26 08:26 UTC
* **Node.js Version**: 10.15.3 , npm version:6.4.1
* **OS**: windows 10
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:

when i'm trying to install node modules with npm install command i got this error.please help to solve issue.

**Comment by ZYSzys** [comment] 2019-05-26 08:30
It's usually caused by your `package.json` format error. 

Note that there shouldn't be extra comma in your `package.json` file.

**Comment by ZYSzys** [comment] 2019-06-05 01:17
Closing due to no feedback.

Feel free to reopen if there is any question.

**Closed by ZYSzys** 2019-06-05 01:17 UTC
