### ISSUE TITLE
Readline problems

### ISSUE THREAD

**Issue by benleib** [nodejs/help#1664] opened 2018-12-08 19:50 UTC
When ever I use readline my computer double types every key I hit. After the module is acknowledged it starts to do this. Any suggestions on what to do.

```
const readline = require('readline');
const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout,
  prompt: 'OHAI> '
});

rrll..pprroommpptt(());;
```

[Edited by @Trott for code formatting and to eliminate superfluous GitHawk message.]

**Comment by Trott** [comment] 2018-12-08 20:37
I imagine you're doing this in the REPL. You're getting one character printed by the REPL and another character printed by `rl` (since you are directing the output to `process.stdout`). So this would be expected behavior.

**Comment by Trott** [comment] 2018-12-08 20:37
I'm going to close this, but re-open (or if GitHub won't let you do that, leave a comment) if there's still an issue.

**Closed by Trott** 2018-12-08 20:37 UTC
