### ISSUE TITLE
node --prof: high load of Shared libraries /usr/bin/node

### ISSUE THREAD

**Issue by denyaalt** [nodejs/help#4422] opened 2024-06-18 07:26 UTC
### Node.js Version
v20.12.0

### Operating System
Debian 6.1.69-1 (2023-12-30) x86_64 GNU/Linux

### Description

Hi, I am testing node with network load and I get the following profiling results:
```
 [Shared libraries]:
   ticks  total  nonlib   name
  285518   63.3%          /usr/bin/node
  21547    4.8%          /usr/lib/x86_64-linux-gnu/libc.so.6
    770    0.2%          [vdso]
    231    0.1%          /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.30
    114    0.0%          /usr/lib/x86_64-linux-gnu/libm.so.6

 [Summary]:
   ticks  total  nonlib   name
  44333    9.8%   31.0%  JavaScript
  43387    9.6%   30.3%  C++
  19641    4.4%   13.7%  GC
  308180   68.3%          Shared libraries
  55499   12.3%          Unaccounted
```
There is a high CPU load on the node itself, but what does this mean? 
What is the bottleneck?

P.S. My node script receives 10k TCP packets from different clients and sends 20k TCP packets to other clients.

**Comment by denyaalt** [comment] 2024-06-20 15:13
How does the hardware configuration matter in answering my question?
If the hardware is more powerful, it can handle more traffic; if it is weaker, it can handle less.

My question is what does Shared libraries and /usr/bin/node mean in profiling report?

**Comment by RedYetiDev** [comment] 2024-07-20 01:37
@nodejs/performance (right?)

---

Also, your hardware/software can help determine whether or not the issue is actually coming from Node.js. There's a lot to learn about the system at hand.

**Comment by lemire** [comment] 2024-07-20 14:18
@denyaalt 



> There is a high CPU load on the node itself, but what does this mean? What is the bottleneck?

If you have a clearly identifiable bottleneck, then the complete report (which you are not providing) should tell you.

**Comment by denyaalt** [comment] 2024-07-21 09:13
My question is what does **Shared libraries** and **/usr/bin/node** mean in profiling report?

**Comment by RedYetiDev** [comment] 2024-07-21 11:59
> My question is what does **Shared libraries** and **/usr/bin/node** mean in profiling report?

What about the question you asked originally?:

> There is a high CPU load on the node itself, but what does this mean?
> What is the bottleneck?

Did you answer this question?

**Comment by denyaalt** [comment] 2024-07-21 13:21
Are you kidding? 
To answer the question, I first need to understand what **Shared libraries** and **/usr/bin/node** are in profiling.

If you don't know the answer, please don't comment.

**Comment by RedYetiDev** [comment] 2024-07-21 15:55
> Are you kidding? 
> *(...)*
> If you don't know the answer, please don't comment.

I'm sorry if my comment annoyed you, I was just trying to assess the situation. There is no need to get upset, everyone helping you is a volunteer, so I ask that you maintain a collaborative and respectful demeanor when communication.

---

Back to my question, if you still need help identifying a bottleneck, it would help if you gave more information.

As for what shared libraries are, they are libraries that are shared between multiple executables. For example, V8 is NOT a shared library, as it is bundled.

**Comment by denyaalt** [comment] 2024-07-21 17:05
Where can I read about shared libraries in detail?
Why is there no shared libraries name in the profiling?

What more detailed information do I need to provide?
The full profiling report only shows the names of my functions, they won't give you anything, there are no hints about a bottleneck.

**Comment by RedYetiDev** [comment] 2024-07-21 17:17
The internet has plenty of resources for learning more about shared libraries. If you'd like to suggest an improvement to the profiling report, feel free to open a separate issue.


> What more detailed information do I need to provide?

The entire report would be helpful, along with some reproduction code, so we can help find the bottleneck.

**Comment by denyaalt** [comment] 2024-07-21 17:25
Again, no specifics, "look for the answer somewhere on the Internet".
The code is not needed for repetition, and you will not repeat it, my question is specifically, what is **Shared libraries** and **/usr/bin/node** in the profiling report, that's all!

**Comment by RedYetiDev** [comment] 2024-07-21 18:28
> Again, no specifics, "look for the answer somewhere on the Internet".

Sorry, I didn't mean for that to come off as rude. To reiterate, I don't have the specific details of the profile report, but I'm sure the internet has tons of resources.

Additionally, the @nodejs/performance team may have more information, so let's see what they say.

**Comment by denyaalt** [comment] 2024-07-21 18:34
In the last 5 years I have seen the degradation of forums more and more, everyone is trying to increase the number of posts, but there is no benefit from the messages, it is a pain.

You commented 5 times and each post is of no use.
Please do not comment anymore...

**Comment by RedYetiDev** [comment] 2024-07-21 18:50
> You commented 5 times and each post is of no use.
> Please do not comment anymore...

I'm sorry you feel that way. While I don't know all the answers, I try my best to get all the information so that those who do will be able to provide help easier.

**Comment by RedYetiDev** [comment] 2024-07-21 20:45
> The code is not needed for repetition, and you will not repeat it, my question is specifically, what is Shared libraries and /usr/bin/node in the profiling report, that's all!

It seems to me like your asking a few different questions:

1. What are the different parts of the profiling report

The Node.js website has a detailed guide about profiling, available at https://nodejs.org/en/learn/getting-started/profiling

2. Why does Node.js use so much of my CPU?

It's hard to tell what part of your code is causing the CPU to be used up, and for that reproducible code would be helpful

3. What's the bottleneck in my code

Aside from what I said above, if you require assistance with specific code unrelated to the Node.js core, such as dependencies, alternative resources may help, such as StackOverflow


---

Is there anything else you need?

**Comment by benjamingr** [comment] 2024-07-21 20:51
His question is given the profile in https://github.com/nodejs/help/issues/4422#issue-2359139430 "what it means" that Node is spending 63% of time in /usr/bin/node under "shared libraries". Whether or not his results in terms of where the time is spent are good, what he should do in order to analyze those results and how to better figure out where his bottlenecks performance wise are.

The remediation would be to first - profile the full output of --prof rather than just the breakdown which would help identify parts in C++ that are slow. Ideally also run node with the inspector `--inspect` and use the V8 CPU profiling tools to identify bottlenecks in JS land.

The answer of the 63.3% the guess would be "node's own code in response to what the user is doing" but without the full report it would be hard to tell - which is what Daniel Lemire was trying to explain above.

I think OP is being argumentative and fruitlessly so ( @denyaalt please edit your non-constructive parts in your comments that don't help the discussion). I am leaning more towards closing this issue since discussion isn't happening constructively, but to be honest I can also understand OP's frustration at asking a pretty straightforward question and not getting an answer for a month (though again, this is open source, we're all volunteers, etc etc)

**Comment by denyaalt** [comment] 2024-07-21 20:51
Dude, get some work done and stop sending useless messages.

**Comment by benjamingr** [comment] 2024-07-21 20:52
@denyaalt since you may have not seen my message when you posted yours, I am putting my moderator hat on - giving you one final opportunity to edit your messages and have a constructive conversation rather than escalate this and not have a discussion at all.

**Comment by denyaalt** [comment] 2024-07-21 20:58
[RedYetiDev](https://github.com/RedYetiDev), dude, get some work done and stop sending useless messages.

V8 CPU profiling will show only JavaScript load, and this is only 9.8% of the profiling report.
In general, it is useless to discuss anything.

**I write again:**
The full profiling report only shows the names of my functions, they won't give you anything, there are no hints about a bottleneck.

What are Shared Libraries and /usr/bin/node in the profiling report?
If you don't know the answer, please don't comment!

**Closed** 2024-07-21 21:16 UTC
Labels: question, needs more info

**Comment by az-nextsec** [comment] 2024-12-03 05:48
Experiencing the same issue except my report is 99.7% in `shared libraries`. How can I unpack that to understand what node is doing?
