### ISSUE TITLE
npm instal && npm run dev  " laravel"

### ISSUE THREAD

**Issue by ghost** [nodejs/help#3543] opened 2021-09-21 00:09 UTC
* **Node.js Version**: 14
* **OS**: ubuntu
* **Scope (install, code, runtime, meta, other?)**:install
* **Module (and version) (if relevant)**:

I try it on win 7  and ubuntu  same error ):
Whe i run with laravel the command  npm isntall 
I get ( 58 packages are looking for funding 
                run 'npm fund for details
found 6 vulnerbilities (4 moelderate  2 high  )
    run  'npm audit fix ' to fix them , or'npm audit 'for details)
And when i run npm audit and it fix 
But when run the command npm run dev   after that i get the error 

![400208700135_442986](https://user-images.githubusercontent.com/91100536/134092481-7429af39-27bc-4b78-a0fa-5c6dfa9fa12f.jpg)

![400290600541_30587](https://user-images.githubusercontent.com/91100536/134092477-8d746130-8e1a-4ce1-a529-fc8786b8cb2e.jpg)

**Comment by bmuenzenmeyer** [comment] 2022-10-28 13:14
I am closing this issue for the following reasons:

- it relates to a userland project laravel
- npm audit results are [well-documented as creating false-positives](https://github.com/facebook/create-react-app/issues/11174), with which `audit fix` often [does more harm](https://github.com/facebook/create-react-app/issues/12415) depending on the exact make up of the project's dependency resolution.
- the issue is over a year old, and the original poster's account is deleted. I don't feel like the content of the issue carries enough general interest or movement toward action to help future users

**Closed by bmuenzenmeyer** 2022-10-28 13:14 UTC
Labels: install
