### ISSUE TITLE
FATAL ERROR: v8::ToLocalChecked Empty MaybeLocal.

### ISSUE THREAD

**Issue by ronssm** [nodejs/help#2515] opened 2020-03-06 02:36 UTC
Version: v10.15.0
Platform: Microsoft Windows Server 2016 64-bit
Couldnt get more logs because the process dies.
```
c:\windows\system32\inetsrv\w3wp.exe[7268]: src\node.cc:1453: Assertion `(env_->execution_async_id()) == (0)' failed.
 1: node::DecodeWrite
 2: node::CallbackScope::~CallbackScope
 3: node::CallbackScope::~CallbackScope
 4: node::MakeCallback
 5: node::Start
 6: uv_run
 7: node::FreeEnvironment
 8: node::FreeEnvironment
 9: node::Start
10: lh_node_usage_stats_bio
11: BaseThreadInitThunk
12: RtlUserThreadStart
worker 7268 died with code 3
Worker 3640 started
Worker 3640 is running on port 10001
FATAL ERROR: v8::ToLocalChecked Empty MaybeLocal.
 1: node_module_register
 2: v8::V8::ToLocalEmpty
 3: node::FatalException
 4: v8::internal::StackGuard::ArchiveSpacePerThread
 5: v8::internal::StackGuard::ArchiveSpacePerThread
 6: v8::internal::StackGuard::ArchiveSpacePerThread
 7: v8::internal::StackGuard::ArchiveSpacePerThread
 8: v8::internal::StackGuard::ArchiveSpacePerThread
 9: node::Start
10: v8::internal::AsmJsScanner::IsNumberStart
11: 000002FCB58043C1
worker 9056 died with code 3
c:\windows\system32\inetsrv\w3wp.exe[11684]: src\node.cc:1453: Assertion `(env_->execution_async_id()) == (0)' failed.
 1: node::DecodeWrite
 2: node::CallbackScope::~CallbackScope
 3: node::CallbackScope::~CallbackScope
 4: node::MakeCallback
 5: node::Start
 6: uv_run
 7: node::FreeEnvironment
 8: node::FreeEnvironment
 9: node::Start
10: lh_node_usage_stats_bio
11: BaseThreadInitThunk
12: RtlUserThreadStart
worker 11684 died with code 3
```

**Comment by mmarchini** [comment] 2020-03-06 19:40
Moving this issue to nodejs/help. If it proves to be an issue on Node.js instead of the dependencies, we can move back.

@ronssm are you able to reproduce this locally, or is the issue only happening on you staging/production servers? Have you upgraded Node.js recently (from v8 to v10, for example)?

**Comment by ronssm** [comment] 2020-03-06 19:48
@mmarchini unfortunately it only happens in production. 
I didnt upgrade node version, it is the same since it was installed.
After @bnoordhuis comment, we are investigating the tripwire module but nothing new so far.

**Comment by bnoordhuis** [comment] 2020-03-06 22:28
You can try attaching a debugger to the process(es).

**Closed** 2020-08-17 02:23 UTC

**Comment by bnoordhuis** [comment] 2020-08-17 09:41
FWIW, I looked at `deasync` recently and it does something pretty dangerous:

https://github.com/abbr/deasync/blob/103d84db0572d89c5ae3e958aa037654f044cb09/src/deasync.cc#L10

Calling `uv_run()` recursively (what deasync seems to be doing) is unsound because `uv_run()` is not re-entrant.
