### ISSUE TITLE
I am getting this issue when deploy the app on the heroku

### ISSUE THREAD

**Issue by ravirathoreds** [nodejs/help#2452] opened 2020-01-30 11:09 UTC
Hello,

I have attached the screenshot  below:
Please check 
![image](https://user-images.githubusercontent.com/55428204/73444693-1e828800-437f-11ea-9dbb-6f0b3109cc79.png)

Thank you.

**Comment by Hakerh400** [comment] 2020-01-30 12:30
Please share your code.

**Comment by ravirathoreds** [comment] 2020-01-30 12:39
Hello Hakerh400

I share you all code or only index.js file.
Please let me know.
Thank you

**Comment by ravirathoreds** [comment] 2020-01-30 12:39
Index.js file code:
// Required Module

const express = require('express');
const path = require('path');
const cookieParser = require('cookie-parser');
const session = require('express-session');
const fileUpload = require('express-fileupload');
const expressLayouts = require('express-ejs-layouts');
const cors = require('cors');
const url = require('url');
const bodyParser = require('body-parser');
const moment = require('moment');
const passport = require('passport');
const LocalStrategy = require('passport-local').Strategy;
const flash    = require('connect-flash');
const frontend = require('./src/routes/frontend');
const admin = require('./src/routes/admin');
global.app = express();

// Env File connection
const result = require('dotenv').config()

// view engine setup
app.use(express.static(__dirname + '/public'));
app.use(expressLayouts);
app.set('views', path.join(__dirname, 'src/views'));
app.set('view engine', 'ejs');
app.use(bodyParser.urlencoded({ extended: true }));
app.use(bodyParser.json())



app.use(express.json());
app.use(express.urlencoded({ extended: false }));
app.use(cookieParser());


/* This realted to Middleware */

const middlewares = [
    session({
        secret: 'P43Nv38QX61DB9gh2OaGMPT9b7hjOz0R',
        resave: true,
        saveUninitialized: true,
    }),
]

app.use(middlewares);

// Required module 

app.use(cors());
app.use(fileUpload());
app.use(cookieParser());
app.use(passport.initialize());
app.use(passport.session());
app.use(flash());


require('./src/controllers/admin/auth/passport')(passport); // pass passport for configuration


// Route Location

app.use('/', frontend);
app.use('/admin', admin);

// catch 404 and forward to error handler
app.use((req, res, next) => {
    res.status(404).render('admin/error/404', {
        layout: 'admin/layouts/error' , title: '404 Not Found'
    });
});


/* Server connection Detail with port */

if (process.env.NODE_ENV == 'development') {
    app.listen(process.env.PORT || 8000, function() {
        console.log(`Your port is ${process.env.PORT}`);
        console.log(`Your Envoirment is ${process.env.NODE_ENV}`);
    });
}

**Comment by Hakerh400** [comment] 2020-01-30 12:51
Can you post the content of `/app/src/models/index.js`

**Comment by ravirathoreds** [comment] 2020-01-30 12:57
Hello Haker400
I am using the Sequelize ORM..
Model index.js

'use strict';

const fs = require('fs');
const path = require('path');
const Sequelize = require('sequelize');
const basename = path.basename(__filename);
const env = process.env.NODE_ENV || 'development';
const config = require(__dirname + '/../../database/config.js')[env];
const db = {};

let sequelize;
if (config.use_env_variable) {
  sequelize = new Sequelize(process.env[config.use_env_variable], config);
} else {
  sequelize = new Sequelize(config.database, config.username, config.password, config);
}

fs
  .readdirSync(__dirname)
  .filter(file => {
    return (file.indexOf('.') !== 0) && (file !== basename) && (file.slice(-3) === '.js');
  })
  .forEach(file => {
    const model = sequelize['import'](path.join(__dirname, file));
    db[model.name] = model;
  });

Object.keys(db).forEach(modelName => {
  if (db[modelName].associate) {
    db[modelName].associate(db);
  }
});

db.sequelize = sequelize;
db.Sequelize = Sequelize;

module.exports = db;

**Comment by Hakerh400** [comment] 2020-01-30 13:05
You got the error because `config.use_env_variable` is defined, but `process.env[config.use_env_variable]` is undefined (there is no environment variable whose name is equal to the value of `config.use_env_variable`).

To solve that, you can either explicitly define `database`, `username` and `password` in your `config` (and remove `use_env_variable`), or you can define environment variable containing the database name, username and password for your database.

**Comment by ravirathoreds** [comment] 2020-01-30 13:16
Hello Hakerh400
Please check this screenshot:
When i console the config then get all the database detail.
![image](https://user-images.githubusercontent.com/55428204/73452657-4f1eed80-4390-11ea-9d1d-d9583f2a7b20.png)
![image](https://user-images.githubusercontent.com/55428204/73452817-b89efc00-4390-11ea-9575-b8ece2721ee4.png)

Please let me  know where i wrong.
This code is running successfully on the localhost server. but when i deploy the code on the jeroku then this error message show.

Thank you.

**Comment by Hakerh400** [comment] 2020-01-30 16:57
As I said, the problem is that your environment variables in the Heroku system are not properly set. You have

```js
const env = process.env.NODE_ENV || 'development';
```

which defines constant `env` as the value of `NODE_ENV` environment variable, or `'development'` if there is no such environemnt variable. Then from your config, you select the exported object assigned to the property with name equal to `env`.

You need to set all required environment variables in the Heroku system to make it work. If you are not sure what you are supposed to do, please provide the content of `config.js` (remove private data if you want) and provide the output of `console.log(process.env)` **both** from the Heroku app and your local app.

**Comment by gireeshpunathil** [comment] 2020-11-09 04:45
answered, closing. feel free to re-open if it is outstanding

**Closed by gireeshpunathil** 2020-11-09 04:45 UTC
