### ISSUE TITLE
from version nodejs 15 I get an error: Error: double-loading config .. .npmrc" as "user", previously loaded as "project"

### ISSUE THREAD

**Issue by kad-meedel** [nodejs/help#4193] opened 2023-06-22 19:56 UTC
### Details

When I want to use nodejs version 15 or higher I get the following error when trying to do a npm install xxx or even a npm config list.

The error I get is:

Error: double-loading config "/var/jenkins_data/workspace/test-scripts_test-nodejs-19/.npmrc" as "user", previously loaded as "project"
My 'default' .npmrc file is in the home dir of the user.
So I overwrite some settings within the project npmrc

### Node.js version

The problem shows up from nodejs 15 and higher

### Operating system

jenkins environment within linux server

### Scope

install packages

### Module and version

From nodejs 15 and higher

**Comment by Gloriouspete** [comment] 2023-06-22 20:06
You seem to be having a configuration conflict with the npmrc file,
A helpful solution would be to reset Npm with `npm config delete userconfig` and then install it back ,

we're also using node 18  currently so i'd advice you upgrade to node 18, sometimes old versions causes these issues,

if all these still doesn't work, use `npm cache clean --force` to clear unnecessary cache that may be causing conflict.

Good luck.

**Comment by kad-meedel** [comment] 2023-06-22 20:39
Gloriouspete, thanks for your quick reply.
I wil try you suggestions.

Thanks

**Comment by Gloriouspete** [comment] 2023-06-23 07:55
You're welcome, I'd be expecting feedback

**Comment by kad-meedel** [comment] 2023-06-26 06:28
The npm config delete userconfig won't work in our environment, because the 'default' npmrc is owned by root. 
I just want to overwrite some settings in my project, the way I always have done so far.
Until nodejs 14 this problem didn't exit!?

The option npm cache clean --force gives the same error as mentioned.
Error: double-loading config "/var/jenkins_data/workspace/tory-test-scripts_test-nodejs/.npmrc" as "user", previously loaded as "project"

Are there any other suggestions how to change my project config to prevent me from getting this error.

Is there any documentation describing this behavior change. I can't find it in the release notes of node 15.

**Comment by preveen-stack** [comment] 2023-06-27 08:51
@kad-meedel If your issue is solved, would you mind closing the issue

**Comment by Gloriouspete** [comment] 2023-06-27 13:28
Use `.npmrc.development` then you can load it like that in your env.

But the issue is caused because you have the same npmrc file in both user and project

**Closed** 2023-06-28 06:12 UTC
Labels: npm

**Comment by joemdjossou** [comment] 2023-08-22 16:33
I got this kind of error but instead of <<as "user", previously loaded as "project">>
It is as as _**\.cache\firebase\runtime\npmrc" as "global", previously loaded as "user"**_

I was trying to run the binary for the Firebase CLI in order to list my Firebase projects but when I enter any command under npm it flashes the error stated above.
@Gloriouspete can you help me figure it out?

**Comment by Gloriouspete** [comment] 2023-08-22 19:35
@joemdjossou have you tried `npm cache clean` , also what version of node are you using

**Comment by joemdjossou** [comment] 2023-08-22 19:43
I'm using the node veersion 18.17.1
I tried it but it has given me an error 
I then tried `npm cache clean --force` 

This was the answer
npm WARN using --force Recommended protections disabled

But still getting under binary for the Firebase CLI 
`.cache\firebase\runtime\npmrc" as "global", previously loaded as "user"`

**Comment by Gloriouspete** [comment] 2023-08-22 19:49
Try verifying your installation steps .

An easy way would be to uninstall firebase-cli 

Use `npm uninstall -g firebase-tools` to uninstall then install again correctly implementing the installation steps.
It should fix it

**Comment by welligtonporto** [comment] 2023-08-30 14:56
I updated the nodejs to the last version (18.17.1) and the firebase-tools `npm install -g firebase-tools` and fix it.

**Comment by joemdjossou** [comment] 2023-09-03 02:04
It is finally working guys
Thank y'all :)

**Comment by mhjb** [comment] 2023-09-08 00:31
removing the version of firebase cli that I installed with curl did the trick
