### ISSUE TITLE
Memory usage htop vs inspect devtools

### ISSUE THREAD

**Issue by lkiii** [nodejs/help#2393] opened 2020-01-06 10:57 UTC
* **Version**: 10.16.3
* **Platform**: Linux 4e54e997d94f 4.9.0-9-amd64 nodejs/node#1 SMP Debian 4.9.168-1+deb9u5 (2019-08-11) x86_64 x86_64 x86_64 GNU/Linux
 (Docker container with oracle linux)
* **Subsystem**:

I am trying to find the cause of memory leak and I am getting huge conflict of data between node inspect and htop.
![image](https://user-images.githubusercontent.com/1472871/71820681-899ab080-3098-11ea-897e-426db04a8684.png)
![image](https://user-images.githubusercontent.com/1472871/71813890-8b0dae00-3083-11ea-9e56-97b93cac9442.png)
![image](https://user-images.githubusercontent.com/1472871/71820744-be0e6c80-3098-11ea-8542-d43688486b5e.png)

How is this possible? Where is a mistake?

**Comment by lkiii** [comment] 2020-01-06 14:43
I did some additional research and the issue is not with the heap, but with rss
```
rss: " 1158.07 MB"
heapTotal: " 65.07 MB"
heapUsed: " 42.65 MB"
external: " 1.34 MB"

This seems to be a similar case to https://github.com/nodejs/help/issues/1942

**Comment by gireeshpunathil** [comment] 2020-01-07 08:19
@lkiii - as you already guessed, the native tools do not `see` the JS heap split. they see everything as `virtual memory` and rss

was that the only issue you wanted to bring up? or the current usage of memory (virtual or rss or both) is unexpected for your application?

**Comment by lkiii** [comment] 2020-01-07 09:11
The rss goes to 1Gb after several http requests. How can I get additional info on what is inside rss? Is there any way to debug it?

As I understood garbage collector should always clean rss, but it seems it is not happening. The application starts using more and more memory until becomes unresponsive.

**Comment by gireeshpunathil** [comment] 2020-01-07 09:19
@lkiii - producing a core dump (system dump) and checking through [llnode](https://github.com/nodejs/llnode) would be good idea.  after setting `ulimit -c unlimited` on the running terminal, issuing `gcore` on the node process ID from another terminal would produce a core dump.

**Comment by lkiii** [comment] 2020-01-07 11:45
@gireeshpunathil Thank you for the tips. 

I am not sure why I can not run gcore
```
bash-4.2# ps -a
  PID TTY          TIME CMD
    8 pts/0    00:00:00 npm
   19 pts/0    00:00:02 node
 1070 pts/1    00:00:00 ps
bash-4.2# gcore 19
ptrace: Operation not permitted.
You can't do that without a process to debug.
The program is not being run.
gcore: failed to create core.19
bash-4.2#
```

**Edit:**
I had to pass extra parameters to docker `--cap-add=SYS_PTRACE --security-opt seccomp=unconfined`

**Comment by lkiii** [comment] 2020-01-07 12:19
@gireeshpunathil Could you please provide a little bit more guidance? This is the first time I am working with a system dump and it is not that straight forward.

I have managed to dump multiple core files, but I had a lot of issues with llnode install on oraclelinux container, so I have extracted core files and I am trying to inspect them on my machine with llnode. The issue is that I can not get any data out of the files:
```
lk@DESKTOP-3UG613U:/mnt/c/Users/lukas/Documents/Projects/dump$ llnode `which node` -c 'core.6 - init'
(lldb) target create "/usr/bin/node" --core "core.6 - init"
Core file '/mnt/c/Users/lukas/Documents/Projects/dump/core.6 - init' (x86_64) was loaded.
(lldb) plugin load '/home/lk/.npm-global/lib/node_modules/llnode/llnode.so'
(lldb) settings set prompt '(llnode) '
(llnode) v8 nodeinfo
Stack dump:
0.      HandleCommand(command = "v8 nodeinfo")
lk@DESKTOP-3UG613U:/mnt/c/Users/lukas/Documents/Projects/dump$
```

```
lk@DESKTOP-3UG613U:/mnt/c/Users/lukas/Documents/Projects/dump$ llnode `which node` -c 'core.6'
(lldb) target create "/usr/bin/node" --core "core.6"
Core file '/mnt/c/Users/lukas/Documents/Projects/dump/core.6' (x86_64) was loaded.
(lldb) plugin load '/home/lk/.npm-global/lib/node_modules/llnode/llnode.so'
(lldb) settings set prompt '(llnode) '
(llnode) v8 nodeinfo
Stack dump:
0.      HandleCommand(command = "v8 nodeinfo")
lk@DESKTOP-3UG613U:/mnt/c/Users/lukas/Documents/Projects/dump$
```

**Comment by gireeshpunathil** [comment] 2020-01-07 12:55
@lkiii - stack does not help here. what we need is:
 - info about memory retainers in the native heap
 - dominator tree that contain the path from these retainers to JS objects that we can relate to the source.

I don't remember the commands on top of my head, but will revert when I get those. Meanwhile I am pinging @mmarchini as he has worked on this are extensively and may know the sequences

**Comment by mmarchini** [comment] 2020-01-07 21:44
llnode won't help. Based on the information provided [here](https://github.com/nodejs/help/issues/2393#issuecomment-571163384), the memory is likely leaking on native code (huge `rss` consumption but low heap consumption), and not JavaScript code.

> As I understood garbage collector should always clean rss, but it seems it is not happening.

The Garbage Collection will only clean memory allocated in the JavaScript heap. It also won't release pages right after a page is empty, since the allocator might need that page again soon. I'm not sure when/if a page in JavaScript heap is freed, but even empty pages be counted in `HeapTotal`.

---

There are a few system tools you could probably use to find out where memory is being allocated. But before going into those tools, it might be worth looking at your dependencies and app code:

1) Are there any dependencies loading a native (C++, etc.) module? Or maybe in your app code?
2) Same question for WebAssembly modules.
3) Are you running an official Node.js build (from nodejs.org) or a custom build?

**Comment by lkiii** [comment] 2020-01-07 22:29
> 
> There are a few system tools you could probably use to find out where memory is being allocated. But before going into those tools, it might be worth looking at your dependencies and app code:


> 1. Are there any dependencies loading a native (C++, etc.) module? Or maybe in your app code?
I think it might be oracledb module. Here is full production dependencies list, I am not sure which libraries use C++ modules:
```

  "dependencies": {
    "@marsaud/smb2": "^0.14.0",
    "axios": "^0.19.0",
    "exceljs": "^2.0.1",
    "form-data": "^2.5.1",
    "hummus": "^1.0.108",
    "ldapts": "^1.10.0",
    "memory-streams": "^0.1.3",
    "module-alias": "^2.2.2",
    "oracledb": "^4.0.0",
    "raven": "^2.6.4",
    "request-ip": "^2.1.3",
    "restify": "^8.4.0",
    "restify-cors-middleware": "^1.1.1",
    "restify-errors": "^7.0.0"
  }
```
Only oracle, restify, ldapts ,request-ip are being used on every request. So it must be oracledb issue.
> 2. Same question for WebAssembly modules.
None
> 3. Are you running an official Node.js build (from nodejs.org) or a custom build?
Yes I am running official rpm:
```

**Comment by mmarchini** [comment] 2020-01-07 23:19
If you can reproduce the issue locally, I recommend using [valgrind](https://valgrind.org/) to get more insights on what's going on. It might give you some useful output to share in the oracledb issue. Don't use `valgrind` in production though, it comes with significant performance overhead.

I'll close the issue since it's being tracked downstream now. Feel free to continue discussions though, or to reopen if it turns out the issue is not on oracledb.

**Closed by mmarchini** 2020-01-07 23:19 UTC

**Comment by lkiii** [comment] 2020-01-08 13:45
@mmarchini I have managed to start valgrind with option `valgrind --leak-check=yes`
[Here is the output](https://github.com/nodejs/help/files/4035541/output.zip)

**Comment by mmarchini** [comment] 2020-01-08 18:46
Hum, not much is reported by valgrind, which aligns with Dan suggestion that something is retaining memory. If memory is allocated and not freed, but it's also still referenced somewhere else, valgrind won't print stack traces for it by default. If you want to dig deeper, `valgrind --leak-check=full --show-leak-kinds=all` will give you way more information.

I suggest following Dan's suggestions first though, it might fix your problem.

**Comment by lkiii** [comment] 2020-01-08 20:16
I will try to change the connection type. The leak might be when a connection is being closed and opened and not binding, as initially thought.

Also @mmarchini  I have tried running `valgrind --leak-check=full --show-leak-kinds=all  --log-file=/dumpas/output` but after killing server I do not get the results. 
![image](https://user-images.githubusercontent.com/1472871/72012358-7b00f480-3264-11ea-8801-e4ce22c2f914.png)

Do you know why this might happen?

**Comment by lkiii** [comment] 2020-01-13 13:20
@mmarchini Hello, maybe you had several minutes to take a look at the latest valgrid output? Have `--leak-check=full --show-leak-kinds=all` extra parameters provided more details?

**Comment by mmarchini** [comment] 2020-01-13 15:41
Ah, I missed the edit. Will try to take a look later

**Comment by mmarchini** [comment] 2020-01-15 01:38
```
==236== 47,424,808 bytes in 2,891 blocks are still reachable in loss record 3,892 of 3,892
==236==    at 0x4C29E63: malloc (vg_replace_malloc.c:309)
==236==    by 0xAE81BEC: kpummapg (in /usr/lib/oracle/18.3/client64/lib/libclntsh.so.18.1)
==236==    by 0xD6551D9: kgh_invoke_alloc_cb (in /usr/lib/oracle/18.3/client64/lib/libclntsh.so.18.1)
==236==    by 0xD65050A: kghgex (in /usr/lib/oracle/18.3/client64/lib/libclntsh.so.18.1)
==236==    by 0xD6543D9: kghfnd (in /usr/lib/oracle/18.3/client64/lib/libclntsh.so.18.1)
==236==    by 0xD6529F1: kghalo (in /usr/lib/oracle/18.3/client64/lib/libclntsh.so.18.1)
==236==    by 0xD64FD10: kghgex (in /usr/lib/oracle/18.3/client64/lib/libclntsh.so.18.1)
==236==    by 0xD6543D9: kghfnd (in /usr/lib/oracle/18.3/client64/lib/libclntsh.so.18.1)
==236==    by 0xD6529F1: kghalo (in /usr/lib/oracle/18.3/client64/lib/libclntsh.so.18.1)
==236==    by 0xD64FD10: kghgex (in /usr/lib/oracle/18.3/client64/lib/libclntsh.so.18.1)
==236==    by 0xD64CDE2: kghalf (in /usr/lib/oracle/18.3/client64/lib/libclntsh.so.18.1)
==236==    by 0xD6CD0B8: kghualloc (in /usr/lib/oracle/18.3/client64/lib/libclntsh.so.18.1)
```

This is the allocation consuming more memory by a long shot. The stack is not very helpful aside from confirming that it's happening in the Oracle native module, and that it's not a traditional leak (those allocations are still referenced somewhere). It would be useful to get more stack frames here, but I don't know if Valgrind has an option to do that (from a quick Google Search it doesn't seem to have).

If you can provide a fully contained Docker image in the OracleDB issue with everything installed, from npm dependencies to a functional OracleDB instance (I don't know if OracleDB license allows this though), it will probably be easier to help.

**Comment by lkiii** [comment] 2020-01-16 14:55
@mmarchini 
I have created a docker environment with the issue.

docker-compose.yml
```
version: "3"
services:
  db:
    image: lkii/oracledbtestcase:xe
    shm_size: '1gb'
  node:
    image: lkii/oracledbtestcase:example-pool
    ports: 
        - "8081:8081"
    links: 
        - db

**Comment by lkiii** [comment] 2020-01-22 15:25
Hello @mmarchini,

Where you able to start the environment?
