### ISSUE TITLE
Client certificate renegotiation with HTTP/2

### ISSUE THREAD

**Issue by mechdrew** [nodejs/help#1799] opened 2019-02-27 20:50 UTC
* **Node.js Version**: 11.10.0 (and tested back into 8.15.0)
* **OS**: Windows 10 x64
* **Scope (install, code, runtime, meta, other?)**: runtime
* **Module (and version) (if relevant)**: `http2`

In our application, we have a login page that accepts multiple login types, including but not limited to username/password and client certificate. In order to prevent every attempt to access our web app from requesting a client certificate, we wait for the user to click a specific link, upon which the server uses the `request.connection.renegotiate({ requestCert: true })` to request the certificate. This works great when using `https` for the server, and has for years.

However, we recently needed to allow HTTP/2 connections to help improve client performance, which has been great until trying to use client certificates. `renegotiate` leads to `ERR_HTTP2_NO_SOCKET_MANIPULATION`, which makes sense due to the way HTTP/2 handles the socket and how `renegotiate` is trying to write directly to the socket. But this takes away our ability to request certificates only when necessary. Is there a different way we should be handling the certification request, or any alternatives that could help with this? We really want the login page to show before asking for the certificate.

I was directed here from nodejs/node#24728, so hopefully someone will be able to provide some guidance.

**Comment by bnoordhuis** [comment] 2019-02-28 08:09
It's perhaps not a direct answer to your question but HTTP/2 was designed with TLS 1.3 in mind and TLS 1.3 doesn't allow renegotiation.

Node.js will most likely support the Post-Handshake Authentication extension once it grows support for TLS 1.3, that lets you request a client certificate, but it remains to be seen how it's going to interact with HTTP/2.

If you're using TLS < 1.3, you can renegotiate up til the the point that the HTTP/2 connection preface is sent. Since you're already busy processing a request that won't help.

That means your problem is essentially unfixable without gross hacks like redirecting the client to a HTTP/1.1 connection.

**Comment by gireeshpunathil** [comment] 2019-06-21 05:21
answered, closing

**Closed by gireeshpunathil** 2019-06-21 05:21 UTC

**Comment by risacher** [comment] 2019-09-05 19:57
Anyone interested in this issue should also look at https://tools.ietf.org/html/draft-ietf-httpbis-http2-secondary-certs-04 and https://lists.w3.org/Archives/Public/ietf-http-wg/2019AprJun/0001.html
