### ISSUE TITLE
Node.js also installs NPM. Why then does NPM "not support Node.js version 12.2.0"?

### ISSUE THREAD

**Issue by axefrog** [nodejs/help#1907] opened 2019-05-11 20:38 UTC
* **Node.js Version**: 12.2.0
* **OS**: Windows 10
* **Scope (install, code, runtime, meta, other?)**: Install/NPM/Version
* **Module (and version) (if relevant)**: NPM

I've experienced this issue more than once in the past when a new version of Node, and the only advice I can find online seems to recommend manually upgrading my version of NPM.

1. I run through the installer to install a new version of Node
2. I see that the option to install NPM is fully selected:

![image](https://user-images.githubusercontent.com/298883/57574615-a76b3380-747f-11e9-82b4-21346369b725.png)

3. After installation is complete, I get this:

```
> npm install -g eslint
npm WARN npm npm does not support Node.js v12.2.0
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 6, 8, 9, 10, 11.
npm WARN npm You can find the latest version at https://nodejs.org/
C:\Users\axefr\AppData\Roaming\npm\eslint -> C:\Users\axefr\AppData\Roaming\npm\node_modules\eslint\bin\eslint.js
+ eslint@5.16.0
updated 1 package in 3.613s
```

Is the installer lying to me and just leaving my old version of NPM in place? If not, why is Node.js bundling a version of NPM that doesn't recognise it?

_Note: I know how to manually upgrade NPM. My question is more about the UX of Node.js installing the wrong version of NPM, or telling me it's installing NPM but in fact ignoring what's there._

**Comment by gireeshpunathil** [comment] 2019-05-12 03:05
@axefrog - can you please paste here the first 10 or so lines of your `npm\lib\utils\unsupported.js`?

**Comment by axefrog** [comment] 2019-05-15 21:04
Which unsupported.js should I use?

![image](https://user-images.githubusercontent.com/298883/57809478-def01d80-77a8-11e9-8a8c-a98fb732ca3c.png)

**Comment by gireeshpunathil** [comment] 2019-05-16 07:52
I guess it is `C:\Users\axefr\AppData\Roaming\npm\node_modules\npm\lib\utils` but I would like to see other content as well!

**Comment by JunBach** [comment] 2019-05-24 02:45
I encounter the same issue as well with nodejs v12.2.0
I install nodejs via chocolatey.

**Comment by axefrog** [comment] 2019-05-26 20:08
Snippets pasted in the same order as my screenshot (above):

```
'use strict'
var semver = require('semver')
var supportedNode = [
  {ver: '6', min: '6.0.0'},
  {ver: '8', min: '8.0.0'},
  {ver: '9', min: '9.0.0'},
  {ver: '10', min: '10.0.0'},
  {ver: '11', min: '11.0.0'},
  {ver: '12', min: '12.0.0'}
]
var knownBroken = '<4.7.0'
```

```
'use strict'
var semver = require('semver')
var supportedNode = [
  {ver: '6', min: '6.0.0'},
  {ver: '8', min: '8.0.0'},
  {ver: '9', min: '9.0.0'},
  {ver: '10', min: '10.0.0'},
  {ver: '11', min: '11.0.0'}
]
var knownBroken = '<4.7.0'
```

```
'use strict'
var semver = require('semver')
var supportedNode = [
  {ver: '6', min: '6.0.0'},
  {ver: '8', min: '8.0.0'},
  {ver: '9', min: '9.0.0'},
  {ver: '10', min: '10.0.0'},
  {ver: '11', min: '11.0.0'}
]
var knownBroken = '<4.7.0'
```

```
'use strict'
var semver = require('semver')
var supportedNode = [
  {ver: '4', min: '4.7.0'},
  {ver: '6', min: '6.0.0'},
  {ver: '7', min: '7.0.0'},
  {ver: '8', min: '8.0.0'}
]
var knownBroken = '<4.7.0'
```

Note: I have no idea what the origin of these different installations are. I don't install different versions of Node.js (or NPM) on purpose. If there are conflicts, I'd be interested in trying to understand how they arose.

**Comment by JunBach** [comment] 2019-05-27 02:32
Hmm, I am not sure why but the issue resolved after I have updated to node v12.3.1 and npm v6.9.0

**Comment by gireeshpunathil** [comment] 2019-05-27 05:45
@axefrog - thanks. So the issue at hand is understood as the prevalent npm library set is coming from your second block (though I don't know the root cause for this) and that section does not have entry for node v.12.x

My guess is that different types of installer / uninstaller / upgrader tools are used, which do not adhere to any common convention so do not understand each other about where the files are placed etc.

If you always stick to the use of official Node installer (as shown in your first update screenshot) and still if you are able to see the problem then let me know and I will try to recreate this myself, and report to Node / NPM. Or else please see if you are able to resolve this instance of the issue by manually removing other locations except item 2.

**Comment by gireeshpunathil** [comment] 2019-06-24 06:10
ping @axefrog

**Comment by gireeshpunathil** [comment] 2019-07-08 06:03
answered, closing

**Closed by gireeshpunathil** 2019-07-08 06:03 UTC
