### ISSUE TITLE
Sort about ten million data with Array.prototype.sort on Mac

### ISSUE THREAD

**Issue by mjc224000** [nodejs/help#2196] opened 2019-09-22 02:59 UTC
* **Version**:v10.16.3

* **Platform**:Darwin 192.168.0.104 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64

* **Subsystem**:

I am learning Algorithm 4 using node. i was trying to compare the speed of my sort method  with Array.prototype.sort when dealing with ten million data.
 then i found a bug using Array.prototype.sort.
i ask a friend to do the same on Windows platform ,but it work correctly ,i think this is a bug with Mac OS ,but i still think it is necessary to report.

[my project](https://github.com/mjc224000/algs)
// index.js
let {IO} = require('./StdIn')
const {MergeSort} = require('./MergeSort');
 
async function Main() {
    // read millions ints from file;
    let data = await IO.readInts("./data/LargeT.txt");
    // make a copy
    let data1 = [...data];

    //sort data with mergeSort and Array.prototype.sort
    let correct = MergeSort(data).join('\n');
    let inCorrect = data1.sort().join('\n');
    // save results
    let p1 = IO.Out('./Correct.txt', correct);
    let p2 = IO.Out("./InCorrect", inCorrect);

    await p1;
    await p2;

}

Main();
```

**Comment by ORESoftware** [comment] 2019-09-22 06:36
if the behavior is actually different for the same program and the same version of node.js on two different platforms, might be interesting

**Comment by Hakerh400** [comment] 2019-09-22 06:44
Duplicate of https://github.com/nodejs/node/issues/29517. As said, the order is implementation-defined, there's no guarantee, even on the same version of Node.js.

**Comment by mjc224000** [comment] 2019-09-22 12:46
> Duplicate of [nodejs/node#29517](https://github.com/nodejs/node/issues/29517). As said, the order is implementation-defined, there's no guarantee, even for the same version of Node.js.

it is not like that ,i just simply called sort method, which is supposed to return a sorted array,
instead  i got an array was  almost random. 
and i know with different implementations, the callback's arguments is not ordered as your link represented above. my point is that the mac os's implementation is not work properly.

**Comment by devsnek** [comment] 2019-09-22 14:07
by default sort compares things as strings. try `sort((a, b) => a - b)`

**Comment by Hakerh400** [comment] 2019-09-22 15:51
> it is not like that ,i just simply called sort method, which is supposed to return a sorted array,
instead i got an array was almost random.

I see now what you mean. It is not really related to that issue, but rather to you understanding of how `Array.prototype.sort` works. The documentation for [Array.prototype.sort](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort) says that if the callback is omitted, *the array elements are converted to strings, then sorted according to each character's Unicode code point value*. At the line `data1.sort().join('\n')` you're omitting the callback (sort function) and it brings `0` on the beginning, then all numbers that start with `1`, then all that start with `2`, and so on. It is not random and it is specified in the documentation.

> I ask a friend to do the same on Windows platform ,but it work correctly

Tested on Windows and unable to reproduce. It gives the expected `InCorrect.txt` as in your repo, which is, as explained, the expected result.

Still a duplicate, but now duplicate of https://github.com/nodejs/node/issues/13615

**Comment by mjc224000** [comment] 2019-09-23 02:44
> > it is not like that ,i just simply called sort method, which is supposed to return a sorted array,
> > instead i got an array was almost random.
> 
> I see now what you mean. It is not really related to that issue, but rather to your understanding of how `Array.prototype.sort` works. The documentation for [Array.prototype.sort](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort) says that if the callback is omitted, _the array elements are converted to strings, then sorted according to each character's Unicode code point value_. At the line `data1.sort().join('\n')` you're omitting the callback (sort function) and it brings `0` on the beginning, then all numbers that start with `1`, then all that start with `2`, and so on. It is not random and it is specified in the documentation.
> 
> > I ask a friend to do the same on Windows platform ,but it work correctly
> 
> Tested on Windows and unable to reproduce. It gives the `InCorrect.txt` as in your repo, which is, as explained, the expected result.
> 
> Still a duplicate, but now duplicate of [nodejs/node#13615](https://github.com/nodejs/node/issues/13615)

Thanks for your answers，you teach me a lesson. I feel embarrassed that i was stupid enough to believe that was a bug

**Closed** 2019-09-23 02:45 UTC
