### ISSUE TITLE
gyp stack err 404 response downloading https://nodejs.org/download/release/v16.0.0/node-v16.0.0-headers.tar.gz

### ISSUE THREAD

**Issue by iam-frankqiu** [nodejs/help#3109] opened 2020-12-04 06:23 UTC
* **Version**: v16.0.0
* **Platform**: Mac OS X 
* **Subsystem**: 10.15.6

### What steps will reproduce the bug?
`npx create-react-app react-app`

### How often does it reproduce? Is there a required condition?

May be 1 minute. 

### What is the expected behavior?
No erros.

### What do you see instead?
Installed success.

### Additional information
```
Exit code: 1
Command: node ./build.js
Arguments: 
Directory: /Users/qiuquanhu/Documents/forkItem/snowpack/node_modules/deasync
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@7.1.2
gyp info using node@16.0.0 | darwin | x64
gyp info find Python using Python version 2.7.16 found at "/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python"
gyp http GET https://nodejs.org/download/release/v16.0.0/node-v16.0.0-headers.tar.gz
gyp http 404 https://nodejs.org/download/release/v16.0.0/node-v16.0.0-headers.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: 404 response downloading https://nodejs.org/download/release/v16.0.0/node-v16.0.0-headers.tar.gz
gyp ERR! stack     at Request.<anonymous> (/Users/qiuquanhu/Documents/forkItem/snowpack/node_modules/node-gyp/lib/install.js:187:14)
gyp ERR! stack     at Request.emit (node:events:388:22)
gyp ERR! stack     at Request.onRequestResponse (/Users/qiuquanhu/Documents/forkItem/snowpack/node_modules/request/request.js:1059:10)
gyp ERR! stack     at ClientRequest.emit (node:events:376:20)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (node:_http_client:664:27)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (node:_http_common:126:17)
gyp ERR! stack     at TLSSocket.socketOnData (node:_http_client:530:22)
gyp ERR! stack     at TLSSocket.emit (node:events:376:20)
gyp ERR! stack     at addChunk (node:internal/streams/readable:304:12)
gyp ERR! stack     at readableAddChunk (node:internal/streams/readable:279:9)
gyp ERR! System Darwin 19.6.0
gyp ERR! command "/usr/local/bin/node" "/Users/qiuquanhu/Documents/forkItem/snowpack/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /Users/qiuquanhu/Documents/forkItem/snowpack/node_modules/deasync
gyp ERR! node -v v16.0.0
```

**Comment by iam-frankqiu** [comment] 2020-12-05 01:15
> @iam-frankqiu it seems the app you are trying to use requires https://github.com/abbr/deasync, chances is are they don't have a version compatible with Node.js 16. Your best luck is to install or build an actual release of Node.js.

I am sorry for my carelessness. Thank you

**Comment by aduh95** [comment] 2020-12-05 11:21
Glad I could help. I'm closing this, feel free to reopen if you need more assistance or open a new issue if you found a bug.

> Can't I issue the not released version of node?

You definitely can! Bug reports on the `master` branch are very helpful and welcome, we'd rather fix the bugs before we release them for sure. FYI when reporting a bug on the master branch, we usually refer to the commit ID rather than `v16.0.0` to avoid confusion with actual releases.

**Closed by aduh95** 2020-12-05 11:21 UTC

**Comment by iam-frankqiu** [comment] 2020-12-05 13:19
> Glad I could help. I'm closing this, feel free to reopen if you need more assistance or open a new issue if you found a bug.
> 
> >

Thank you for your help. My question is: Is really is a bug or just because hasn't released?

**Comment by aduh95** [comment] 2020-12-05 13:45
It’s not a bug, Node.JS introduces breaking changes in each semver major version, it would be unrealistic to expect every npm package to support Node.JS 16 before it’s released.

**Comment by iam-frankqiu** [comment] 2020-12-05 14:17
> introduces



> It’s not a bug, Node.JS introduces breaking changes in each semver major version, it would be unrealistic to expect every npm package to support Node.JS 16 before it’s released.

I agree with you. But it seems that it's not so convenient for us to use the not released version of Node to test before release. Because some file of URL is wrong. I am thinking maybe we can make some improvements. how do you think?

**Comment by aduh95** [comment] 2020-12-05 22:29
> But it seems that it's not so convenient for us to use the not released version of Node to test before release.

You can try out [Nightly builds](https://nodejs.org/download/nightly/), they come with a the expected files including the header tar ball. Link to the latest build: https://nodejs.org/download/nightly/v16.0.0-nightly202012050fd121e00c/

If you want to build your own version, you can `make tar-headers` on the `master` branch to get the expected file, I'm don't know enough about `deasync` build chain to tell you what's the correct way of building it on an unsupported version.

Another "obvious" workaround would be to not use `deasync` or any package that compiles C++ addons; in my experience it's sometimes quicker to find a JS or WASM equivalent than figuring out how to compile it yourself.

**Comment by iam-frankqiu** [comment] 2020-12-06 06:23
> If you want to build your own version, you can `make tar-headers` on the `master` branch to get the expected file, I'm don't know enough about `deasync` build chain to tell you what's the correct way of building it on an unsupported version.

Ok. Thank you pretty much.
