### ISSUE TITLE
[SWIG] [ANSI C] Fatal error: utility: No such file or directory

### ISSUE THREAD

**Issue by papaiatis** [nodejs/help#684] opened 2017-06-19 14:09 UTC
* **Node.js Version**: v6.10.1
* **OS**: Ubuntu 14.10
* **Scope (install, code, runtime, meta, other?)**: not sure
* **Module (and version) (if relevant)**: node-gyp

Copied from here: https://github.com/nodejs/node-gyp/issues/1238

Hi all,

I'm trying to create a javascript wrapper for an ANSI C header file using SWIG and node-gyp.
I'm basically using this this doc as a starting point: http://www.swig.org/Doc3.0/Javascript.html#Javascript

I created the wrapper C file with SWIG which I'd like to build with node-gyp, however I does not seem to be finding some system headers:

```
$ node-gyp build                                              
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@6.10.1 | linux | x64
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory `/home/atis/swig-test/src/build'
  CC(target) Release/obj.target/test2/test2_wrap.o
In file included from /home/atis/.node-gyp/6.10.1/include/node/node.h:42:0,
                 from ../test2_wrap.c:132:
/home/atis/.node-gyp/6.10.1/include/node/v8.h:21:19: fatal error: utility: No such file or directory
 #include <utility>
                   ^
compilation terminated.
make: *** [Release/obj.target/test2/test2_wrap.o] Error 1
make: Leaving directory `/home/atis/swig-test/src/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 3.13.0-119-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/bin/node-gyp" "build"
gyp ERR! cwd /home/atis/swig-test/src
gyp ERR! node -v v6.10.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
```

I found the `utility` header file here: /usr/include/c++/4.8/utility
I have installed "swig3.0", "libjavascriptcoregtk-1.0-dev" and "libv8-dev" too.
I'm on Ubuntu 14.10, kernel 3.13.0-119.
gcc version 4.8.4

```
$ node-gyp list
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@6.10.1 | linux | x64
6.10.1
gyp info ok 
```

Note that I'm not building a NodeJS extension, I just want to use a C header file in JS.
Any help would be great!

**Comment by esellier** [comment] 2017-07-05 14:00
You should add the include dirs in your gyp file:
      'include_dirs+': [
          '/usr/include',
          '/usr/include/c++/4.2.1',
        ]
next to target_name

**Comment by aqrln** [comment] 2017-07-07 08:15
Well, my guess would be that you're trying to build it with a C compiler, while the V8 and Node.js headers are in C++.

**Comment by bladedoyle** [comment] 2017-07-13 02:32
You can tell CMAKE to use a cplusplus compiler for your generated .i file(s) with the CMAKE SET_SOURCE_FILES_PROPERTY() macro.  ex:

SET_SOURCE_FILES_PROPERTIES(YourPreprocessedInterfaceFile.i PROPERTIES CPLUSPLUS ON)

**Comment by gireeshpunathil** [comment] 2018-03-11 06:07
closing as answered, please re-open if the issue is still outstanding.

**Closed by gireeshpunathil** 2018-03-11 06:07 UTC
