### ISSUE TITLE
BadRequestError: request aborted

### ISSUE THREAD

**Issue by KayHS** [nodejs/help#2155] opened 2019-08-30 14:19 UTC
I have an api that has an endpoint which accepts a relatively large payload (7mb). If i perform a test which attempts to hit this endpoint concurrently. I start to get the following error.

*Request*
```
{"log_id":"db0ac1d0-cafe-11e9-afec-e91ff7e323e3","level":"info","request":{"method":"POST","path":"<removed>","url":"<api_url_removed>","body":{},"forward_for":"<removed>","content_type":"application/json","content_length":"7687038"},"message":"Received","log_type":"request","timestamp":"2019-08-30 08:19:15"}
```

*Error*

> BadRequestError: request aborted at IncomingMessage.onAborted (/app/node_modules/raw-body/index.js:231:10) at IncomingMessage.emit (events.js:189:13) at abortIncoming (_http_server.js:449:9) at socketOnClose (_http_server.js:442:3) at Socket.emit (events.js:194:15) at TCP._handle.close (net.js:600:12)

*App*
```
app.use(express.json({limit: "16mb"}));
app.use(express.urlencoded({ limit: "16mb", extended: true, parameterLimit: 50000 }));
```

Why are these request being aborted and how can i handle this?

**Comment by gireeshpunathil** [comment] 2019-12-23 14:23
@KayHS - is this still an issue?

looks like the server is deeming the request as invalid due to some constraints that is not met.

can you run the server after: `export DEBUG=express`  ? this will throw additional debug messages around vital control flow points in the server

**Comment by Mnabawy** [comment] 2020-09-21 19:59
this issue is related to the body-parser package setup 

```
// parse application/json
app.use(bodyParser.json())

app.use(f`unction (req, res) {
  res.setHeader('Content-Type', 'text/plain')
  res.write('you posted:\n')
  res.end(JSON.stringify(req.body, null, 2))
})
```
check this link for more details
[adding generic json and url encoded ](https://github.com/expressjs/body-parser#expressconnect-top-level-generic)

**Comment by gireeshpunathil** [comment] 2020-09-22 02:14
ping @KayHS

**Comment by PoojaDurgad** [comment] 2020-09-23 10:05
@KayHS , is this issue resolved?

**Comment by Mnabawy** [comment] 2020-09-23 11:53
@PoojaDurgad we hope so

**Comment by gireeshpunathil** [comment] 2020-09-23 14:06
closing as resolved

**Closed by gireeshpunathil** 2020-09-23 14:06 UTC

**Comment by kushagraagent47** [comment] 2021-01-16 13:20
I faced this error because of cloudflare, Cloudflare adds limit on max upload size, you can directly use ip address to upload your files.

**Comment by ChenJunsen** [comment] 2022-07-19 00:48
opps,there seems still a problem:
`
BadRequestError: request aborted
    at IncomingMessage.onAborted (E:\workspace\MySQL\RouteHubNetworkOptimization\node_modules\raw-body\index.js:238:10)
    at IncomingMessage.emit (events.js:376:20)
    at abortIncoming (_http_server.js:565:9)
    at socketOnClose (_http_server.js:558:3)
    at Socket.emit (events.js:388:22)
    at TCP.<anonymous> (net.js:673:12)
`
my code:
`
const express = require('express')
const bodyParser = require('body-parser');
const server = express()

const startServer = () => {
  // server.use(express.json())
  // server.use(express.raw())
  // server.use(express.urlencoded({ extended: true}))

  server.use(bodyParser.json({ limit: '50mb' }));
  server.use(bodyParser.urlencoded({ limit: '50mb', extended: true }));

  server.post('/flight/common/getFlightDataList', (req, resp) => {
    console.log(req.query)
    resp.send({
      code: 200
    })
  })

  const { port, hostName } = $serverConfig
  server.listen(port, hostName, () => {
    console.log(`服务已经启动:http://${ hostName }:${ port }`)
  })
}
module.exports = { startServer }
`
neither i use the stand alone body-parser or express insider body-parser
This problem only occurs when I make a post request.It's correct with get request.

**Comment by bkarlow-optimo** [comment] 2022-11-10 20:00
@ChenJunsen - I see this same issue.  Were you able to resolve somehow?

**Comment by ChenJunsen** [comment] 2022-11-11 00:25
> @ChenJunsen - I see this same issue.  Were you able to resolve somehow?

did you import the mockJS?

**Comment by ngoctienbk** [comment] 2022-11-17 09:21
Any update on this problem? I still face this randomly only on production, I cannot reproduce it in my local or my staging.
My code: 
index.ts: 

```
import express from 'express'
import router from './router'
import passport from 'passport'

const app: express.Express = express()

if (process.env.NODE_ENV === 'production') {
  app.set('trust proxy', true)
}
app.use('/', router)

module.exports = {
  path: '/api',
  handler: app
}

```

nuxt.config.js: 

```
import express from 'express'
export default {
  ...
  serverMiddleware: [
    express.json({limit: '50mb'}),
    express.urlencoded({limit: '50mb', extended: true}),
    ...
  }
}
```

Although I didn't use raw-body or body-parser, this error still sometime happen on my production.

P/s: I'm using NodeJS 14.20.1, it's seem `body-parser` automatically import into Node so far. Does in related?

**Comment by jirihajek** [comment] 2022-11-28 09:12
Since the only issue for me was that the error is repeatedly logged, while it doesn't seem to be interesting at all, I got rid of it in the logs by the following code:

```
app.use((err, req, res, next) => {
  if (err && err.code === 'ECONNABORTED') {
    res.status(400).end(); // Don't process this error any further to avoid its logging
  } else
    next(err);
});
```

**Comment by weiliang903** [comment] 2023-04-27 03:04
Same error => [this is an exception thrown by raw body that is used by body-parser](https://stackoverflow.com/a/70478694/8818057)

**Comment by MatiasEndres** [comment] 2025-03-20 13:17
> i am also facing this within graphql federation gateway.
> 
> the problem here is that the whole gateway hangs because of that error so basically the service is totally hanging. .. is it possible to catch that exception ? is the cause understood ? i am not able to rproduce

Did you find some solution? same problem here using GraphQL

**Comment by dberardo-com** [comment] 2025-03-20 13:22
the issue is that the nestjs log is so minimal i dont even know whether the issue is on a backend-service side or in the gateway itself ... 

[Nest] 1  - ERROR [ExceptionsHandler] request aborted
BadRequestError: request aborted
    at IncomingMessage.onAborted (/usr/src/app/node_modules/raw-body/index.js:245:10)
    at IncomingMessage.emit (node:events:520:28)
    at IncomingMessage._destroy (node:_http_incoming:179:10)
    at _destroy (node:internal/streams/destroy:102:25)
    at IncomingMessage.destroy (node:internal/streams/destroy:64:5)
    at abortIncoming (node:_http_server:597:9)
    at socketOnClose (node:_http_server:591:3)
    at Socket.emit (node:events:532:35)
    at TCP.<anonymous> (node:net:687:12)

i am now trying this: https://github.com/nodejs/help/issues/2155#issuecomment-1524558343 
but i am not so hopeful  ... 

@MatiasEndres  are you also facing this when using GQL federation or only on a simple GQL service ?

i would rather use fastify with GQL federation but the cookies management is so messed up that i am not able to pass cookies through the gateway ... i am so disappointed at this, since it is the ABC of web programming and cookies are not handled properly :-/ so i am stuck with express ...
