### ISSUE TITLE
Node.js installation with linux mint 18 cinnamon

### ISSUE THREAD

**Issue by samisabir212** [nodejs/help#579] opened 2017-04-13 19:53 UTC
how do i install node.js when node.js doesnt support linux mint 18 cinnamon?

* **Node.js latest version**:
* **Linux 18 cinnamon**:
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:

```
-->

**Comment by ORESoftware** [comment] 2017-04-14 06:46
What makes you think Node.js cannot run on Mint 18 Cinnamon?

**Comment by gibfahn** [comment] 2017-04-15 10:00
If you want to use a package manager, see [this guide](https://nodejs.org/en/download/package-manager/) (Linux Mint is a Debian based distro, so the `apt` or `apt-get` instructions should work fine.

If you want to install node manually, there is no "installation" on Linux per se, you just need to extract the tarball, and make sure the `node` and `npm` binaries in the `./bin` subdirectory are somewhere in your path.

I find [nvm](https://github.com/creationix/nvm#install-script) is useful for managing node installations (it will download, extract, and add to path for you). If you want to do things manually, you can do something like:

```bash
wget https://nodejs.org/dist/v6.9.2/node-v6.9.2-linux-x64.tar.gz
tar -xf node-v6.9.2-linux-x64.tar.gz --directory /usr/local --strip-components 1
```

This will put the `./bin` directory in `/usr/local/bin`, which should be in your `$PATH` already. You can verify that it worked with:

```bash
node --version
npm --version
```

**Comment by samisabir212** [comment] 2017-04-15 13:48
This is very helpful!
Thank you for your time.

**Comment by gibfahn** [comment] 2017-04-15 17:21
I'll close this, but if you have any more questions/issues just comment on this and I'll reopen.

**Closed by gibfahn** 2017-04-15 17:21 UTC

**Comment by petercr** [comment] 2018-01-03 17:15
I can only get a legacy version of NodeJS to install on Linux Mint 18.3 'Sylvia' 
I tried using the info shown on the NodeJs website but the terminal told me that I can only install the legacy version of Node. Version 4.2.6

**Comment by gibfahn** [comment] 2018-01-03 17:20
@petercr so you tried:

```bash
curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
sudo apt-get install -y nodejs
```

And that didn't work?

**Comment by petercr** [comment] 2018-01-04 18:11
Yes here's a screenshot of the problem I seem to be having. I'm not sure if the problem is directly related to the issue I'm having with the Visual Studio Code package and that's what causing the problem. But either way it is saying that the latest version of node is installed **4.2.6-dfsg-lubuntu4.1** 

Please let me know if you have any other ideas. 
![Console screenshot showing terminal not updating NodeJS(https://user-images.githubusercontent.com/26460352/34577851-b7ef2ac6-f150-11e7-927a-8c9505b4ada0.png)

**Comment by petercr** [comment] 2018-01-05 13:59
I have resolved the issue, it was the broken package associated with Visual Studio Code and Visual Studio Code Insiders Edition. After removing both of them and updating the package list, I was able to install the latest stable build of Node JS. 
Thank you :clap: :smiley:

**Comment by jpauljayme** [comment] 2018-09-10 15:05
Hi i am using Linux Mint 18.2 "Sonya" and i cannot proceed in installing...
![screenshot_2018-09-10_23-04-35](https://user-images.githubusercontent.com/39881625/45305914-eee69c00-b54d-11e8-8eb4-1356e1abee74.png)

**Comment by AyushG3112** [comment] 2018-09-10 15:38
Are you using the `apt` utility by any chance?
