### ISSUE TITLE
failing to deploy - TypeError cannot read property of '_events' of undefined

### ISSUE THREAD

**Issue by twigs67** [nodejs/help#3521] opened 2021-08-29 23:01 UTC
* **Node.js Version**:
* **OS**:
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:

node version: 14.4.0
OS: node:14.4.0-alpine3.11

Hello,

Apologies if this isn't the correct place for this, but I'm completely lost as to why I'm getting this error. events=target._events does not exist anywhere in my codebase, so i'm guessing it is due to a node_module, but I can't find the culprit.

What's worse is I can't reproduce this locally, it just fails when deploying to our dev environment.

```
2021-08-29T14:26:05.489-04:00	Running Node Cluster

2021-08-29T14:26:05.489-04:00	Master server started on 1

2021-08-29T14:26:05.529-04:00	events.js:350

2021-08-29T14:26:05.530-04:00	events = target._events;

2021-08-29T14:26:05.530-04:00	^

2021-08-29T14:26:05.530-04:00	TypeError: Cannot read property '_events' of undefined

2021-08-29T14:26:05.530-04:00	at _addListener (events.js:350:19)

2021-08-29T14:26:05.530-04:00	at addListener (events.js:406:10)

2021-08-29T14:26:05.530-04:00	at Function.clusterize (/usr/src/app/dist/src/core/node-cluster.js:40:30)

2021-08-29T14:26:05.530-04:00	at Object.<anonymous> (/usr/src/app/dist/src/main.js:121:38)

2021-08-29T14:26:05.530-04:00	at Module._compile (internal/modules/cjs/loader.js:1200:30)

2021-08-29T14:26:05.530-04:00	at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)

2021-08-29T14:26:05.530-04:00	at Module.load (internal/modules/cjs/loader.js:1049:32)

2021-08-29T14:26:05.530-04:00	at Function.Module._load (internal/modules/cjs/loader.js:937:14)

2021-08-29T14:26:05.530-04:00	at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)

2021-08-29T14:26:05.530-04:00	at internal/main/run_main_module.js:17:47
package.json

Cluster server started on 56
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at process.target._send (internal/child_process.js:835:20)
    at process.target.send (internal/child_process.js:706:19)
    at sendHelper (internal/cluster/utils.js:26:15)
    at send (internal/cluster/child.js:193:10)
    at EventEmitter.cluster._setupWorker (internal/cluster/child.js:46:3)
    at initializeClusterIPC (internal/bootstrap/pre_execution.js:337:13)
    at prepareMainThreadExecution (internal/bootstrap/pre_execution.js:62:3)
    at internal/main/run_main_module.js:7:1
Emitted 'error' event on Worker instance at:
    at process.<anonymous> (internal/cluster/worker.js:29:12)
    at process.emit (events.js:315:20)
    at internal/child_process.js:839:39
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at process.target._send (internal/child_process.js:835:20)
    at process.target.send (internal/child_process.js:706:19)
    at sendHelper (internal/cluster/utils.js:26:15)
    at send (internal/cluster/child.js:193:10)
    at EventEmitter.cluster._setupWorker (internal/cluster/child.js:46:3)
    at initializeClusterIPC (internal/bootstrap/pre_execution.js:337:13)
    at prepareMainThreadExecution (internal/bootstrap/pre_execution.js:62:3)
    at internal/main/run_main_module.js:7:1
Emitted 'error' event on Worker instance at:
    at process.<anonymous> (internal/cluster/worker.js:29:12)
    at process.emit (events.js:315:20)
    at internal/child_process.js:839:39
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}
```

I will happily pay someone to help me figure this out. 

Thanks for reading

**Comment by Mesteery** [comment] 2021-08-29 23:03
duplicate of #3520.

**Closed by Mesteery** 2021-08-29 23:03 UTC
Labels: duplicate

**Comment by twigs67** [comment] 2021-08-29 23:24
shoot sorry @aduh95... it's been such a long day, I didn't even notice what repo I was in... lol :/
