### ISSUE TITLE
When I tried to deconstruct "stat", I got "Cannot read properties of undefined (reading '_checkModeProperty')"

### ISSUE THREAD

**Issue by brenner8023** [nodejs/help#3713] opened 2022-01-31 05:02 UTC
### Details

When I tried to deconstruct "stat", I got "Cannot read properties of undefined (reading '_checkModeProperty')".

![image](https://user-images.githubusercontent.com/31237954/151741425-c4f396cd-2511-47fa-80da-0b645b2a149a.png)

![image](https://user-images.githubusercontent.com/31237954/151741303-5d8bafc3-c5b5-4d69-9e10-7b3b40b7cded.png)

![image](https://user-images.githubusercontent.com/31237954/151741357-3ce231b9-3512-4a24-909b-3c2fb6f30dc6.png)

### Node.js version

```
v16.13.2
```

### Example code

```js
const fs = require('fs')
const path = require('path')

const main = (dirName) => {
  const dir = path.resolve(__dirname, dirName)
  const files = fs.readdirSync(dir)
  files.forEach(file => {
    const { isDirectory } = fs.statSync(path.join(dir, file))
    if (isDirectory()) {
      console.log(file)
    }
  })
}
main('.')
```

### Operating system

Windows 10

### Scope

code

### Module and version

Not applicable.

**Comment by VoltrexMaster** [comment] 2022-02-01 08:08
This is intended behavior, you can't deconstruct methods and use methods that rely on the parent object that holds the properties/methods that certain method you've deconstructed is using in it's function body.

However, you can do something like the following if your use case worths it:
```js
const stat = fs.statSync(...);

const { isDirectory } = stat;

if (isDirectory.call(stat)) { ... }
```

**Comment by gireeshpunathil** [comment] 2022-06-21 03:12
@brenner8023 - is this resolved?

**Comment by gireeshpunathil** [comment] 2023-08-02 02:47
closing as answered

**Closed by gireeshpunathil** 2023-08-02 02:47 UTC
Labels: workaround provided
