### ISSUE TITLE
Node.js How to excecute the below function synchronously

### ISSUE THREAD

**Issue by Gunasekaran15** [nodejs/help#1351] opened 2018-06-22 06:10 UTC
I want to excecute the below function synchronously without change the time and output will be 123.How to do using node.js

function f1(){
  setTimeout(function() {
    console.log('Hi I am order 1');
  }, 3000);
}

function f2() {
  setTimeout(function() {
    console.log('Hi I am order 2');
  }, 2000);
}

function f3() {
  setTimeout(function() {
    console.log('Hi I am order 3');
  }, 1000);
}

f3();
f2();
f1();

**Comment by gireeshpunathil** [comment] 2018-06-22 06:19
what is the use case for this?
while it is easy to do with [Promises](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise), it breaks what was meant by those methods.

**Comment by trvsapjiac** [comment] 2018-06-22 09:12
> I want to excecute the below function synchronously without change the time and output will be 123.How to do using node.js

You can't. In general, a function may perform arbitrary asynchronous stuff, so until you wait for it to complete (using promises or callbacks), you can't know when the function completed all asynchronous methods it produced.

However, though you may or may not find it useful, in this particular code you posted, you can do some tricks by overriding `setTimeout` or `console.log` functions in order to track when the data is logged to the console. Note that this is not a good practice and it doesn't work in general cases.

```js
'use strict';

function f1(){
  setTimeout(() => {
    console.log('Hi I am order 1');
  }, 3000);
}

function f2() {
  setTimeout(() => {
    console.log('Hi I am order 2');
  }, 2000);
}

function f3() {
  setTimeout(() => {
    console.log('Hi I am order 3');
  }, 1000);
}

var sem = 0;

console.log = (log => (...args) => {
  log(...args);
  sem = 1;
})(console.log);

(async () => {
  var call = func => new Promise(res => {
    func();
    var f = () => {
      if(sem === 0) return setTimeout(f);
      sem = 0;
      res();
    };
    f();
  });

  await call(f1);
  await call(f2);
  await call(f3);
})();
```

```console
> node index.js
Hi I am order 1
Hi I am order 2
Hi I am order 3
```

**Comment by gireeshpunathil** [comment] 2018-06-28 08:18
@Gunasekaran15 - you ok with the above?

**Comment by littlebroto1** [comment] 2018-06-29 18:59
I think you can do what you want if you use worker threads. I have seen where some people claim they used worker threads with stuff like this. I have no idea how they work and don't be surprised if it doesn't work because I don't know anything about workers. Even though you my want to check it out and see if you can do what you want with them. Please don't judge me if this is totally wrong because I have no idea what worker threads even do and I am just telling you what I have read.

**Comment by trvsapjiac** [comment] 2018-06-30 18:04
@Gunasekaran15 It is possible to achieve something like this using child process, as @littlebroto1 suggested, but the problem is that you can't pass any arguments to these functions and you can't reference any local or global variables from the surrounding. Here is an example how it can be achieved:

```js
'use strict';

var fs = require('fs').promises;
var cp = require('child_process');

const TEMP_FILE = './temp.js';

function f1(){
  setTimeout(() => {
    console.log('Hi I am order 1');
  }, 3000);
}

function f2() {
  setTimeout(() => {
    console.log('Hi I am order 2');
  }, 2000);
}

function f3() {
  setTimeout(() => {
    console.log('Hi I am order 3');
  }, 1000);
}

(async () => {
  var call = func => new Promise(async res => {
    var code = `'use strict';(${func})();`;
    await fs.writeFile(TEMP_FILE, code);

    var proc = cp.spawn('node', [TEMP_FILE]);
    proc.stdout.pipe(process.stdout);
    proc.stderr.pipe(process.stderr);

    proc.on('exit', async () => {
      await fs.unlink(TEMP_FILE);
      res();
    });
  });

  await call(f1);
  await call(f2);
  await call(f3);
})();
```

**Comment by littlebroto1** [comment] 2018-06-30 19:49
I believe the easiest way to do this is to make your own timer.

I just made one and it works like a charm.

Here is your code after I added the timer.
```js
function timer(mil) {
    var time1 = new Date().getTime();
    var time2 = new Date().getTime();
    while ((time2 - time1) <= mil) {
        if ((time2 - time1) >= mil) {
            return;
        }
        time2 = new Date().getTime()
    }
}

function f1() {
    timer(3000)
    console.log('Hi I am order 1');
}

function f2() {
    timer(2000)
    console.log('Hi I am order 2');
}

function f3() {
    timer(1000)
    console.log('Hi I am order 3');
}

f3();
f2();
f1();
```

**Comment by gireeshpunathil** [comment] 2018-07-31 10:13
closing as answered

**Closed by gireeshpunathil** 2018-07-31 10:13 UTC
