### ISSUE TITLE
GLIBC_2.25 not found

### ISSUE THREAD

**Issue by japrozs** [nodejs/help#3489] opened 2021-07-29 11:52 UTC
Hi there, I'm trying to deploy a node js app in a docker container using dokku. Whenever I try to deploy it, I get the following error:
```bash
root@api:~# docker tag japrozs/spam:4 dokku/api:latest
root@api:~# dokku tags:deploy api latest
-----> Releasing api (dokku/api:latest)...
-----> Deploying api (dokku/api:latest)...
-----> No Procfile found in app image
       DOKKU_SCALE declares scale -> web=1
-----> Attempting pre-flight checks
       For more efficient zero downtime deployments, create a file CHECKS.
       See http://dokku.viewdocs.io/dokku/deployment/zero-downtime-deploys/ for examples
       CHECKS file not found in container: Running simple container check...
-----> Waiting for 10 seconds ...
b7eb33f2fd56bb53438cc267e7ea5ede285544a41fbd7f563341e76dbbc4f5d2
App container failed to start!!
=====> api web container output:
       node:internal/modules/cjs/loader:1151
         return process.dlopen(module, path.toNamespacedPath(filename));
                        ^
       Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /usr/src/app/node_modules/argon2/lib/binding/napi-v3/argon2.node)
           at Object.Module._extensions..node (node:internal/modules/cjs/loader:1151:18)
           at Module.load (node:internal/modules/cjs/loader:972:32)
           at Function.Module._load (node:internal/modules/cjs/loader:813:14)
           at Module.require (node:internal/modules/cjs/loader:996:19)
           at require (node:internal/modules/cjs/helpers:92:18)
           at Object.<anonymous> (/usr/src/app/node_modules/argon2/argon2.js:9:56)
           at Module._compile (node:internal/modules/cjs/loader:1092:14)
           at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
           at Module.load (node:internal/modules/cjs/loader:972:32)
           at Function.Module._load (node:internal/modules/cjs/loader:813:14) {
         code: 'ERR_DLOPEN_FAILED'
       }
       node:internal/modules/cjs/loader:1151
         return process.dlopen(module, path.toNamespacedPath(filename));
                        ^
       Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /usr/src/app/node_modules/argon2/lib/binding/napi-v3/argon2.node)
           at Object.Module._extensions..node (node:internal/modules/cjs/loader:1151:18)
           at Module.load (node:internal/modules/cjs/loader:972:32)
           at Function.Module._load (node:internal/modules/cjs/loader:813:14)
           at Module.require (node:internal/modules/cjs/loader:996:19)
           at require (node:internal/modules/cjs/helpers:92:18)
           at Object.<anonymous> (/usr/src/app/node_modules/argon2/argon2.js:9:56)
           at Module._compile (node:internal/modules/cjs/loader:1092:14)
           at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
           at Module.load (node:internal/modules/cjs/loader:972:32)
           at Function.Module._load (node:internal/modules/cjs/loader:813:14) {
         code: 'ERR_DLOPEN_FAILED'
       }
       node:internal/modules/cjs/loader:1151
         return process.dlopen(module, path.toNamespacedPath(filename));
                        ^
       Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /usr/src/app/node_modules/argon2/lib/binding/napi-v3/argon2.node)
           at Object.Module._extensions..node (node:internal/modules/cjs/loader:1151:18)
           at Module.load (node:internal/modules/cjs/loader:972:32)
           at Function.Module._load (node:internal/modules/cjs/loader:813:14)
           at Module.require (node:internal/modules/cjs/loader:996:19)
           at require (node:internal/modules/cjs/helpers:92:18)
           at Object.<anonymous> (/usr/src/app/node_modules/argon2/argon2.js:9:56)
           at Module._compile (node:internal/modules/cjs/loader:1092:14)
           at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
           at Module.load (node:internal/modules/cjs/loader:972:32)
           at Function.Module._load (node:internal/modules/cjs/loader:813:14) {
         code: 'ERR_DLOPEN_FAILED'
       }
       node:internal/modules/cjs/loader:1151
         return process.dlopen(module, path.toNamespacedPath(filename));
                        ^
       Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /usr/src/app/node_modules/argon2/lib/binding/napi-v3/argon2.node)
           at Object.Module._extensions..node (node:internal/modules/cjs/loader:1151:18)
           at Module.load (node:internal/modules/cjs/loader:972:32)
           at Function.Module._load (node:internal/modules/cjs/loader:813:14)
           at Module.require (node:internal/modules/cjs/loader:996:19)
           at require (node:internal/modules/cjs/helpers:92:18)
           at Object.<anonymous> (/usr/src/app/node_modules/argon2/argon2.js:9:56)
           at Module._compile (node:internal/modules/cjs/loader:1092:14)
           at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
           at Module.load (node:internal/modules/cjs/loader:972:32)
           at Function.Module._load (node:internal/modules/cjs/loader:813:14) {
         code: 'ERR_DLOPEN_FAILED'
       }
       node:internal/modules/cjs/loader:1151
         return process.dlopen(module, path.toNamespacedPath(filename));
                        ^
       Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /usr/src/app/node_modules/argon2/lib/binding/napi-v3/argon2.node)
           at Object.Module._extensions..node (node:internal/modules/cjs/loader:1151:18)
           at Module.load (node:internal/modules/cjs/loader:972:32)
           at Function.Module._load (node:internal/modules/cjs/loader:813:14)
           at Module.require (node:internal/modules/cjs/loader:996:19)
           at require (node:internal/modules/cjs/helpers:92:18)
           at Object.<anonymous> (/usr/src/app/node_modules/argon2/argon2.js:9:56)
           at Module._compile (node:internal/modules/cjs/loader:1092:14)
           at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
           at Module.load (node:internal/modules/cjs/loader:972:32)
           at Function.Module._load (node:internal/modules/cjs/loader:813:14) {
         code: 'ERR_DLOPEN_FAILED'
       }
       node:internal/modules/cjs/loader:1151
         return process.dlopen(module, path.toNamespacedPath(filename));
                        ^
       Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /usr/src/app/node_modules/argon2/lib/binding/napi-v3/argon2.node)
           at Object.Module._extensions..node (node:internal/modules/cjs/loader:1151:18)
           at Module.load (node:internal/modules/cjs/loader:972:32)
           at Function.Module._load (node:internal/modules/cjs/loader:813:14)
           at Module.require (node:internal/modules/cjs/loader:996:19)
           at require (node:internal/modules/cjs/helpers:92:18)
           at Object.<anonymous> (/usr/src/app/node_modules/argon2/argon2.js:9:56)
           at Module._compile (node:internal/modules/cjs/loader:1092:14)
           at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
           at Module.load (node:internal/modules/cjs/loader:972:32)
           at Function.Module._load (node:internal/modules/cjs/loader:813:14) {
         code: 'ERR_DLOPEN_FAILED'
       }
=====> end api web container output
2021/07/29 11:46:47 exit status 1
2021/07/29 11:46:48 exit status 1
```

This is strange because I'm not even using native modules in my application. It's just a graphql express server.

**Comment by VoltrexMaster** [comment] 2021-08-30 14:31
Not sure if this is an error caused by the runtime itself or your docker container requiring the `glibc` lib (?), I suggest trying to reinstall the Node.js runtime and try again.

**Comment by japrozs** [comment] 2021-08-30 14:36
> Not sure if this is an error caused by the runtime itself or your docker container requiring the `glibc` lib (?), I suggest trying to reinstall the Node.js runtime and try again.

I tried using `FROM node:latest` instead of `FROM node:14` and it worked!

**Comment by VoltrexMaster** [comment] 2021-08-30 14:39
> > Not sure if this is an error caused by the runtime itself or your docker container requiring the `glibc` lib (?), I suggest trying to reinstall the Node.js runtime and try again.
> I tried using `FROM node:latest` instead of `FROM node:14` and it worked!

Good, it seems like your issue is already resolved; you can close this now 🎉

**Closed** 2021-08-31 02:21 UTC
