### ISSUE TITLE
Missing permission to kill my own child process (EPERM)

### ISSUE THREAD

**Issue by sjkummer** [nodejs/help#2549] opened 2020-03-25 16:37 UTC
* **Node.js Version**: 12
* **OS**: macOS
* **Scope (install, code, runtime, meta, other?)**: code
* **Module (and version) (if relevant)**: ChildProcess

A child process spawned using the `sudo` command cannot be killed within node:
```js
            const cmd = 'sudo';
            const args: string[] = [
                '-S',
                'tcpdump',
            ];
            
            const childProcess = spawn(cmd, args);
            
            childProcess.kill(); // throws Error: kill EPERM
```

**Important:** 
The error is even thrown if the sudo password is newer passed to stdin and the child process therefore never reached any further privileges ...

**Comment by gireeshpunathil** [comment] 2020-11-06 09:24
able to repro without `node`:

terminal 1:
```
#sudo -S tcpdump
Password:
```

terminal 2:

```
#ps -ef | grep sudo
    0  1630 15608   0  2:49PM ttys001    0:00.15 sudo -S tcpdump
  501  1672 20959   0  2:52PM ttys002    0:00.03 grep sudo

#kill -9 1630
-bash: kill: (1630) - Operation not permitted
```

so looks like this is expected behavior, in mac. (did not observe this in linux though)

hope this helps.

**Comment by gireeshpunathil** [comment] 2020-12-09 06:11
closing as answered, pls re-open if there is still issue with it

**Closed by gireeshpunathil** 2020-12-09 06:11 UTC
