### ISSUE TITLE
How can I detect the file was deleted during the writing with fs.creaeteWriteStream write()?

### ISSUE THREAD

**Issue by tommyZZM** [nodejs/help#2092] opened 2019-08-01 02:40 UTC
* **Node.js Version**: v10.16.1
* **OS**: macOS 10.14.5
* **Scope (install, code, runtime, meta, other?)**: code
* **Module (and version) (if relevant)**: fs

Step to reproduce the issue.

1) create a writeStream, and you will got a file in the directory
```
# terminal
node
const fs = require('fs');
const ws = fs.createWriteStream('./test', { flags: 'a' })
```
![image1](https://i.loli.net/2019/08/01/5d4249ff1ddf429204.png)

2) then we can write some thing to the file
```
ws.write('123\n');
ws.write('123\n');
ws.write('123\n');
```

3) **MOVE the file** to trash and **DELETE the file**
![image2](https://i.loli.net/2019/08/01/5d4250464adba93105.png) 

4) continue call write in the code.
```
fs.existSync('./test'); // false
ws.write('123\n'); // true
ws.write('123\n'); // true
ws.write('123\n'); // true
```

The write stream still call write successfully. even the file already doesn't exist anymore. 

and the file would never recreate.

How can I detect the file was deleted during the writing with a write stream?

Should fs.createReadStream raises an error after the target file is deleted?

**Comment by Hakerh400** [comment] 2019-08-01 17:48
See https://github.com/nodejs/help/issues/1988

**Comment by slashd0t** [comment] 2019-11-12 11:16
Hi @Hakerh400 , were you able to re-create the deleted file? we have the same issue too.

**Comment by Hakerh400** [comment] 2019-11-13 07:17
@slashd0t Yes, but, as said in https://github.com/nodejs/help/issues/1988#issuecomment-503369523, it is working as intended. Since it is not a bug, it is not going to be fixed by Node.js team.

**Comment by tniessen** [comment] 2019-11-15 03:01
This behavior is not specific to Node.js, it depends on your operating system. All modern operating systems have separate mechanisms for open file descriptors and inodes / file system entries. If you delete a file, its inode / file system entry is removed from the file system, but the kernel won't close open file descriptors immediately. You can keep reading from files and keep writing to them, even if they appear to be deleted. When all file descriptors are closed, the kernel usually disposes of the file, making it inaccessible.

You can detect whether the file was deleted using the `fs.access` API. Streams should not throw as long as the file descriptor is open, and as I said above, that depends on the operating system, not on Node.js.

**Comment by gireeshpunathil** [comment] 2019-12-20 10:28
@tommyZZM - are you good with the explanations provided by @Hakerh400 and @tniessen ? are we good to close this?

**Closed** 2019-12-23 01:44 UTC
Labels: question
