### ISSUE TITLE
> > i have this problem too! i do all what you say but it still no working

### ISSUE THREAD

**Issue by eryycr** [nodejs/help#2947] opened 2020-08-29 13:59 UTC
> > Hello,
> > I'm having the same problem as stated above. When type {node index.js } I get the error below, I tried number of solutions ie uninstalled node and npm then reinstalled then back separately. I'm still getting the same error, help needed.
> > The error:
> > ```
> > interactive-SVG-image git:(master) ✗ node index.js
> > internal/modules/cjs/loader.js:983
> >  throw err;
> >  ^
> > 
> > Error: Cannot find module '/Users/lish/code/JavaScript_projects/interactive-SVG-image/index.js'
> >    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
> >    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
> >    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
> >    at internal/main/run_main_module.js:18:47 {
> >  code: 'MODULE_NOT_FOUND',
> >  requireStack: []
> > }
> > ```
> 
> I do have the same issue .I tried many solutions ,I am feeling frustrated to solve this 🤣

yes i Fix it

1. `npm cache clean --force`

2. ### delete **node_modules** _folder_

3. ### delete **package-lock.json** _file_

4. `npm install`

_Originally posted by @micstudent in https://github.com/nodejs/help/issues/2644#issuecomment-663993489_

**Comment by PoojaDurgad** [comment] 2020-12-17 09:32
duplicate of https://github.com/nodejs/help/issues/2644

**Comment by PoojaDurgad** [comment] 2021-03-29 05:48
inactive issue

**Closed by PoojaDurgad** 2021-03-29 05:48 UTC
