### ISSUE TITLE
nodemon is not getting installed

### ISSUE THREAD

**Issue by tejashvibari27** [nodejs/help#2857] opened 2020-07-17 16:48 UTC
* **Node.js Version**: v12.18.2
* **OS**:  Windows 8.1 pro
* **Scope (install, code, runtime, meta, other?)**: install
* **Module (and version) (if relevant)**:

nodemon is not getting installed with npm and also with yarn

![Untitled6](https://user-images.githubusercontent.com/55012632/87810969-7d7b8100-c87b-11ea-9144-024b40707f1d.jpg)

**Comment by bnoordhuis** [comment] 2020-07-20 08:10
Closing as a duplicate of #2853.

**Closed by bnoordhuis** 2020-07-20 08:10 UTC
