### ISSUE TITLE
Triggering parallel of 1k HTTP requests would get stuck

### ISSUE THREAD

**Issue by riston** [nodejs/help#2419] opened 2020-01-15 22:40 UTC
* **Node.js Version**: 10.x
* **OS**: Linux, OS X
* **Scope (install, code, runtime, meta, other?)**: runtime
* **Module (and version) (if relevant)**: HTTP

The question is what is actually happening when you trigger 1k-2k outgoing HTTP requests? I see that it would resolve all the connections easily with 500 connections but moving up towards there seems to cause problems. Tested with local server + example Google and other mock servers.

So with some servers I did receive `reason: read ECONNRESET` which is fine the server couldn't handle the request and throw error. In 1k-2k request range the program would just hang. When you check the open connections with `lsof -r 2 -i -a` you could see that there are some X amount of connections that keep hanging there `0t0  TCP 192.168.0.20:54831->lk-in-f100.1e100.net:https (ESTABLISHED)`. When you add timeout setting to requests these would probably end up with timeout error, but why otherwise the connection is kept up forever and the main program would end up in some limbo state?

Example code:
```ts
import fetch from 'node-fetch';

(async () => {
  const promises = Array(1000).fill(1).map(async (_value, index) => {
    const url = 'https://google.com';
    const response = await fetch(url, {
      // timeout: 15e3,
      // headers: { Connection: 'keep-alive' }
    });
    if (response.statusText !== 'OK') {
      console.log('No ok received', index);
    }
    return response;
  })

  try {
    await Promise.all(promises);
  } catch (e) {
    console.error(e);
  }
  console.log('Done');
})();

**Comment by gireeshpunathil** [comment] 2022-02-08 05:08
@riston - is this still an issue? there could be several root causes:
 - less resources (sockets, memory) so some are queuing up behind others
 - the remote server may be slowing / denying requests
 - the test framework may be slowing down things

**Comment by gireeshpunathil** [comment] 2022-02-27 12:22
closing as answered, pls reopen if there is anything outstanding.

**Closed by gireeshpunathil** 2022-02-27 12:22 UTC
