### ISSUE TITLE
Request with cert and key fails with 'certificate has expired' but same works with CURL

### ISSUE THREAD

**Issue by pnsvinodkumar** [nodejs/help#2479] opened 2020-02-21 03:03 UTC
I have spent days googling the issue I suffer with the error "certificate has expired", when I try to authenticate with a server with "cert" and "key" using https.request node standard module..
but the thing is, I use exactly the same pair of cert/key with curl and python's requests package too.. which would work just fine on the same server/endpoint
would be of great help if someone could throw some light / pointers / hints...

NodeJS: 10.x
OS: Win

**Comment by bnoordhuis** [comment] 2020-02-21 08:17
I'm moving this to nodejs/help. If you can post steps to reproduce and it turns out it's an issue with Node.js itself, I'll move it back.

**Comment by gireeshpunathil** [comment] 2021-12-19 12:59
@pnsvinodkumar - is this still outstanding?

**Comment by gireeshpunathil** [comment] 2022-01-31 12:51
closing as inactive, pls reopen if this is outstanding, and when you can provide details.

**Closed by gireeshpunathil** 2022-01-31 12:51 UTC
