### ISSUE TITLE
Can't define an undefined variable because it was already declared? 🤔

### ISSUE THREAD

**Issue by Chuckytuh** [nodejs/help#3227] opened 2021-02-16 02:00 UTC
* **Node.js Version**: v12.19.0; v14.7.0
* **OS**:
* **Scope (install, code, runtime, meta, other?)**: runtime
* **Module (and version) (if relevant)**: n/a

I'm a bit confused by the following snippet. That problem (?) occurs on nodejs 12 as well, but, the same snippet does not result on the same error on Chrome, for example. Can someone please explain to me why and if this isn't a bug?

node repl:

```bash
Welcome to Node.js v14.7.0.
Type ".help" for more information.
> let x = Object.create()
Uncaught TypeError: Object prototype may only be an Object or null: undefined
    at Function.create (<anonymous>)
> x
Uncaught ReferenceError: x is not defined
> let x = Object.create({})
Uncaught SyntaxError: Identifier 'x' has already been declared
>
```

**Comment by dark-magic** [comment] 2021-02-20 11:46
Have the same thing happening with node v14 lts. i guess its because of the error at the first assignment. but its interesting behaviour for sure.

**Comment by Sylack-lab** [comment] 2021-03-04 08:25
I will try replicating the behaviour.

**Comment by Sylack-lab** [comment] 2021-03-04 08:29
![image](https://user-images.githubusercontent.com/48862659/109933454-b877db00-7ccb-11eb-90c7-e2116650b2b6.png)

NodeJS cant set variables if they error. They are kept as undefined. I suggest using 

 let x = {} to make objects instead of Object.create if you dont know how it works.
 
 Object.create makes an object with an existing object. Aka:
 
 ```
 let obj = {
 a:true
 }
 
 let b = Object.create(obj)
 b.a = true
 
 ```
 
 A bit like typescript interfaces of some sort.

**Comment by devsnek** [comment] 2021-03-04 12:35
Duplicate of #8309

**Closed** 2021-03-04 12:37 UTC
