### ISSUE TITLE
Npm is not working give error every time i run

### ISSUE THREAD

**Issue by raja257** [nodejs/help#2569] opened 2020-04-01 07:25 UTC
Creating a new React app in C:\Users\ML\reactApp\my-app-project\my-app.

Installing packages. This might take a couple of minutes.
Installing react, react-dom, and react-scripts with cra-template...

npm ERR! code ECONNREFUSED
npm ERR! errno ECONNREFUSED
npm ERR! FetchError: request to https://registry.npmjs.org/react-dom failed, reason: connect ECONNREFUSED 127.0.0.1:8080npm ERR!     at ClientRequest.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-fetch-npm\src\index.js:68:14)
npm ERR!     at ClientRequest.emit (events.js:315:20)
npm ERR!     at onerror (C:\Program Files\nodejs\node_modules\npm\node_modules\agent-base\index.js:101:9)
npm ERR!     at callbackError (C:\Program Files\nodejs\node_modules\npm\node_modules\agent-base\index.js:123:5)
npm ERR!     at processTicksAndRejections (internal/process/task_queues.js:97:5)
npm ERR!  FetchError: request to https://registry.npmjs.org/react-dom failed, reason: connect ECONNREFUSED 127.0.0.1:8080
npm ERR!     at ClientRequest.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-fetch-npm\src\index.js:68:14)
npm ERR!     at ClientRequest.emit (events.js:315:20)
npm ERR!     at onerror (C:\Program Files\nodejs\node_modules\npm\node_modules\agent-base\index.js:101:9)
npm ERR!     at callbackError (C:\Program Files\nodejs\node_modules\npm\node_modules\agent-base\index.js:123:5)
npm ERR!     at processTicksAndRejections (internal/process/task_queues.js:97:5) {
npm ERR!   message: 'request to https://registry.npmjs.org/react-dom failed, reason: connect ECONNREFUSED 127.0.0.1:8080',
npm ERR!   type: 'system',
npm ERR!   errno: 'ECONNREFUSED',
npm ERR!   code: 'ECONNREFUSED',
npm ERR!   stack: 'FetchError: request to https://registry.npmjs.org/react-dom failed, reason: connect ECONNREFUSED 127.0.0.1:8080\n' +
npm ERR!     '    at ClientRequest.<anonymous> (C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-fetch-npm\\src\\index.js:68:14)\n' +
npm ERR!     '    at ClientRequest.emit (events.js:315:20)\n' +
npm ERR!     '    at onerror (C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\agent-base\\index.js:101:9)\n' +
npm ERR!     '    at callbackError (C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\agent-base\\index.js:123:5)\n' +
npm ERR!     '    at processTicksAndRejections (internal/process/task_queues.js:97:5)'
npm ERR! }
npm ERR!
npm ERR! If you are behind a proxy, please make sure that the
npm ERR! 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ML\AppData\Roaming\npm-cache\_logs\2020-03-31T17_16_44_476Z-debug.log

Aborting installation.
  npm install --save --save-exact --loglevel error react react-dom react-scripts cra-template has failed.

Deleting generated file... package.json
Deleting my-app/ from C:\Users\ML\reactApp\my-app-project
Done.

**Comment by PoojaDurgad** [comment] 2020-10-01 12:07
>npm ERR! errno ECONNREFUSED
npm ERR! FetchError: request to https://registry.npmjs.org/react-dom failed, reason: connect ECONNREFUSED 127.0.0.1:8080npm
npm ERR! If you are behind a proxy, please make sure that the
npm ERR! 'proxy' config is set properly. See: 'npm help config'

@raja257 - did you run npm install before creating react . for me with your issue root cause is may be because a proxy is being used on your network.try these following commands.
`npm config set proxy null`
`npm config set https-proxy null`
`npm config set registry http://registry.npmjs.org/`
and then execute `npm install -g react-native-cli`
This will set the new configurations and allow you to access the internet with npm. hope it may help.

**Comment by raja257** [comment] 2020-10-01 12:14
Thanks

**Comment by PoojaDurgad** [comment] 2020-11-09 06:30
closing as answered. please feel free to reopen if it is still an issue.

**Closed by PoojaDurgad** 2020-11-09 06:30 UTC

**Comment by mrshabbarkhan** [comment] 2024-03-17 19:48
thank you mam@poojaDurgad
