### ISSUE TITLE
Date.getTimezoneOffset() produces wrong result on Mac OS

### ISSUE THREAD

**Issue by CyberCookie** [nodejs/help#4321] opened 2024-01-04 23:08 UTC
### Details

(new Date(0)).getTimezoneOffset() produces different output on different environments.

Correct output (`-180`) is produced on:
Mac OS 14.2 Chrome 119.0
Linux 6.5 Fedora 38 NodeJS REPL / Chrome 119.0
Windows 11 NodeJS REPL / Chrome 119.0

Incorrect output (`-120`) is produced on:
Mac OS 14.2 NodeJS REPL

<img width="759" alt="image" src="https://github.com/nodejs/help/assets/9907516/47762dab-f286-4e63-8cc2-f26e0386c67e">

### Node.js version

v20.9.0

### Example code

(new Date(0)).getTimezoneOffset()

### Operating system

Mac OS 14.2

### Scope

runtime

### Module and version

Not applicable.

**Comment by preveen-stack** [comment] 2024-01-08 05:10
I am on 14.2.1 on macos Intel
I am not able to reproduce the above with node 21.5.0

**Comment by CyberCookie** [comment] 2024-01-08 09:41
@preveen-stack 
You should probably set another timezone to reproduce it
My timezone is `Eastern European Standard Time`

**Comment by jeremylea** [comment] 2024-05-11 18:12
I'm upgrading some old FreeBSD compute hosts and seeing a similar issue.  I'm in PDT and on all platforms `Intl.DateTimeFormat().resolvedOptions().timeZone=='America/Los_Angeles'` and they report the correct local time via `date`.   On Windows with node 20.12.2, `new Date().getTimezoneOffset()==420` and the same on FreeBSD 12.2-RELEASE-p7 with node 16.10.0 (what the old hosts are running).  On FreeBSD 14.0-RELEASE-p6 with node 20.12.2 `new Date().getTimezoneOffset()==540`...  Interestingly `setting process.env.TZ` (which is undefined) explicitly to `'America/Los_Angeles'` results in the correct answer (420) on FreeBSD 14, even though this is what it already reports as the time zone.

**Comment by RedYetiDev** [comment] 2024-07-15 22:21
Hi! The date data for Node.js is gotten directly from the ICU. Different versions (including Chrome vs Node) will have different outputs. Typically, the latest version of Node.js will have the newest ICU information.

Because this doesn't seem like a bug, but rather a side-effect of the ICU, I'm closing this issue. If you disagree, feel free to ping me and tell me why.

**Closed by RedYetiDev** 2024-07-15 22:21 UTC
Labels: question, macos
