### ISSUE TITLE
N-API Weird Behavior 

### ISSUE THREAD

**Issue by matthew-plusprogramming** [nodejs/help#2438] opened 2020-01-24 01:40 UTC
* **Node.js Version**: v13.6.0
* **OS**: OSX 10.15.2
* **Scope**: code
* **Module**: N-API
Hello,

I observed some weird behavior when using n-api with electronjs. What I noticed is that the following code works:
```cpp
napi_value toreturn;

napi_value *args;
size_t argc = 1;
size_t pathLength;

size_t bufSize(128);
char buf[bufSize];

napi_get_cb_info(env, info, &argc, args, NULL, NULL);
napi_create_double(env, argc, &toreturn);
napi_get_value_string_utf8(env, args[0], buf, bufSize, &pathLength);
```
while the following code causes my program to crash unexpectadly:
```cpp
napi_value *args;
size_t argc = 1;
size_t pathLength;

size_t bufSize(128);
char buf[bufSize];

napi_get_cb_info(env, info, &argc, args, NULL, NULL);
napi_get_value_string_utf8(env, args[0], buf, bufSize, &pathLength);
```

I realized this problem because the code directly above kept crashing and after adding that call to napi_create_double, it for some reason stopped crashing. Anyone know why this might be the case?

**Comment by addaleax** [comment] 2020-01-24 13:30
`napi_value *args` should probably be `napi_value args[1];` – in the former case, `args` is an uninitialized pointer and can refer to any memory, including invalid addresses, which is likely the cause of the crash here.

The `napi_create_double` call is probably not that important, but the fact that a new variable is added along with it (`toreturn`) changes the layout of the variables on the stack, and therefore the contents of `args`, which happens to make it point to valid memory (but is of course still a bug).

**Comment by battletag13** [comment] 2020-01-24 13:38
I actually tweaked the code to now look like this:
```cpp
  napi_value toreturn;

  napi_value args[1];
  size_t argc = 1;
  size_t pathLength;

  size_t bufSize(128);
  char *buf = new char[bufSize];

  napi_get_cb_info(env, info, &argc, args, NULL, NULL);
  napi_get_value_string_utf8(env, args[0], buf, bufSize, &pathLength);
  napi_create_string_utf8(env, buf, bufSize, &toreturn);
  delete[] buf;
```
The code still exhibits similar properties. If I get rid of any of the three function calls (and leave two of them) the code will crash, but as long as I leave all three there it works and all operations are normal.

**Comment by addaleax** [comment] 2020-01-24 13:43
Can you maybe share a full reproduction in that case?

That being said, you can’t really get rid of the `napi_get_cb_info()` call because the subsequent calls depend on it.

**Comment by gireeshpunathil** [comment] 2020-11-09 11:23
@matthew-plusprogramming - is this still an issue?

**Comment by matthew-plusprogramming** [comment] 2020-11-12 03:09
Not sure if it's still an issue, I've since moved away from n-api in favor of using web assembly to get my project to work, but the issue seems to be a weird behavior rather than something breaking the API.

**Comment by gireeshpunathil** [comment] 2020-12-23 11:27
ok, I will close the issue now, and we can re-open if necessary

**Closed by gireeshpunathil** 2020-12-23 11:27 UTC
