### ISSUE TITLE
npm does not support Node.js v10.16.3

### ISSUE THREAD

**Issue by seanlawrenz** [nodejs/help#2134] opened 2019-08-21 14:18 UTC
* **Node.js Version**: 10.16.3 npm 6.9.0
* **OS**: Mac Os 10.14.2
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:

I know this has been kicked around here and the typical answer is to uninstall node or to upgrade npm. This problem still stays. The issues is the version of node that I'm using is 10.16.3 and it's npm version is 6.9.0.  Which means every time I upgrade this issue reappears, because they are the versions that are supposed to go together. 

Not sure what to do or if I should just live with it but please DO NOT JUST MARK AS DUPLICATE. I have tried all the solutions and the issue is that node does not recognize that the correct version of npm is installed.

**Comment by izkrivera** [comment] 2019-08-23 16:51
Same here. The NPM version bundled with the node installer does not recognize the version of node installed.

**Comment by akberkhan2121** [comment] 2019-08-26 21:58
I'm not sure if I have the same problem or not, but when I installed Node.js, and I run node -v , I get a "command not found"; not sure if it comes from the same issue mentioned here

**Comment by BritoMatheus** [comment] 2019-09-04 20:19
Same problem:

npm WARN npm npm does not support Node.js v10.16.3
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8.
npm WARN npm You can find the latest version at https://nodejs.org/

**Comment by ColdHarborDevelopmentGroup** [comment] 2019-09-04 20:23
can confirm - same issue here.

**Comment by afzalakhtar** [comment] 2019-09-08 14:51
Same problem... 

But I got solution when run command "npm uninstall -g npm"

The command above deleted the older orsion of npm from my computer and new one updated automatically

**Comment by jgiordanoGG** [comment] 2019-09-10 14:48
I've run into this after upgrading yesterday. I tried using @afzalakhtar 's suggestion ("npm uninstall -g npm") but it didn't automatically install a new one. I then tried using "sudo npm install -g npm@latest" to get npm back though it installed 6.11.3. Even with this new version I'm still getting the error 🤷🏽‍♂️

**Comment by khanks** [comment] 2019-09-19 21:06
If I created tools like this on my business website, my customers would flood me with phone calls and then drop me if I didn't fix it. This is why I never jump on the bandwagon of the "latest new thing". Unfortunately, I installed this POS because another tool told me to. Lesson learned: if the tool can't use stable technology, then don't buy it.

**Comment by tpwatson** [comment] 2019-10-13 01:08
Having this problem too..

**Comment by tpwatson** [comment] 2019-10-13 01:10
> Same problem...
> 
> But I got solution when run command "npm uninstall -g npm"
> 
> The command above deleted the older orsion of npm from my computer and new one updated automatically

When i try that command it still tells me 

> npm WARN npm npm does not support Node.js v10.16.3

The npm -v version says 5.4.2 

Not sure why npm version 6.9.0 isn't installing with the nodejs 10.16.3 installer

**Comment by tniessen** [comment] 2019-10-13 06:36
I cannot reproduce the problem. How did you install Node.js? Could you post the output of the following commands?

1. `npm -v`
2. `node -v`
3. Windows only: `where npm`
4. Non-Windows only: `which npm`

If you are seeing an outdated npm version despite installing a newer node release, you might not have set up your path correctly.

**Comment by tniessen** [comment] 2019-10-14 03:59
@khanks For your information, I moderated your comment. I am not sure what you were trying to achieve, but insulting us or our work is not just unprofessional, it also violates our Code of Conduct. I will not sugarcoat this because I have seen that you have left similarly condescending comments in other open-source projects.

You openly insult the work of thousands of people online. People who are not being paid for their work, and work that you are contributing absolutely nothing to. Work that is appreciated by tens of thousands of people and hundreds of companies.

I don't know why you think you have the right to insult all of that, but it is unacceptable by our standards.

**Comment by khanks** [comment] 2019-10-14 16:20
You need to chill out dude. I was simply making a statement about things
that need to be fixed,  it wasn't meant to be insulting

**Comment by seanlawrenz** [comment] 2019-10-17 20:00
After picking on this for a while, I found out that there was a particular package that was causing this issue. We had a part of the build process that will copy the contents of the dist folder and put that into another file. The package that did that was https://github.com/mysticatea/cpx cpx. 

We I deprecated that part of the build process and removed cpx this issue disappeared. I don't know if this is part of the npm wheelhouse or not. Let me know if you want any more information.

**Comment by khanks** [comment] 2019-10-17 20:12
Thanks for your work. I don't have that particular package in my code, but
I appreciate your effort. Hello hello hey

**Comment by txm** [comment] 2019-10-21 20:35
```
$ node -v
v10.16.3
```

```
$ npm -v
6.9.0
```

```
$ cd myapp && ./node_modules/.bin/npm -v
3.5.4
```

snippet after `npm i`

```
npm ERR! node v10.16.3
npm ERR! npm  v3.5.4
npm ERR! code MODULE_NOT_FOUND
```

**Comment by technowar** [comment] 2019-10-22 04:31
@txm do you have `npm` installed inside `myapp`? Perhaps you ran `npm install npm` instead of `npm install -g npm`?

**Comment by txm** [comment] 2019-10-22 06:47
@technowar thanks. I think you are right. Or at least a dependency is and I’m putting my money on an ember generator triggered by ‘npm I’.

**Comment by tniessen** [comment] 2019-10-22 12:33
```
$ cd myapp && ./node_modules/.bin/npm -v
3.5.4
```

Yes, it looks like you have an outdated version in your local `node_modules` folder. You should still be able to use the global `npm` instead.

**Comment by txm** [comment] 2019-10-22 12:42
@tniessen and that's the problem, a dependency is installing an old and incompatible version of npm and trying to use it.  My money is on `ember-cli-release`.

**Comment by brodybits** [comment] 2019-10-22 12:57
FYI you can do npm ls to find out why you get the old npm version. Or maybe
try the npm-why utility.
-- 
Sent from my mobile

**Comment by bijoythomas** [comment] 2019-12-17 02:15
I'm running into the same issue as well. Honestly, I haven't come across this issue before. Just the node upgrade from `8.11.4` to `10.16.3` seems to introduced this issue. Details below:
```
node -v
v10.16.3
npm -v
6.9.0
which npm
/Users/whatever/.nvm/versions/node/v10.16.3/bin/npm
npm i -g ramda-destruct
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
/Users/whatever/.nvm/versions/node/v8.11.4/bin/ramda-destruct -> /Users/whatever/.nvm/versions/node/v8.11.4/lib/node_modules/ramda-destruct/bin/cli
+ ramda-destruct@2.0.1
updated 1 package in 4.523s
```

Why is npm installing a package in the older node version? BTW, been using NVM (with bash) for a while now and I love it! I'm sure I'm doing something wrong. Any ideas?

**Comment by jeme** [comment] 2020-02-26 13:56
Ran into the same warning today with NodeJS vs 12.16.1 and I think that in the very least, the warning that NPM spits out could use an update as it is no help at all in this particular situation (if that has not happened yet).

```
F:\PLAY\TypeAhead>npm install npm@latest -g
npm WARN npm npm does not support Node.js v12.16.1
1) npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 6, 8, 9, 10, 11.
2) npm WARN npm You can find the latest version at https://nodejs.org/
```

1. The user will say, but I just did, and there is no never version of Node.
2. The link just leads us to the download site where we just got the newest version from.

Since it states the version of node (v12) and it states the versions it supports (6,8,9,10 and 11) - Then i would assume that it shouldn't be that hard to detect that the version of Node is actually above what the current NPM supports, and then give better instructions to the user, e.g. that the user should try and Update NPM with `npm install npm@latest -g` or whatever the appropriate action might be...

Then there ofc. is the question as to "Why is the newest version of NPM not installed with the newest version of the node installer (in my case the windows installer)" - but making the above change would at least remedy the situation rather than leaving the user without any meaningful help.

(I would not mind attempting to make a PR if someone can point me in the right direction).

**Comment by tniessen** [comment] 2020-02-26 17:01
@jeme

> the warning that NPM spits out could use an update as it is no help at all in this particular situation

npm is a separate product, please report this to them, or contribute [to their code](https://github.com/npm/cli). For our users' convenience, we include a tested version with official Node.js releases, but we do not maintain npm. Manual installations, upgrades, downgrades, and removals can lead to scenarios where the versions do not match.

**Comment by jeme** [comment] 2020-02-27 13:12
@tniessen 

Fair enough, it can be a bit hard to see from the outside, node and npm seems so intertwined that one just assumes that there is a overlap in the team behind.

Anyways, after some further investigation it looks like NPM won't report this warning in the future under this circumstance as it looks like they have moved to a SemVer range check that just allows >= 9.3.0, which should cover basically any future versions of node.

So it turns out that it's not worth pursuing at this time.

**Comment by tniessen** [comment] 2020-02-29 16:50
Thank you for looking this up, @jeme. Seems that this was indeed fixed in npm 6.14.0.

So to anyone reading this thread:
1. Make sure your npm version is not older than the one being shipped with your Node.js version, or at least 6.14.0
2. Make sure you are not using an unmaintained or outdated module that installs an outdated npm version locally.

**Closed by tniessen** 2020-02-29 16:50 UTC
Labels: question

**Comment by danielturus** [comment] 2020-10-07 07:39
How I fixed this issue on Windows 10:
1. Find where npm is located by typing in terminal (git bash) `where npm` (it should be somewhere like C:\Users\[Username]\AppData\Roaming\npm )
2. Remove the folders `npm` and `npm_cache`

Maybe it will help some of you.

**Comment by ccwright90** [comment] 2022-07-29 14:36
@danielturus Thanks mate. You are a life saver. For anyone else looking at this, this is what you need to do:

Find where npm is located by typing in terminal (git bash) where npm (it should be somewhere like C:\Users[Username]\AppData\Roaming\npm )
Remove the folders npm and npm_cache
