### ISSUE TITLE
undefined symbol: node_module_register

### ISSUE THREAD

**Issue by eskejpo** [nodejs/help#1246] opened 2018-05-01 06:09 UTC
node v10
debian x64 
any module like lame... any that uses .node bindings

My problem is i compiled node as libnode.so.61, started process everything works but as soon as i load any module that uses .node it crashes=> node_modules/lame/build/Release/bindings.node: undefined symbol: node_module_register

**Comment by bnoordhuis** [comment] 2018-05-01 11:16
Probably because symbol lookups don't work "sideways" unless you `dlopen("libnode.so.61", RTLD_GLOBAL)`; "sideways" because conceptually your binary is in the middle, with libnode off to one side and the add-on to the other.

I don't know if there is a linux ld(1) equivalent of `RTLD_GLOBAL`.  On macos, it's `-flat_namespace`.

**Comment by eskejpo** [comment] 2018-05-01 19:36
Thank you for your response, i am extremely unexperienced regarding c++ and stuff around it. So what is the solution, what to do? RTLD_GLOBAL works on linux too, but no idea what to do afterwards.

**Comment by bnoordhuis** [comment] 2018-05-01 20:04
What I mean is that I don't know of a Linux linker flag that does at link time what `RTLD_GLOBAL` does at runtime.

I assume you want to embed Node.js in another program?  How is that program built, with what compiler and linker flags?

Sanity check: what does `nm -T libnode.so.61 | grep node_module_register` print?

**Comment by eskejpo** [comment] 2018-05-02 10:44
Well, first of all thanks for the response again, and also i missed some points because. I am compiling nodejs embed project as shared library that loads libnode.so.61, that shared lib gets loaded by app. If it matters then that app is Teamspeak client, which loads plugin (my app), (which loads libnode?). It gets compiled with no problem, embed even works and can communicate between runtime and c++.

root@vmi158387:~# nm -T /usr/lib/libnode.so.61 | grep node_module_register
nm: invalid option -- 'T'

root@vmi158387:~# nm -t /usr/lib/libnode.so.61 | grep node_module_register
nm: /usr/lib/libnode.so.61: invalid radix

compile.sh
#!/bin/bash

socka="/usr/lib/libcpplocate.so.1 libbass.so libbass_aac.so /usr/lib/libnode.so.61"
libky="-Iinclude -I../include/ -I/home/nodejs/embed/node-embed/externals/node -I/home/nodejs/embed/node-embed/externals/node/src -I/home/nodejs/embed/node-embed/externals/node/deps/v8/include -I/home/nodejs/embed/cpplocate/build/source/cpplocate/include -I/home/nodejs/embed/cpplocate/source/cpplocate/include"

g++ -shared -O2 -Wall -DLINUX -fPIC $socka -lpthread pluginv2.cpp $libky -std=gnu++1y -o /home/nodejs/ts/client/TeamSpeak3-Client-linux_amd64/plugins/asd.so 

Also when i embed it as simple app, module loading works with no problem, but when teamspeak loads it these problems happen. It may also be caused by something inside app?

Thanks again for giant help.

**Comment by eskejpo** [comment] 2018-05-02 11:48
Hi, i have posted the dump with nm -g up. So you mean compiling node with --fully-static (=>libnode.a) and then linking it with arguments you posted. 
I have also read this https://github.com/nodejs/node/wiki/Statically-linked-executable which says its also broken. But i will try it and we will see, i appreciate all your help.

**Comment by bnoordhuis** [comment] 2018-05-02 11:52
> So you mean compiling node with --fully-static

No, that's something different; `--fully-static` is for building a statically linked node executable.  What I mean is building libnode as a static library rather than a dynamic library.

**Comment by eskejpo** [comment] 2018-05-02 14:49
Hello, so i guess --enable-static? I did it, changed common.gypi so it includes -fPIC

```
#!/bin/bash

socka="/usr/lib/libcpplocate.so.1 libbass.so libbass_aac.so /usr/lib/libnode.so.61 -Wl,--whole-archive,/home/nodejs/embed/node-embed/externals/node/out/Release/obj.target/libnode.a -Wl,--no-whole-archive"
libky="-I../include/ -I/home/nodejs/embed/node-embed/externals/node -I/home/nodejs/embed/node-embed/externals/node/src -I/home/nodejs/embed/node-embed/externals/node/deps/v8/include -I/home/nodejs/embed/cpplocate/build/source/cpplocate/include -I/home/nodejs/embed/cpplocate/source/cpplocate/include"

g++ -shared -O2 -Wall -DLINUX -fPIC $socka -lpthread pluginv2.cpp -Iinclude $libky -std=gnu++1y -o /home/nodejs/ts/client/TeamSpeak3-Client-linux_amd64/plugins/asd.so 

```

added libnode.a (~200kb?), 

node_modules/lame/build/Release/bindings.node: undefined symbol: node_module_register
dang it

**Comment by bnoordhuis** [comment] 2018-05-03 12:25
You link in the shared library as well; I'd drop that.  Does `nm asd.so | grep node_module_register` print anything?  What about `nm -g`?

If the answers to both questions is 'yes', then I suspect teamspeak loads your plugin with `RTLD_LOCAL`, hiding its symbols from subsequently loaded shared objects.

**Comment by eskejpo** [comment] 2018-05-03 13:45
Thank you once again. 
`
root@vmi158387:/home/nodejs/ts/client/TeamSpeak3-Client-linux_amd64/plugins# nm asd.so | grep node_module_register
00000000000d16f0 T node_module_register
root@vmi158387:/home/nodejs/ts/client/TeamSpeak3-Client-linux_amd64/plugins# nm -g asd.so | grep node_module_register
00000000000d16f0 T node_module_register

`

To the second point, i made simple shared object, executable to test your point
testapp.cpp
`
#includes...
int lf();

int main(){
	lf();
	return 0;
}

`

sharedobject.cpp
`
#include "node_lib.h"
using namespace std;

int lf() {
	
	std::string program_name = "prog name";
	node::Initialize(program_name, {"-e", "console.log()"}, false);
	node::Evaluate(R"(
				setTimeout(function(){
					console.log("process")
					require("./embedapp.js")
				},0); 
                 )");

	while (node::ProcessEvents()) {

	}

	return 0;
}
`

same thing happens

**Comment by gireeshpunathil** [comment] 2018-06-15 12:14
I am unable to reproduce this issue with Node v10.x - probably there is a subtle difference in the way the main executable is built:
1. Build libnode.so.64 using ./configure --shared && make
2. build an executable with a main that links against libnode.so.64 . the linker flags are all obvious ones only - -ldl -lrt -lm 
3. built an addon using the steps as in the documentation
4. wrote a JS script that makes use of the addon
5. executed the main with the js script file as the argument.

with LD_DEBUG=all exported, I see the module is linked, loaded and invoked rightly.

```trace
     95099:     symbol=node_module_register;  lookup in file=./n [0]
     95099:     symbol=node_module_register;  lookup in file=/home/gireesh/foo/libnode.so.64 [0]
     95099:     binding file /home/gireesh/foo/libnode.so.64 [0] to /home/gireesh/foo/libnode.so.64 [0]: normal symbol `node_module_register'
```

The visible difference between us is in the main: you seem to be calling `node::Initialize` and `node::Evaluate` which I am not doing, instead call `Start` stright. I guess that should not make any difference, as the symbol in question sits in the shared library, not in the executable.

Can you export LD_DEBUG=all and see what error it throws up for the missing symbol?

**Comment by eskejpo** [comment] 2018-06-16 07:05
3139201:     13380:     object=/home/bot/client/node_modules/lame/build/Release/bindings.node [0]
3139203:     13380:      scope 1: /home/bot/client/node_modules/lame/build/Release/bindings.node /usr/lib/x86_64-linux-gnu/libstdc++.so.6 /lib/x86_64-linux-gnu/libm.so.6 /lib/x86_64-linux-gnu/libpthread.so.0 /lib/x86_64-linux-gnu/libc.so.6 /lib64/ld-linux-x86-64.so.2 /lib/x86_64-linux-gnu/libgcc_s.so.1
3139224:     13380:     calling init: /home/bot/client/node_modules/lame/build/Release/bindings.node
3139311:     13380:     symbol=node_module_register;  lookup in file=/home/bot/client/node_modules/lame/build/Release/bindings.node [0]
3139318:     13380:     /home/bot/client/node_modules/lame/build/Release/bindings.node: error: symbol lookup error: undefined symbol: node_module_register (fatal)
3139320:     13380:     calling fini: /home/bot/client/node_modules/lame/build/Release/bindings.node [0]
3139323:     13380:     file=/home/bot/client/node_modules/lame/build/Release/bindings.node [0];  destroying link map

I use node::Initialize from https://github.com/hpicgs/node-embed/ also tried other library. Why? I need some embed to communicate between c++ host, node env. Call functions, hook events. 
When its compiled into shared library which is loaded by some app (as an addon lets say) this happens. When i compile it as an executable it works.

**Comment by gireeshpunathil** [comment] 2018-07-31 08:26
ping @eskejpo

**Comment by eskejpo** [comment] 2018-08-01 09:44
@gireeshpunathil I forgot about this issue, thanks for your ping tho. 
I no longer have the command as i lost hope on it but from post above i deduct it was something like this

//edited it so it is more readable
socka="
/usr/lib/libcpplocate.so.1
/usr/lib/libnode.so.61 
"

libky="
-I../include/ 
-I/home/nodejs/embed/node-embed/externals/node 
-I/home/nodejs/embed/node-embed/externals/node/src 
-I/home/nodejs/embed/node-embed/externals/node/deps/v8/include 
-I/home/nodejs/embed/cpplocate/build/source/cpplocate/include 
-I/home/nodejs/embed/cpplocate/source/cpplocate/include
"
g++ -Wno-deprecated -std=c++17 -shared -O2 -Wall -DLINUX -fPIC $libky $socka -o sharedobject.so

g++ -Wno-deprecated -std=c++17 sharedobject.so -o executable.out

**Comment by gireeshpunathil** [comment] 2018-08-01 13:28
@eskejpo  - thanks, I guess this is not complete:

1. the last step: where is the main? you should have another driver file that contain main, right?
2. the last step: should have `-ldl -lrt -lm`

Assuming you are still interested in pursuing this, please try following these 2. Else let me know.

**Comment by gireeshpunathil** [comment] 2018-08-10 06:27
closing based on your last comment, please  let me know if you still have this outstanding.

**Closed by gireeshpunathil** 2018-08-10 06:27 UTC
