### ISSUE TITLE
String.prototype.replace() & String.prototype.replaceAll don't replace string properly

### ISSUE THREAD

**Issue by USERSATOSHI** [nodejs/help#3881] opened 2022-06-05 10:35 UTC
### Details

let's say, I have an object: `{ content : "$hi$" }`.
I converted this object to string using `Util.inspect()` and this returns `'{ content: \'$hi$\' }'`
then, I used String.prototype.replace to replace `'$hi$'` to ``` `$hi$` ``` via 
```js
const a = "$hi$";
const b = "`$hi$`";
const c = { content: "$hi$" };
inspect( c ).replace( `content: '${ a }'`, `content: ${ b }` )
```
and here the issue begins,
I expected the result to be ```{ content: `$hi$` }```
but instead, I got ```{ content: `$hi{  }```

I can't tell if i did a mistake or this is a bug

Below are the screenshots:
**Using QuokkaJs to display values on editor**
![image](https://user-images.githubusercontent.com/73595362/172046382-a62659cc-cb06-419d-b7f0-4b5f9d9b16d3.png)
**Running the file**
![image](https://user-images.githubusercontent.com/73595362/172046408-8c1e0f8d-bb22-49b4-a6d1-de0c40b377c5.png)

### Node.js version

17.9.0

### Example code

```js
const a = "$hi$";
const b = "`$hi$`";
const c = { content: "$hi$" };
const { inspect } = require( "util" );
console.log({ inspected: inspect(c) });
console.log( inspect( c ).replace( `content: '${ a }'`, `content: ${ b }` ) );
```

### Operating system

Microsoft Windows NT 10.0.22000.0 x64

### Scope

bug

### Module and version

Not applicable.

**Comment by VoltrexMaster** [comment] 2022-06-05 23:34
This is not a bug but rather intended behavior, the replacement value contains a writeback special identifier ($\`), this identifier is replaced with whatever that was behind the search string.

Since you're replacing the entirety of `content: '$hi$'` with

```txt
content: '`$hi$`'
```

If you look close enough, it includes the writeback identifier which is **$\`** after `$hi`, which gets replaced with `{ ` because it's the only thing left **behind** the search string which was `content: '$hi$'`.

Both of the `String.prototype.replace()` and `String.prototype.replaceAll()` methods inspect the replacement string and look for special identifiers to replace, which these identifiers start with the `$` sign.

Let's have a deeper look:

With regex, we can use the assigned number identifiers to access the groups of the matched regex result

```js
import { inspect } from 'node:util';

// The object we want to inspect.
const foo = { content: 'hello' };
// Inspect the object.
const bar = inspect(foo); // "{ content: 'hello' }"

// Now let's replace `content` and `hello` to something else using the number assigned identifiers we mentioned earlier.
bar.replace(
  // Use a regex to group both `content` and `hello`.
  /(content): '(hello)'/,
  // And replace with something else, notice that `$1` and `$2` in the replacement string is replaced with the values of the captured groups from the regex, which `$1` is `content` and `$2` is `hello` in this case.
  "$1ButReplaced: '$2 world'"
); // "{ contentButReplaced: 'hello world' }"
```

Now that we've looked at the number assigned identifiers indexed by the captured groups in the regex that can be used in the replacement string, now let's have a look at the writeback identifer:

```js
import { inspect } from 'node:util';

// The object we want to inspect.
const foo = { content: 'hello world' };
// Inspect the object.
const bar = inspect(foo); // "{ content: 'hello world' }"

// Now we can replace `hello world` with something else.
bar.replace(
  // Search for `'hello world'`.
  "'hello world'",
  // And replace it with whatever there was behind `'hello world'` (which is `{ content: ` in this case) using the writeback identifier which is $`, and write something after it if needed!
  '"$`, whoops! Now I\'ve taken it\'s place."'
); // `{ content: "{ content: , whoops! Now I've taken it's place" }`
```

If you're still confused with what happened in your case, here's what happens during the replacement:

1. Search for the search string which is `content: '$hi$'` in string `"{ content: '$hi$' }"`.
2. Once the search string is found, remember that `{ ` is what's behind the **search string**, assign it to the special writeback identifier  which is **$\`**.
3. Inspect the replacement string which is

```txt
content: '`$hi$`'
```

and look for special identifiers prefixed with `$`.
4. Found the special writeback identifier in the replacement string which is **$\`**, placed right after `$hi`, replace it with what was left behind the search string mentioned at point 2.
5. Now the replacement string is

```txt
content: `$hi{ }
```

after inspection.
7. Replace the found search string with the replacement string.
8. Now the replaced string is

```txt
{ content: `$hi{ }
```

**Comment by USERSATOSHI** [comment] 2022-06-06 06:04
oh i got it now ,
thanks for explaining

**Closed** 2022-06-06 06:05 UTC
