### ISSUE TITLE
Removing files via npm scripts does not work on windows 10

### ISSUE THREAD

**Issue by rajzik** [nodejs/help#2200] opened 2019-09-23 14:38 UTC
* **Version**: v12.7.0 and v12.10.0
* **Platform**: Windows 10 64 bit

When trying to clean the repository with clean script it is not possible with npm run script. I have tried `cmd` and `ps` with no difference.

## Steps to reproduce
1. package json
```json
{
  ...,
  "scripts": {
    "clean": "del-cli './{esm,dist,lib,.cache}'",
    "clean2": "rimraf './{esm,dist,lib,.cache}'",
  },
  ...
}
```
2. `npm run clean` -> does nothing
     1. same with administrator mode
3. Tring from cmd with `npx rimraf './{esm,dist,lib,.cache}'` works

No error what so ever.

**Comment by Hakerh400** [comment] 2019-09-24 06:46
If you want to delete folders `esm`, `dist`, `lib` and `.cache` when you run `npm run clean` from cmd, then put this in your `package.json`

```json
{
  "scripts": {
    "clean": "rd /s /q esm dist lib .cache>nul 2>&1|echo.>nul"
  }
}
```

You don't need `clean2` or `del-cli` or `npx rimraf`

**Comment by rajzik** [comment] 2019-09-24 06:57
@Hakerh400 so it's ok that rimraf from package scripts doesn't work? 
I would like to have a solution that isn't dependent on OS.
This solution is only for windows?

**Comment by Hakerh400** [comment] 2019-09-24 07:20
For platform independent solution use:

```json
{
  "scripts": {
    "clean": "del-cli esm dist lib .cache>nul 2>&1|echo.>nul"
  }
}
```

> so it's ok that rimraf from package scripts doesn't work?

I am not sure what you mean. What is the purpose of the `clean2` script? Where do you run it? You said `npm run clean -> does nothing`, but then you say that `rimraf` works from cmd. I don't see relation between these two statements. In your initial example, `clean` calls `del-cli` and `clean2` calls `rimraf`. It is redundant.

**Comment by rajzik** [comment] 2019-10-03 07:37
@Hakerh400 That was an example of my approach. 
I have tried two packages which should delete files and folders.
My issue is when I execute `rimraf` with `npx` it is working but when I try the same command as npm script it doesn't work. 
Is this behavior expected?

**Comment by Hakerh400** [comment] 2019-10-06 05:59
Neither of your scripts work for me. You are using incorrect syntax. The `rimraf` CLI expects directory paths to be provided as arguments (separated by a space). Same for `del-cli`. But, you provided directory names separated by commas and surrounded by braces. It thinks that is a single folder. The correct usage is:

```json
{
  "scripts": {
    "clean": "del-cli esm dist lib .cache",
    "clean2": "rimraf esm dist lib .cache"
  }
}
```

* `npx rimraf esm dist lib .cache` - Works
* `npm run clean` - Works
* `npm run clean2` - Works

**Comment by rajzik** [comment] 2019-10-08 10:25
Well, that's my issue.

```json
{
  "scripts": {
      "clean": "rimraf '{build,dist}'",
      "clean3": "npx rimraf '{build,dist}'",
      "clean2": "rimraf build"
  }
}
```

## What's working from powershell

- `npx rimraf '{build,dist}'`
- `npm install -g rimraf` -> `rimraf '{build,dist}'`
- `npm run clean2`

and mentioned in your response.

## what doesn't work for me

- `npm run clean`
- `npm run clean3`

So again, is this intended behavior of npm scripts? 
Why it doesn't work the same?

**Comment by Hakerh400** [comment] 2019-10-08 19:33
You didn't say you're using Powershell. The problem is because Powershell removes signle quote characters. When executed from Command Prompt, single quotes are not removed, so `rimraf` thinks that you're trying to delete a file that has literal name `'{build,dist}'` (including quotes), so it does not work. Same with NPM script.

To make it work with NPM script, simply remove the quotes:

```json
{
  "scripts": {
    "clean": "rimraf {build,dist}",
    "clean3": "npx rimraf {build,dist}",
    "clean2": "rimraf build"
  }
}
```

**Comment by gireeshpunathil** [comment] 2019-12-27 10:05
@rajzik - is this resolved?

**Comment by rajzik** [comment] 2019-12-28 06:24
Yeah.

**Comment by gireeshpunathil** [comment] 2019-12-28 06:43
closing then, cheers!

**Closed by gireeshpunathil** 2019-12-28 06:43 UTC

**Comment by eladkarako** [comment] 2020-08-26 18:33
workaround. 
http://gnuwin32.sourceforge.net/packages/coreutils.htm
Use download exe and dependencies. no more weak/ambiguous delete.
`call "rm.exe" --directory --force --no-preserve-root --recursive --verbose "<C:\your\folder>"`

you can script it with NodeJS as an execute with arguments, in various ways.

**Comment by oneezy** [comment] 2021-07-14 17:39
> To make it work with NPM script, simply remove the quotes:
> ```json
> {
>   "scripts": {
>     "clean": "rimraf {build,dist}",
>     "clean3": "npx rimraf {build,dist}",
>     "clean2": "rimraf build"
>   }
> }
```

For me to get this to work w/ Gitbash on Windows 10, I had write it like this:
```
"scripts": {
  "clean": "rimraf build"
}
```
and then this did the job
```
npm run clean
```

**Comment by sajjadTareen** [comment] 2022-03-21 09:26
For Windows need to replace '/ ' with '\' eg
`"clean": "del ./build/*"`
becomes:
`"clean": "del .\\build\\*"`
