### ISSUE TITLE
Please help me as quick as possible

### ISSUE THREAD

**Issue by Lemoncino** [nodejs/help#661] opened 2017-06-07 20:15 UTC
So I have a problem with this, I don't know what's the matter but it tells me "missing ) after argument list" even tho everything seems ok: 

```js
const Discord = require("discord.js");
const client = new Discord.Client();
const prefix = "!"

client.on('ready', () => {
console.log(`Logged in as ${client.user.username}!`);
client.user.setGame('With kittens');
    }
  });
client.on('message', msg => {
 if (msg.content === prefix + 'Ping') {
  msg.reply('Stop fu***ng pinging me...');
    }
  });
client.on('message', msg => {
 if (msg.content === prefix + 'Hey') {
  msg.reply('Heyo! Im a bot created by 柠檬 (Lemon)!');
    }
  });
client.on('message', msg => {
 if (msg.content === prefix + '.rank') {
  msg.reply('Uhm.. Sorry for the inconvenience but I do not know your rank. You should ask DezinBot by typing !rank');
    }
  });
client.on('message', msg => {
 if (msg.content === prefix + 'Help') {
  msg.reply('Hey! Im still learning so I dont know many commands, these are the available ones: !Ping !Hey !.rank !Help');
    }
  });
client.on('guildMemberAdd', member => {
 member.guild.defaultChannel.send(`Welcome to 𝖉𝖊𝖟𝖎𝖓𝖌𝖆𝖒𝖊𝖘, ${member}!`);
    }
  });
client.login(' there actually is a normal number but I can't show it here );
```

**Comment by addaleax** [comment] 2017-06-07 20:19
I think the problem is that you `'I can't show this token'` has the `'` in the middle of the string, you’ll need to escape it as `\'` (or use a apostrophe like `’` instead).

And by the way, you can wrap pieces of source code that you post on github in  ```` ``` ```` so that it becomes more readable, for example:

    ```js
    console.log('Hello world!');
    ```

becomes

```js
console.log('Hello world!');
```

:smile:

**Comment by vsemozhetbyt** [comment] 2017-06-07 20:22
+ It seems you have an extra `}` in fragments like this:
```
    }
  });
```

**Comment by Lemoncino** [comment] 2017-06-07 20:29
this is what I get 
}
^

SyntaxError: missing ) after argument list
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3

**Comment by Lemoncino** [comment] 2017-06-07 20:29
I tried doing everything I could but it still gives me this error

**Comment by Lemoncino** [comment] 2017-06-07 20:31
Oh also, addaleax there is a normal code without any ' , I just typed in that because I can't show that code xD The whole thing worked perfectly before, now it does not

**Comment by lordKnighton** [comment] 2017-06-07 20:34
```js
client.login('I can't show this token'); 
```
Try 

```js
client.login("I can't show this token");
```

**Comment by vsemozhetbyt** [comment] 2017-06-07 20:34
@Lemoncino Is your code now like this (see the comments)?
```js
const Discord = require("discord.js");
const client = new Discord.Client();
const prefix = "!"

client.on('ready', () => {
console.log(`Logged in as ${client.user.username}!`);
client.user.setGame('With kittens');
  // deleted }
  });
client.on('message', msg => {
 if (msg.content === prefix + 'Ping') {
  msg.reply('Stop fu***ng pinging me...');
    }
  });
client.on('message', msg => {
 if (msg.content === prefix + 'Hey') {
  msg.reply('Heyo! Im a bot created by 柠檬 (Lemon)!');
    }
  });
client.on('message', msg => {
 if (msg.content === prefix + '.rank') {
  msg.reply('Uhm.. Sorry for the inconvenience but I do not know your rank. You should ask DezinBot by typing !rank');
    }
  });
client.on('message', msg => {
 if (msg.content === prefix + 'Help') {
  msg.reply('Hey! Im still learning so I dont know many commands, these are the available ones: !Ping !Hey !.rank !Help');
    }
  });
client.on('guildMemberAdd', member => {
 member.guild.defaultChannel.send(`Welcome to 𝖉𝖊𝖟𝖎𝖓𝖌𝖆𝖒𝖊𝖘, ${member}!`);
  // deleted }
  });
client.login('I can\'t show this token'); // escaped '
```

**Comment by Lemoncino** [comment] 2017-06-07 20:37
Oh... It seems you have an extra } in the first and the last fragments like this:

    }
  });
 you was right, I removed these ones and now it works, thank you a lot..

**Comment by vsemozhetbyt** [comment] 2017-06-07 20:40
@Lemoncino If it is fixed, it seems we can close this issue for now, but feel free to ask more questions or reopen the issue if you need :)

**Closed by vsemozhetbyt** 2017-06-07 20:40 UTC
