### ISSUE TITLE
../src/node_buffer.cc:219:char* node::Buffer::Data(v8::Local<v8::Object>): Assertion `obj->IsArrayBufferView()' failed.

### ISSUE THREAD

**Issue by PkNuAbrahim** [nodejs/help#1927] opened 2019-05-26 11:04 UTC
```js
var BTSP = require('bluetooth-serial-port');
var serial = new BTSP.BluetoothSerialPort();

serial.on('found', function(address, name) {

    // you might want to check the found address with the address of your
    // bluetooth enabled Arduino device here.

    if (name === "HC-05"){
    serial.findSerialPortChannel(address, function(channel) {
        serial.connect(address, channel, function() {
            console.log('connected');
            process.stdin.resume();
            process.stdin.setEncoding('utf8');
            console.log('Press "1" or "0" and "ENTER" to turn on or off the light.')
process.stdin.on('data', function (data) {
            
                serial.write(data);
            });

            serial.on('data', function(data) {
                console.log('Received: ' + data);
            });
        }, function () {
            console.log('cannot connect');
        });
    });
}
});

serial.inquire();
```

i wanna know why this code occur error ( node[4957]: ../src/node_buffer.cc:219:char* node::Buffer::Data(v8::Local<v8::Object>): Assertion `obj->IsArrayBufferView()' failed.
) i wanna connet arduino and raspberry pi3 with node.js

**Comment by addaleax** [comment] 2019-05-26 13:07
@PkNuAbrahim Can you open this issue at https://github.com/eelcocramer/node-bluetooth-serial-port, and link this one there? This doesn’t look like it’s related to Node.js itself, but rather the bluetooth module you’re using.

A quick guess would be that the issue is that you are passing strings to the serial port:

```
            process.stdin.setEncoding('utf8');
            [...]
process.stdin.on('data', function (data) {
            
                serial.write(data);
            });
```

`.setEncoding()` makes `process.stdin` emit strings instead of Buffers, but the typechecking code in `serial.write()` seems broken:

https://github.com/eelcocramer/node-bluetooth-serial-port/blob/0b5ce52ceecd3a7ad18849b95f62a6c45a0b8bab/src/linux/BTSerialPortBinding.cc#L301-L306

They attempt to throw a type error, but don’t return to JS and instead let the code continue running; the `Buffer::Data()` call might be what is causing you trouble.

**Comment by PkNuAbrahim** [comment] 2019-05-26 14:46
@addaleax thank you for the reply ,i reuploaded this issue at link you gave me..
i appriciate you.

**Comment by addaleax** [comment] 2019-05-26 15:16
I’m closing this since it’s moved to another repository. If it turns out there’s an issue with Node.js itself, we can always re-open this.

(Also, I commented over there, so that the maintainers can see the the triage info that I provided here. Generally, when opening issues about the same thing in multiple places, it’s a good idea to provide links between them, so that everybody can be on the same page and have all available context.)

**Closed by addaleax** 2019-05-26 15:16 UTC
