### ISSUE TITLE
Node fails quickly with `std::bad_alloc` yet there is plenty of unused heap size

### ISSUE THREAD

**Issue by holyjak** [nodejs/help#1544] opened 2018-10-11 21:53 UTC
* **Node.js Version**: 8.11.4
* **OS**: Linux (Amazon)
* **Scope (install, code, runtime, meta, other?)**: runtime

We have a Node app that gets about 200 req / minute, mostly fetching data from Redis, `JSON.parse`ing it and returning. It crashes reliably within 3-5 min of start with either 

```
terminate called after throwing an instance of 'std::bad_alloc'
what(): std::bad_alloc
```

or 

```
# Fatal error in , line 0
# Out of memory: HashMap::Initialize
```

The weird thing is that it uses only a part of its heap (provided our monitoring `process.memoryUsage()` isn't missing something) - we run it with `--max-old-space-size=3072` (on a 4GB machine) and `heapUsed < 750MB`, `heapTotal < 1GB`, `rss < 1GB`, `osMemoryFree 2 - 3 GB`.

These memory crashes and lower rss/heap usage started after a deployment of a recent change so it is likely the change causes this, but

1. Why is Node crashing with out-of-memory when there _seems_ to be plenty of it available?
2. What are we missing in our monitoring? Could it be that it is running out of space in same weird kind of memory, other than the standard heap, that our monitoring is not watching?
3. Can we supply some command-line options to get more insight into which memory it is lacking / where is it crashing?

Thank you so much!

This is the code that was deployed when memory usage dropped and the OOM crashes started:

```js
/** Allow max one promise 'in progress' for the given `key`; return it if requested again before finished. */
class PromiseThrottle {

    constructor() {
        this.requestsInProgress = {};
    }

    throttle(key, promiseMaker) {
        if (this.requestsInProgress[key]) return this.requestsInProgress[key]; // Return the in-progress promise

        return this.requestsInProgress[key] = new Promise((resolve) =>
            resolve(timeout(promiseMaker(), time.fifteenMinutesInMs)))
            .then(d => { delete this.requestsInProgress[key]; return d; })
            .catch(err => { delete this.requestsInProgress[key]; throw err; });
    }
}

const redisGetThrottle = new PromiseThrottle();
/** Get a key - return null when not present. */
function get(key) {
    return redisGetThrottle.throttle(key, () => redis.get(key).then(JSON.parse));
   // BEFORE this change it was just:
  // return  redis.get(key).then(JSON.parse);
}
```

**Comment by addaleax** [comment] 2018-10-11 21:59
Do you think you could provide us with a core dump, or a native stack trace à la https://www.npmjs.com/package/segfault-handler?

This *sounds* like more of a real bug with Node.js than an actual out-of-memory situation.

**Comment by gireeshpunathil** [comment] 2018-10-11 23:44
probably try with `ulimit -c unlimited` ?

**Comment by addaleax** [comment] 2018-10-12 02:32
@jakubholynet Is there a realistic chance that the heapdump creation itself is causing the OOM?

**Comment by jakubholynet** [comment] 2018-10-12 06:18
@addaleax that is something I am also considering

Did some load testing and this is interesting:

```
top - 06:15:22 up  7:15,  3 users,  load average: 15.17, 11.34, 5.99
Tasks: 107 total,   1 running,  78 sleeping,   0 stopped,   0 zombie
Cpu(s):  0.7%us,  0.5%sy,  0.0%ni, 91.6%id,  6.4%wa,  0.0%hi,  0.0%si,  0.7%st
Mem:   4040060k total,  3935204k used,   104856k free,    10232k buffers
Swap:        0k total,        0k used,        0k free,   594284k cached

  PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND
25602 nodejs    20   0 4613m 2.9g  34m S  2.7 76.0   0:32.69 node
```

Notice the node is using 4613m virt memory (was ± 2000 before the load) and it uses 2.9g mem so close to the max heap size. Not sure if that indicates a problem or not.

**Comment by jakubholynet** [comment] 2018-10-12 07:35
Yet another, different crash, this time with stack:

```
<--- Last few GCs --->

[26816:0x24f9bf0]   675949 ms: Mark-sweep 1803.6 (3179.4) -> 1803.4 (3184.9) MB, 216
7.1 / 1.2 ms  allocation failure GC in old space requested
[26816:0x24f9bf0]   678132 ms: Mark-sweep 1803.4 (3184.9) -> 1803.3 (3142.9) MB, 218
3.1 / 2.8 ms  last resort GC in old space requested
[26816:0x24f9bf0]   680314 ms: Mark-sweep 1803.3 (3142.9) -> 1803.3 (3132.4) MB, 218
2.0 / 3.3 ms  last resort GC in old space requested

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x9a00eaa5879 <JSObject>
    0: builtin exit frame: parse(aka parse)(this=0x2f4b902822d1 <undefined>,0x370dd7
044021 <Very long string[12009700]>)

    1: /* anonymous */ [/opt/dynatrace/oneagent/agent/res/nodeagent/nodejsagent.js:1
0819] [bytecode=0x20805e2d5ce9 offset=95](this=0x2bd904b4509 <Object map = 0x6f5396b
6d91>,k=0x2f4b902822d1 <undefined>,h=0x9a00ea89149 <JSFunction parse (sfi = 0x2f4b90
2b12b9)>,l=0x370dd7044389...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [node]
 2: 0x8c21ec [node]
 3: v8::Utils::ReportOOMFailure(char const*, bool) [node]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [node]
 5: v8::internal::Factory::NewRawTwoByteString(int, v8::internal::PretenureFlag) [node]
 6: v8::internal::String::SlowFlatten(v8::internal::Handle<v8::internal::ConsString>, v8::internal::PretenureFlag) [node]
 7: v8::internal::Builtin_JsonParse(int, v8::internal::Object**, v8::internal::Isolate*) [node]
 8: 0x34e36a70697d
```

**Comment by jakubholynet** [comment] 2018-10-12 14:54
Ok, I have tracked it down to two problems:

I: The memory visible from a heapdump is a fraction (1/4 - 1/10) of the actual physical memory used.

II: There is a memory leak caused by using `Promise.race` with the data-returning promise and `setTimeout`. I know how to get rid of it (don't use setTimeout) but have no idea why it happens.

See https://gist.github.com/jakubholynet/6c8f615c195ebb7b3ef4d9a0a0ee4362 for details of both issues.

**Comment by gireeshpunathil** [comment] 2019-06-28 09:34
ping @holyjak - is this still an issue?

**Comment by holyjak** [comment] 2019-06-28 19:38
I cannot verify anymore. sorry.

**Comment by gireeshpunathil** [comment] 2019-06-29 02:04
ok, let us close this then, please re-open when we have data to share.

**Closed by gireeshpunathil** 2019-06-29 02:04 UTC
