### ISSUE TITLE
REPL: Differed output on addition of " ; "

### ISSUE THREAD

**Issue by pranshuchittora** [nodejs/help#2967] opened 2020-09-08 07:51 UTC
* **Version**: v12, v14
* **Platform**: Linux
* **Subsystem**: Ubuntu 20

### What steps will reproduce the bug?
![Screenshot from 2020-09-08 13-17-18](https://user-images.githubusercontent.com/32242596/92448322-0f499f80-f1d6-11ea-86cb-f55ef7069c67.png)

### How often does it reproduce? Is there a required condition?
Always

### What is the expected behavior?
![Screenshot from 2020-09-08 13-18-30](https://user-images.githubusercontent.com/32242596/92448361-1cff2500-f1d6-11ea-8297-57560730a85a.png)

Chrome Version 85.0.4183.83 (Official Build) (64-bit)

### What do you see instead?
Same output

**Comment by bnoordhuis** [comment] 2020-09-08 12:38
I've moved this to nodejs/help because what you're seeing is expected behavior.

The REPL has some built-in smarts to detect whether something can be evaluated as a statement or an expression.

`{} + []` is a legal expression and evaluated as `( {} + [] )`. When you add a semicolon, it's evaluated as a statement instead.

Chrome/Chromium always evaluates it as a statement.

**Comment by RaisinTen** [comment] 2020-12-25 15:11
Closing since this is already answered.

**Closed by RaisinTen** 2020-12-25 15:11 UTC
