### ISSUE TITLE
Suddenly, I couldn't connect to mysqlDB. connect ECONNREFUSED 127. 0.0.1:3306

### ISSUE THREAD

**Issue by secmin** [nodejs/help#2841] opened 2020-07-13 03:28 UTC
Node.js Version**:  12.18.2
OS**:   linux ubuntu 18.04.3 LTS
Scope (install, code, runtime, meta, other?)**:  code
Module (and version) (if relevant)**: mysql(npm/mysql2)

mysql driver : https://github.com/mysqljs/mysql

I was able to insert into the DB, but suddenly the connection was not working.

Error: connect ECONNREFUSED 127.0.0.1:3306
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1134:16) {
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 3306,
  fatal: true
}

const mysql = require('mysql2')

const connectionConfig = {
  host: process.env.DB_HOST,
  user: process.env.DB_USER,
  password: process.env.DB_PASS,
  database: process.env.DB_NAME
}

const pool = mysql.createPool(connectionConfig )

module.exports = pool

function accountCreate(account) {
  const id = nanoid(10)
  const post = {
    id,
    name: account.name,
    account_category_id: account.category,
  }

  pool.execute('INSERT INTO accounts SET ?' , post, function (err, results, fields) {
　// Error here.
    if (err) console.error(err)
    console.log(results, fields)
  })
}

The CLI can be run in the terminal with no problem.
Changing pool.execute to pool.query didn't change it.
Also, mysql points out that this is a problem that's specific to nodejs.
You can find it here: https://github.com/mysqljs/mysql/issues/2268

That's all.
Please help me.

**Comment by gireeshpunathil** [comment] 2021-09-02 15:57
@secmin - is this still outstanding?

**Comment by secmin** [comment] 2021-09-03 01:11
@gireeshpunathil 
I couldn't figure out the cause at the time, but it was restored.

**Comment by gireeshpunathil** [comment] 2021-09-03 02:12
@secmin - ok, nice to know that the issue is resolved, closing then! feel free to re-open if you start seeing the issue again!

**Closed by gireeshpunathil** 2021-09-03 02:12 UTC

**Comment by PS8924** [comment] 2022-03-29 01:54
seeing this issue. can not able to find solution. Please help!

**Comment by mahfuz0001** [comment] 2024-03-10 13:28
> seeing this issue. can not able to find solution. Please help!

same
