### ISSUE TITLE
process.stdin.on('data') fires all it's data in the same tick

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#2088] opened 2019-07-31 08:02 UTC
I ran this:

```bash
tail -n 35111  <file> | node read-stdin.js
```

in `read-stdin.js` I have:

```js
process.stdin.resume().on('data', d =>{
  console.log(d);
});
```

what seems to happen is that all the on('data') calls happen in the same tick - so I can't have any user interaction with the script (signals etc), until all the data events fire. Is this expected? Any way around this?

I thought about adding some buffer process:

```bash
tail -n 35111  <file> | buffer | node read-stdin.js
```

but I don't really know how to delay things so that the nodejs receiver can handle other i/o in the meantime.

**Comment by ORESoftware** [comment] 2019-07-31 08:08
my guess is that I can use backpressure somehow? 
https://nodejs.org/ja/docs/guides/backpressuring-in-streams/

so something like this:

```js
process.stdin.resume().pipe(makeBackPressure())on('data', d =>{
  console.log(d);
});
```

but how do I implement it?

**Comment by addaleax** [comment] 2019-07-31 11:19
You can do one of the following:

a) Turn your `'data'` handler into the `_write()` method of a `Writable` stream, use the `_write()` callback to indicate that you’re done processing, and then pipe into that Writable (this is likely the ideal solution, imo)
b) Use async iteration over `process.stdin` (e.g. `for await (const chunk of process.stdin) { ... }`), if your handler could be turned into an async function
c) Add/remove the `'data'` listener to only receive data as needed
d) Use `.on('readable')` instead, to know when the stream has data available, and use `.read()` to retrieve that data only when needed
e) Manually call `process.stdin.pause()` and `process.stdin.resume()` from the `'data'` listener – this might not play well with other consumers, when there are any

**Comment by ORESoftware** [comment] 2019-07-31 16:11
Ok cool, as for (a) isnt a transform stream writable? should I mess with the _write method of the stream? is there a way to use highWaterMark with a transform stream. I am using objectMode:true with the transform stream.

**Comment by addaleax** [comment] 2019-07-31 16:24
@ORESoftware A transform stream is writable, but I’m not sure what “the transform stream” in your reply refers to?

What I’m thinking of is something like this.

```js
const w = new Writable({
  write(chunk, encoding, cb) {
    doSomethingAsynchronously(chunk, () => cb());
  }
});
process.stdin.pipe(w);
```

(Passing `write` to the `Writable` constructor is a clean way of setting `._write` directly on construction.)

If you do pass the input data to a Transform stream – objectMode or not – then piping into that would already be sufficient for making sure that backpressure is respected.

**Comment by ORESoftware** [comment] 2019-07-31 16:26
Thanks, sorry this is the transform stream I was talking about:

https://stackoverflow.com/questions/57286321/implementing-backpressure-in-a-transform-stream/57295095

in my original post the transform stream was supposed to be returned from the `makeBackPressure()`  call.

**Comment by addaleax** [comment] 2019-07-31 16:30
@ORESoftware Setting the highWaterMarks will not necessarily affect the rate at which input is consumed, and will not enable or disable backpressure handling¹. Piping into another stream will essentially mean that the source’s `readableHighWaterMark` and the destination’ş `writableHighWaterMark` form a combined buffer.

It might help if you provide more information about the problem you’re ultimately trying to solve?

¹ I guess if you set a high water mark to Infinity that does disable backpressure handling.

**Comment by ORESoftware** [comment] 2019-07-31 17:12
Hey Anna yeah the problem I am trying to solve is to avoid all 35K events firing in the same tick. If even 1/20 of those events could be delayed to the next tick that would be fine. But they do have to fire in order, which is where the challenge is.

**Comment by addaleax** [comment] 2019-07-31 17:28
@ORESoftware I still feel like this issue here is mixing two things up – one is backpressure handling, and the other is event loop blocking.

If the underlying problem is lack of backpressure handling, then https://github.com/nodejs/help/issues/2088#issuecomment-516807273 lists a number of possible solutions to that problem. If you want to know in more detail how to apply that to your particular use case, then it would be good if you could share information about what you do with the data.

If proper backpressure handling is in place, and the event loop being blocked is the real issue here, then it’s hard to tell how one can best help you without knowing how you process the data. If you are processing it synchronously, then that will block the event loop for a tick, sure. If you are processing it asynchronously and the issue is really just that it results in a high load factor for your process, you could pipe into a transform stream that automatically throttles throughput (e.g. [this module](https://www.npmjs.com/package/stream-throttle) provides rate-based throttling).

**Comment by ORESoftware** [comment] 2019-07-31 17:32
well my guess was that applying backpressure would force the reader to wait til next tick to read etc, but maybe that's wrong

**Comment by ORESoftware** [comment] 2019-07-31 19:52
I am going to try to understand that throttle module along with the token-bucket design of require('limiter');

but I guess if I were to design my own interface it would have to look something like this:


```js
const q = new LinkedQueue();

const run = () => {
 
 for(let v of q.deq(18)){
     doSomething();
  }

  process.nextTick(run);
};

run();
```


something recursive like this is the only way to delay the remainder of the items will preserving the order of the items. above I am processing no more than 18 items, and then delaying the remainder until the next tick of the event loop. but, in the context of the streams API,  I actually have no idea how to preserve the order and have a next tick delay.

The problem with rate limiting to x per second or whatever, in some cases those algorithms are inefficient, but I will take a look at the limiter module etc, maybe that token bucket algo will work...I know the above will work, but not sure how to implement it in a transform stream, any idea?

**Comment by ORESoftware** [comment] 2019-07-31 20:02
maybe this will in fact work?
https://stackoverflow.com/questions/57298081/how-to-deplay-processing-of-stream-transform-items

**Comment by addaleax** [comment] 2019-07-31 20:53
> well my guess was that applying backpressure would force the reader to wait til next tick to read etc, but maybe that's wrong

Not applying backpressure is generally a bug, but it may or may not be what helps here and that’s impossible to tell without knowing your application better. If the data processing happens synchronously, it won’t help. If it happens asynchronously, it will help, and it will force data to be emitted in a later event loop turn.

If delaying to the next event loop turn is really all you need, then this will help:

```js
const delayTransform = new Transform({
  transform(chunk, enc, cb) {
    // Artificially delay passing on the data by one event loop turn
    setImmediate(cb, null, chunk);
  }
});

process.stdin.pipe(delayTransform).on('data', ...)
```

**Comment by ORESoftware** [comment] 2019-08-03 07:47
@addaleax you might already be aware of this (or maybe I am wrong) but I don't think you want to put everything on the next tick...for example:

```js
const list = []  // 500K items

for(let v of list){
  process.nextTick(() => {
    console.log(v);
  });
}
```

because that's just going to block the event loop on the next tick instead of this one.

I think the idea is you want to process them in thunks, delay every 300 or 400 or so, something like this:


```js

const list = []  // 500K items
let v = 0;

const processTheList = () => {

 let stop = v + 300;

 while(v++ < stop){
    console.log(v);
  }

  process.nextTick(processTheList);

});

```

**Comment by addaleax** [comment] 2019-08-03 13:08
> but I don't think you want to put everything on the next tick...for example:

That’s not what happens. Each chunk gets its own event loop turn with the `delayTransform` example.

> because that's just going to block the event loop on the next tick instead of this one.

It’s going to block the event loop on the *current* tick, because `process.nextTick()` callbacks run in the same event loop turn.

> I think the idea is you want to process them in chunks, delaying every 300 or 400 or so

Sure, you could do that too. But `process.nextTick()` is not going to help you with anything that involves event loop blockage, you do need `setImmediate()` or `setTimeout()` for that.

**Comment by ORESoftware** [comment] 2019-08-03 16:55
Ahh, good to know about process.nextTick, I always thought it ran at the beginning of the next tick of the event loop but now sounds like the end of current tick? poorly named utility, but I have used it a lot to good affect, so not too much complaints.

so setImmediate it is, and yeah I agree that in your example all the calls will get daisy chained and each will happen in a subsequent tick - but that's too much delaying, I just need to delay every 50 chunks or so. thanks for the info.

**Comment by addaleax** [comment] 2019-08-03 17:05
> Ahh, good to know about process.nextTick, I always thought it ran at the beginning of the next tick of the event loop but now sounds like the end of current tick?

Yes, it runs every time at the end of a call from the event loop into JS.

> poorly named utility

:100: 

> I just need to delay every 50 chunks or so. thanks for the info.

I guess it’s not hard, but fwiw, here’s how I’d modify the example above to do that:

```js
class DelayTransform extends Transform {
  constructor() {
    super();
    this.count = 0;
  }

  _transform(chunk, enc, cb) {
    if (this.count++ % 50 === 0) {
      // Artificially delay passing on the data by one event loop turn
      setImmediate(cb, null, chunk);
    } else {
      cb(null, chunk);
    }
  }
}

process.stdin.pipe(delayTransform).on('data', ...)
```

**Comment by gireeshpunathil** [comment] 2019-12-20 10:29
closing as answered; pls re-open if necessary

**Closed by gireeshpunathil** 2019-12-20 10:29 UTC
