### ISSUE TITLE
Node.js http server is creating large number of the tcp sockets which stayed in ESTABLISHED state which slow down the server

### ISSUE THREAD

**Issue by enzigma-gaurav-wadghule** [nodejs/help#2242] opened 2019-10-20 05:34 UTC
Hello,
 we have implemented http server with nodejs version 10.6. Node application is hosted with docker container with node-alpine as base image. problem we are facing is that node server is creating large number of tcp sockets as time increases from application deployment which slow down the node application. when i have executed the lsof -i command inside the environment where application is running i get the list of the ESTABLISHED tcp connections.

to close the tcp connection we have implemented timeout for socket.
![image](https://user-images.githubusercontent.com/56781097/67155096-0930a300-f326-11e9-9dde-c1052f28a91b.png)

**Comment by bnoordhuis** [comment] 2019-10-20 11:29
I'm moving this to nodejs/help because the issue is almost certainly with your application (failing to close connections) rather than a bug in Node.js.

**Comment by gireeshpunathil** [comment] 2019-12-27 08:49
do you have special settings for [Agent](https://nodejs.org/dist/latest-v13.x/docs/api/http.html#http_class_http_agent) in your server?

In either case, if you suspect that the sockets are not being cleaned up on time, it is worthwhile to collect heapdumps and inspect the `http.ClientRequest` and `http.ServerResponse` objects to see how many of those are around, and what is holding them up

**Comment by gireeshpunathil** [comment] 2020-11-13 11:12
closing, inactive. feel free to re-open if it is outstanding

**Closed by gireeshpunathil** 2020-11-13 11:12 UTC
