### ISSUE TITLE
recodesign node got error when run

### ISSUE THREAD

**Issue by Rhain** [nodejs/help#4122] opened 2023-03-07 03:13 UTC
### Details

I codesign the node with my own appId with command `codesign --deep --timestamp --options runtime -f -s 'Developer ID Application: xxxxxxxx' ~/Library/Keychains/login.keychain-db  node`.
evertything looks fine, but when I ran node ,I got this error:
```

#
# Fatal error in , line 0
# Check failed: reservation_.SetPermissions(unprotect_start, unprotect_size, FLAG_write_code_using_rwx ? PageAllocator::kReadWriteExecute : PageAllocator::kReadWrite).
#
#
#
#FailureMessage Object: 0x7ff7bc3c2a50
 1: 0x103c7c5e2 node::NodePlatform::GetStackTracePrinter()::$_3::__invoke() [/usr/local/lib/gsf/bin/node]
 2: 0x104d68133 V8_Fatal(char const*, ...) [/usr/local/lib/gsf/bin/node]
 3: 0x103fbb4d4 v8::internal::MemoryChunk::SetCodeModificationPermissions() [/usr/local/lib/gsf/bin/node]
 4: 0x103f38f89 v8::internal::Heap::UnprotectAndRegisterMemoryChunk(v8::internal::MemoryChunk*, v8::internal::UnprotectMemoryOrigin) [/usr/local/lib/gsf/bin/node]
 5: 0x103f0c8ac v8::internal::Heap::AllocateRaw(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/local/lib/gsf/bin/node]
 6: 0x103f3ed01 v8::internal::Heap::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/local/lib/gsf/bin/node]
 7: 0x103f0b810 v8::internal::Factory::CodeBuilder::AllocateCode(bool) [/usr/local/lib/gsf/bin/node]
 8: 0x103f0afa9 v8::internal::Factory::CodeBuilder::BuildInternal(bool) [/usr/local/lib/gsf/bin/node]
 9: 0x103de1ea3 v8::internal::baseline::BaselineCompiler::Build(v8::internal::Isolate*) [/usr/local/lib/gsf/bin/node]
10: 0x103df4063 v8::internal::GenerateBaselineCode(v8::internal::Isolate*, v8::internal::Handle<v8::internal::SharedFunctionInfo>) [/usr/local/lib/gsf/bin/node]
11: 0x103e2e1c7 v8::internal::Compiler::CompileSharedWithBaseline(v8::internal::Isolate*, v8::internal::Handle<v8::internal::SharedFunctionInfo>, v8::internal::Compiler::ClearExceptionFlag, v8::internal::IsCompiledScope*) [/usr/local/lib/gsf/bin/node]
12: 0x103e2e553 v8::internal::Compiler::CompileBaseline(v8::internal::Isolate*, v8::internal::Handle<v8::internal::JSFunction>, v8::internal::Compiler::ClearExceptionFlag, v8::internal::IsCompiledScope*) [/usr/local/lib/gsf/bin/node]
13: 0x103dde048 v8::internal::baseline::BaselineBatchCompiler::CompileBatch(v8::internal::Handle<v8::internal::JSFunction>) [/usr/local/lib/gsf/bin/node]
14: 0x103dddf87 v8::internal::baseline::BaselineBatchCompiler::EnqueueFunction(v8::internal::Handle<v8::internal::JSFunction>) [/usr/local/lib/gsf/bin/node]
15: 0x1042f0861 v8::internal::(anonymous namespace)::BytecodeBudgetInterruptFromBytecode(v8::internal::Isolate*, v8::internal::Handle<v8::internal::JSFunction>) [/usr/local/lib/gsf/bin/node]
16: 0x1042ef453 v8::internal::Runtime_BytecodeBudgetInterruptFromBytecode(int, unsigned long*, v8::internal::Isolate*) [/usr/local/lib/gsf/bin/node]
17: 0x1046adff9 Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_NoBuiltinExit [/usr/local/lib/gsf/bin/node]
```

what's the  reason cause the error?

so how to fix this error?

### Node.js version

v17.8.0

### Operating system

mac_x64

### Scope

runtime

### Module and version

Not applicable.

**Comment by preveen-stack** [comment] 2023-04-27 15:25
[memory-chunk.cc](https://github.com/nodejs/node/blob/36e4e3d86b31de7f38125aacad810e40295fd2ae/deps/v8/src/heap/memory-chunk.cc#L84-L105)
```
void MemoryChunk::SetCodeModificationPermissions() {
  DCHECK(!V8_HEAP_USE_PTHREAD_JIT_WRITE_PROTECT);
  DCHECK(IsFlagSet(MemoryChunk::IS_EXECUTABLE));
  DCHECK(owner_identity() == CODE_SPACE || owner_identity() == CODE_LO_SPACE);
  // Incrementing the write_unprotect_counter_ and changing the page
  // protection mode has to be atomic.
  base::MutexGuard guard(page_protection_change_mutex_);
  write_unprotect_counter_++;
  if (write_unprotect_counter_ == 1) {
    Address unprotect_start =
        address() + MemoryChunkLayout::ObjectStartOffsetInCodePage();
    size_t page_size = MemoryAllocator::GetCommitPageSize();
    DCHECK(IsAligned(unprotect_start, page_size));
    size_t unprotect_size = RoundUp(area_size(), page_size);
    // We may use RWX pages to write code. Some CPUs have optimisations to push
    // updates to code to the icache through a fast path, and they may filter
    // updates based on the written memory being executable.
    CHECK(reservation_.SetPermissions(
        unprotect_start, unprotect_size,
        MemoryChunk::GetCodeModificationPermission()));
  }
}
```

I guess the FATAL error is from this function. I am not sure how to identify which line caused the error. I guess that one of the  DCHECK macro is failing.

Can you build node with 
`./configure --enable-node-code-cache`

and then run with 
`node --trace-opt app.js`
so that we can get the line number is visible in the crash

**Comment by Rhain** [comment] 2023-05-05 02:36
I used blow command to recodesign node.js, it's looks work fine.

```
codesign --deep --timestamp --preserve-metadata=entitlements --options runtime -f -s 'Developer ID Application: xxxxxxxx' --entitlements node.entitlements ~/Library/Keychains/login.keychain-db node
```

`--preserve-metadata=entitlements` is the key。

**Comment by Rhain** [comment] 2023-05-05 02:55
> [memory-chunk.cc](https://github.com/nodejs/node/blob/36e4e3d86b31de7f38125aacad810e40295fd2ae/deps/v8/src/heap/memory-chunk.cc#L84-L105)
> 
> ```
> void MemoryChunk::SetCodeModificationPermissions() {
>   DCHECK(!V8_HEAP_USE_PTHREAD_JIT_WRITE_PROTECT);
>   DCHECK(IsFlagSet(MemoryChunk::IS_EXECUTABLE));
>   DCHECK(owner_identity() == CODE_SPACE || owner_identity() == CODE_LO_SPACE);
>   // Incrementing the write_unprotect_counter_ and changing the page
>   // protection mode has to be atomic.
>   base::MutexGuard guard(page_protection_change_mutex_);
>   write_unprotect_counter_++;
>   if (write_unprotect_counter_ == 1) {
>     Address unprotect_start =
>         address() + MemoryChunkLayout::ObjectStartOffsetInCodePage();
>     size_t page_size = MemoryAllocator::GetCommitPageSize();
>     DCHECK(IsAligned(unprotect_start, page_size));
>     size_t unprotect_size = RoundUp(area_size(), page_size);
>     // We may use RWX pages to write code. Some CPUs have optimisations to push
>     // updates to code to the icache through a fast path, and they may filter
>     // updates based on the written memory being executable.
>     CHECK(reservation_.SetPermissions(
>         unprotect_start, unprotect_size,
>         MemoryChunk::GetCodeModificationPermission()));
>   }
> }
> ```
> 
> I guess the FATAL error is from this function. I am not sure how to identify which line caused the error. I guess that one of the DCHECK macro is failing.
> 
> Can you build node with `./configure --enable-node-code-cache`
> 
> and then run with `node --trace-opt app.js` so that line number is visible in the crash

Thanks for your answer, the above has solved the problem。

**Comment by preveen-stack** [comment] 2023-06-16 07:18
> Thanks for your answer, the above has solved the problem.

Good to know the problem is resolved. closing.

**Closed by preveen-stack** 2023-06-16 07:18 UTC
