### ISSUE TITLE
crypto module reference error

### ISSUE THREAD

**Issue by rashidvali** [nodejs/help#2864] opened 2020-07-19 17:22 UTC
* **Version**:12.18.2
* **Platform**:Windows 10
* **Subsystem**: Chrome v.83.0.4103.116

### What steps will reproduce the bug?
I do import in my module:
import * as crypto from 'crypto'

and call the following:
let hx = crypto.randomBytes(Math.ceil(1));

### How often does it reproduce? Is there a required condition?
permanent

### What is the expected behavior?
It has not to throw an error and has to return random bytes value

### What do you see instead?

external "crypto":1 Uncaught ReferenceError: require is not defined
    at Object.crypto (external "crypto":1)
    at __webpack_require__ (bootstrap:19)
    at Object../src/Lib/Util.ts (Util.ts:1)
    at __webpack_require__ (bootstrap:19)
    at Object../src/init.ts (init.ts:1)
    at __webpack_require__ (bootstrap:19)
    at bootstrap:83
    at bootstrap:83

### Additional information

I have in my package.json

  "devDependencies": {
    "@types/lodash": "^4.14.107",
    "@types/uuid": "^8.0.0",
    "ts-loader": "^8.0.1",
    "typescript": "^3.9.7",
    "typings-for-css-modules-loader": "^1.7.0",
    "webpack": "^4.43.0",
    "webpack-cli": "^3.3.12",
    "webpack-dev-server": "^3.11.0"
  },
  "dependencies": {
    "@types/node": "^14.0.23",
    "css-loader": "^1.0.0",
    "node-sass": "^4.14.1",
    "sass-loader": "^7.1.0",
    "style-loader": "^0.23.1",
    "uuid": "^8.2.0"
  }

This is plain TypeScript/Webpack project

**Comment by bnoordhuis** [comment] 2020-07-20 08:03
Closing as a duplicate of #2818

**Closed by bnoordhuis** 2020-07-20 08:03 UTC

**Comment by rashidvali** [comment] 2020-07-20 16:49
I'm sorry to say that but see no way how this case can be linked to #2818. My issue does not have any installation complains.
