### ISSUE TITLE
net.createConnection is not passing the socket object to the function

### ISSUE THREAD

**Issue by Johnny421** [nodejs/help#2805] opened 2020-06-27 17:08 UTC
Node.js Version: 14.4.0
OS: macOS Catalina ( 10.15.4 )
Module: Net

Hi,
I'm getting : "**TypeError: Cannot read property 'write' of undefined**" with the code down below. I looks like createConnection is not passing the socket to the function. Can someone please help to confirm if that is a bug?  
That is weird, because  net.**createServer**() compared to net.**createConnection** pass the socket to the function.

```
const net = require('net');

function connectListener(conn){

   conn.write('Hello!\r\n');
}

net.createConnection(8888, '127.0.0.1', connectListener);
```

**Comment by mkrawczuk** [comment] 2020-06-28 22:06
Sorry, this is not a bug, but a misunderstanding of net module API.
Please see `connectListener` documentation:  
> If supplied, will be added as a listener for the 'connect' event on the returned socket once.

And the `connect` event description:
> Emitted when a socket connection is successfully established.

Nothing is passed to the event listener's call, so no suprise `conn` is undefined.

Socket is not passed to `connectListener`, it is _returned_ by `net.createConnection`.

**Comment by Himself65** [comment] 2020-06-29 08:26
Closing as resolved, I think.

**Closed by Himself65** 2020-06-29 08:26 UTC
