### ISSUE TITLE
fs.writeSync is producing hex not utf8?

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#2087] opened 2019-07-31 05:25 UTC
I am non MacOS Node.js version 12.3

I have this:

```js
  const logFD = fs.openSync(somefilepath, 'w+');

  try {
    fs.writeSync(logFD, JSON.stringify({p: pos, b: byteLen}), h * 100, 'utf-8');
  } catch (err) {
    consumer.warn(err.message || err);
  }
```

I also tried using 'utf8' instead of 'utf-8'

I am always getting hex or whatever this is in the file:

```
6222 3a34 367d 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 7b22 7022 3a37 3239
3039 2c22 6222 3a32 317d 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 7b22 7022 3a37 3339 3331 2c22
6222 3a31 3032 7d00 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
```

is there some reason it's not readable as utf8?

**Comment by nemanjajovanovic97** [comment] 2019-07-31 08:26
Can you please next time

* Read the documentation
* Post a valid, runnable code
* Spend just a little bit more time trying to understand it yourself before asking others

First of all, the title *"fs.writeSync is producing hex not utf8"* doesn't make sense. Can you familiarize yourself with what hexadecimal representation and UTF-8 encoding of a text are? The sequence of bytes that you posted is indeed readable as UTF-8 and is completely valid UTF-8 text.

The reason your text editor is showing it as hexadecimal is because the file contains null bytes (UTF-8 character `\u0000`). You can instruct your text editor to display it as UTF-8 as well. That has nothing to do with Node.js.

The code snippet that you posted makes a lot of confusion, both to you and to anyone that tries to answer your question. Statement `logFD = fs.openSync(somefilepath)` is obviously incorrect, since you didn't specify that the file is opened for writing and it will throw EPERM on the first `writeSync` call. I guess you wrote it by hand and did not test it before posting, which again suggestes that you put almost no effort into this. You also could remove `try..catch` block and the `consumer`, because it is really irrelevant here and also undefined. What are `pos`, `byteLen` and `h`? Do someone need to read your mind in order to understand what you're trying to do in the code?

The simplified and clean code snippet that shows this behavior is:

```js
const fd = fs.openSync('test.txt', 'w');
for(let i = 0; i !== 5; i++)
  fs.writeSync(fd, JSON.stringify({}), i * 100, 'utf8');
```

It produces the following output (represented in hexadecimal):

```
7b7d 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 7b7d 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 7b7d 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 7b7d 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
7b7d 
```

So, my question to you is: what is the problem here? Why are you unsatisfied with the results? It works as per the documentation. Writing data at offset beyond the current file size will pad the file content with `0x00` bytes. That is working as intended.

If you're terrified of `0x00` bytes and want to replace them with some other character (for example a space), then change `JSON.stringify({})` to

```js
JSON.stringify({}).padEnd(100, ' ')
```

**Comment by ORESoftware** [comment] 2019-07-31 08:33
@nemanjajovanovic97  hey Nemanja, do you need lessons on how to be more of a condescending douchebag? :) Clearly you're not very good at it.

**Comment by ORESoftware** [comment] 2019-07-31 08:35
Appreciate the answer though, informative

**Comment by addaleax** [comment] 2019-07-31 11:40
I think I’ll just closed this as an answered question.

**Closed by addaleax** 2019-07-31 11:40 UTC
