### ISSUE TITLE
Help with failed build tests

### ISSUE THREAD

**Issue by kasicka** [nodejs/help#687] opened 2017-06-20 09:03 UTC
* **Node.js Version**: 8.1.2
* **OS**: RHEL 7
* **Scope (install, code, runtime, meta, other?)**: build
* **Module (and version) (if relevant)**:

Hi, I have some failed build tests on RHEL 7 that I would like to consult.

These two have been failing for v4 and v6 too:

```
=== release test-net-better-error-messages-port-hostname ===
Path: parallel/test-net-better-error-messages-port-hostname
assert.js:60
  throw new errors.AssertionError({
  ^
AssertionError [ERR_ASSERTION]: 'EAI_AGAIN' === 'ENOTFOUND'
    at Socket.<anonymous> (/builddir/build/BUILD/node-v8.1.2/test/parallel/test-net-better-error-messages-port-hostname.js:12:10)
    at Socket.<anonymous> (/builddir/build/BUILD/node-v8.1.2/test/common/index.js:517:15)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at emitErrorNT (internal/streams/destroy.js:62:8)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)
Command: out/Release/node /builddir/build/BUILD/node-v8.1.2/test/parallel/test-net-better-error-messages-port-hostname.js
                                                      
=== release test-net-connect-immediate-finish ===
Path: parallel/test-net-connect-immediate-finish
assert.js:60
  throw new errors.AssertionError({
  ^
AssertionError [ERR_ASSERTION]: 'EAI_AGAIN' === 'ENOTFOUND'
    at Socket.client.once.common.mustCall (/builddir/build/BUILD/node-v8.1.2/test/parallel/test-net-connect-immediate-finish.js:32:10)
    at Socket.<anonymous> (/builddir/build/BUILD/node-v8.1.2/test/common/index.js:517:15)
    at Object.onceWrapper (events.js:316:30)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at emitErrorNT (internal/streams/destroy.js:62:8)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)
Command: out/Release/node /builddir/build/BUILD/node-v8.1.2/test/parallel/test-net-connect-immediate-finish.js
```

These fail only with v8:
```
=== release test-util-inspect ===
Path: parallel/test-util-inspect
/builddir/build/BUILD/node-v8.1.2/test/parallel/test-util-inspect.js:85
assert.strictEqual(util.inspect(process.stdin._handle._externalStream),
                                                     ^
TypeError: Cannot read property '_externalStream' of undefined
    at Object.<anonymous> (/builddir/build/BUILD/node-v8.1.2/test/parallel/test-util-inspect.js:85:54)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
Command: out/Release/node /builddir/build/BUILD/node-v8.1.2/test/parallel/test-util-inspect.js

=== release test-v8-serdes ===
Path: parallel/test-v8-serdes
assert.js:60
  throw new errors.AssertionError({
  ^
AssertionError [ERR_ASSERTION]: Missing expected exception.
    at _throws (assert.js:553:5)
    at Function.throws (assert.js:577:3)
    at Object.<anonymous> (/builddir/build/BUILD/node-v8.1.2/test/parallel/test-v8-serdes.js:98:10)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
Command: out/Release/node /builddir/build/BUILD/node-v8.1.2/test/parallel/test-v8-serdes.js
```

I use shared zlib-1.2.7, compared to zlib-1.2.11, so maybe that fails this test:

```
Path: parallel/test-zlib-failed-init
assert.js:60
  throw new errors.AssertionError({
  ^
AssertionError [ERR_ASSERTION]: Missing expected exception.
    at _throws (assert.js:553:5)
    at Function.throws (assert.js:577:3)
    at Object.<anonymous> (/builddir/build/BUILD/node-v8.1.2/test/parallel/test-zlib-failed-init.js:11:8)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
Command: out/Release/node /builddir/build/BUILD/node-v8.1.2/test/parallel/test-zlib-failed-init.js
```

**Comment by lordKnighton** [comment] 2017-07-19 15:31
@kasicka Did you get them to pass yet? Let me know if you still need help.

**Comment by kasicka** [comment] 2017-08-08 14:09
Nope, they still fail, plus I have test-regress-GH-746 failing randomly on various archs. I can't find a log, but the test times out.

**Comment by bnoordhuis** [comment] 2017-08-08 14:53
I believe the issue that made parallel/test-util-inspect flaky was fixed recently, although that may not have made it into a release yet.

parallel/test-net-better-error-messages-port-hostname and parallel/test-net-connect-immediate-finish failing means your DNS resolver returns something unexpected for invalid hostnames.  Might be a bug in the test, might be a bug in your network.

**Comment by gireeshpunathil** [comment] 2018-03-11 06:08
@kasicka - please let me know if this is still outstanding.

**Comment by gireeshpunathil** [comment] 2018-03-13 08:48
closing due to inactivity, please re-open if it is still outstanding

**Comment by kasicka** [comment] 2018-03-13 09:15
I have just one test failing on master on RHEL and Rawhide, otherwise seems good or might be related to build environment.

=== release test-child-process-spawnsync-validation-errors ===
Path: parallel/test-child-process-spawnsync-validation-errors
Mismatched innerFn function calls. Expected exactly 62, actual 42.
    at Object.exports.mustCall (/root/node/test/common/index.js:427:10)
    at Object.expectsError (/root/node/test/common/index.js:717:18)
    at Object.<anonymous> (/root/node/test/parallel/test-child-process-spawnsync-validation-errors.js:14:12)
    at Module._compile (module.js:671:30)
    at Object.Module._extensions..js (module.js:682:10)
    at Module.load (module.js:582:32)
    at tryModuleLoad (module.js:522:12)
    at Function.Module._load (module.js:514:3)
    at Function.Module.runMain (module.js:712:10)
Command: out/Release/node /root/node/test/parallel/test-child-process-spawnsync-validation-errors.js

**Comment by gireeshpunathil** [comment] 2018-03-13 10:21
is it consistently failing for you? I am unable to reproduce. Few suggestions:
 - please run as non-root
 - there are a number of (more than 100) independent pass(..) and fail(...) calls. Please reduce the test case by incrementally removing them - to identify which call is failing.

**Comment by kasicka** [comment] 2018-03-14 13:48
Right, fails only in container.. also upon investigating, the ```!common.isWindows``` part doesn't seem to run in container, not sure why.

**Comment by gireeshpunathil** [comment] 2018-03-15 07:37
thanks. Container spec please? I will attempt a reproduce.

**Comment by gireeshpunathil** [comment] 2018-03-15 12:26
what does `node -e 'console.log(process.getuid())'` print for you? 0?

**Comment by gireeshpunathil** [comment] 2018-03-15 12:28
and `node -e 'console.log(process.getgid())'`

**Comment by kasicka** [comment] 2018-03-15 12:48
Just plain Fedora Rawhide container.
Yes, both are 0, which explains failed test, but shouldn't it fail on v9 and v8 too?

**Comment by gireeshpunathil** [comment] 2018-03-15 13:05
thanks for the confirmation, the test has changed recently, though I did not check the exact nature of change.

Hope that explains.

**Comment by gireeshpunathil** [comment] 2018-03-15 13:06
@kasicka - feel free to come up with a PR to fix it. :)

**Comment by gireeshpunathil** [comment] 2018-03-20 11:57
closing as answered and explained, the identified issue tracked under https://github.com/nodejs/node/issues/19371 .

**Closed by gireeshpunathil** 2018-03-20 11:57 UTC

**Comment by gireeshpunathil** [comment] 2018-03-29 11:04
@kasicka - fyi, this is fixed via https://github.com/nodejs/node/pull/19554
